Repository woowacourse-teams/2024-ody, pull requests merged in 2024-10, with the labels that each got.

#631 hotfix: 주소 수도권 검증 로직 제거
  backend/src/main/java/com/ody/meeting/domain/Location.java
  backend/src/test/java/com/ody/meeting/domain/LocationTest.java
Labels: BE, BUG

#627 release: 안드로이드 1.0.0 출시
  android/app/build.gradle.kts
  android/app/proguard-rules.pro
Labels: AN, RELEASE

#642 hotfix: merge hotfix from main into develop
  backend/build.gradle
  backend/src/main/java/com/ody/common/config/FlywayConfig.java
  backend/src/main/java/com/ody/common/config/ReplicationDataSourceRouter.java
  backend/src/main/java/com/ody/common/config/ReplicationType.java
  backend/src/main/java/com/ody/common/validator/SupportRegionValidator.java
  backend/src/main/java/com/ody/meeting/domain/Location.java
  backend/src/main/java/com/ody/meeting/service/MeetingService.java
  backend/src/main/java/com/ody/notification/domain/FcmTopic.java
  backend/src/main/java/com/ody/notification/domain/Notification.java
  backend/src/main/java/com/ody/notification/repository/NotificationRepository.java
  backend/src/main/java/com/ody/notification/service/FcmPushSender.java
  backend/src/main/java/com/ody/notification/service/NotificationService.java
  backend/src/main/resources/application-dev.yml
  backend/src/main/resources/application-local.yml
  backend/src/main/resources/application-prod.yml
  backend/src/main/resources/common.yml
  backend/src/main/resources/db/migration/V3__alter_character_set.sql
  backend/src/test/java/com/ody/common/validator/SupportRegionValidatorTest.java
  backend/src/test/java/com/ody/meeting/domain/LocationTest.java
  backend/src/test/java/com/ody/notification/repository/NotificationRepositoryTest.java
  backend/src/test/resources/application.yml
Labels: BE

#629 refactor: 현재 위치 가져오는 객체 생성 및 분리
  android/app/src/main/java/com/mulberry/ody/data/local/service/EtaDashboardWorker.kt
  android/app/src/main/java/com/mulberry/ody/data/remote/thirdparty/address/KakaoAddressRepository.kt
  android/app/src/main/java/com/mulberry/ody/di/AppModule.kt
  android/app/src/main/java/com/mulberry/ody/presentation/common/gps/GeoLocationHelper.kt
  android/app/src/main/java/com/mulberry/ody/presentation/common/gps/LocationHelper.kt
  android/app/src/main/java/com/mulberry/ody/presentation/join/MeetingJoinActivity.kt
  android/app/src/main/java/com/mulberry/ody/presentation/join/MeetingJoinViewModel.kt
  android/app/src/test/java/com/mulberry/ody/fake/FakeLocationHelper.kt
  android/app/src/test/java/com/mulberry/ody/presentation/join/MeetingJoinViewModelTest.kt
Labels: AN, REFACTOR

#644 refactor: 초대코드 검증 시 참여여부 확인하도록 수정
  backend/src/main/java/com/ody/mate/service/MateService.java
  backend/src/main/java/com/ody/meeting/controller/MeetingController.java
  backend/src/main/java/com/ody/meeting/service/MeetingService.java
  backend/src/test/java/com/ody/meeting/service/MeetingServiceTest.java
Labels: BE, REFACTOR

#659 feat: 출발지 입력할 때 현재 위치 눌러서 가져오기로 변경
  android/app/src/main/java/com/mulberry/ody/presentation/join/MeetingJoinActivity.kt
  android/app/src/main/res/drawable/ic_current_location.xml
  android/app/src/main/res/layout/activity_meeting_join.xml
Labels: AN, FEATURE

#661 feat: 에러 메시지 구체화
  android/app/src/main/java/com/mulberry/ody/presentation/invitecode/InviteCodeActivity.kt
  android/app/src/main/java/com/mulberry/ody/presentation/invitecode/InviteCodeViewModel.kt
  android/app/src/main/res/values/strings.xml
  android/app/src/test/java/com/mulberry/ody/fake/FakeMeetingRepository.kt
Labels: AN, FEATURE

#664 refactor: 좌표 자르는 compress 함수 삭제
  android/app/src/main/java/com/mulberry/ody/data/remote/core/entity/join/mapper/JoinRequestMapper.kt
  android/app/src/main/java/com/mulberry/ody/data/remote/core/entity/meeting/mapper/MeetingRequestMapper.kt
  android/app/src/main/java/com/mulberry/ody/data/remote/core/repository/DefaultMeetingRepository.kt
Labels: AN, REFACTOR

#674 chore: dev 로그 미수집 원인 해결
  backend/docker-compose.yml
Labels: BE, INFRA

#669 feat: Odsay, Google Maps 호출 시 DB 저장
  backend/src/main/java/com/ody/notification/controller/NotificationController.java
  backend/src/main/java/com/ody/notification/controller/NotificationControllerSwagger.java
  backend/src/main/java/com/ody/route/config/RouteConfig.java
  backend/src/main/java/com/ody/route/controller/ApiCallController.java
  backend/src/main/java/com/ody/route/domain/ApiCall.java
  backend/src/main/java/com/ody/route/domain/ClientType.java
  backend/src/main/java/com/ody/route/dto/ApiCallCountResponse.java
  backend/src/main/java/com/ody/route/repository/ApiCallRepository.java
  backend/src/main/java/com/ody/route/service/ApiCallService.java
  backend/src/main/java/com/ody/route/service/GoogleRouteClient.java
  backend/src/main/java/com/ody/route/service/OdsayRouteClient.java
  backend/src/main/java/com/ody/route/service/RouteClient.java
  backend/src/main/java/com/ody/route/service/RouteService.java
  backend/src/main/resources/db/migration/V4__create_table_api-call.sql
  backend/src/test/java/com/ody/common/BaseRepositoryTest.java
  backend/src/test/java/com/ody/common/DatabaseCleaner.java
  backend/src/test/java/com/ody/common/FixtureGenerator.java
  backend/src/test/java/com/ody/common/FixtureGeneratorConfig.java
  backend/src/test/java/com/ody/member/controller/MemberControllerTest.java
  backend/src/test/java/com/ody/route/controller/ApiCallControllerTest.java
  backend/src/test/java/com/ody/route/repository/ApiCallRepositoryTest.java
  backend/src/test/java/com/ody/route/service/ApiCallServiceTest.java
  backend/src/test/java/com/ody/route/service/RouteServiceTest.java
  backend/src/test/java/com/ody/route/service/StubGoogleRouteClient.java
  backend/src/test/java/com/ody/route/service/StubOdsayRouteClient.java
Labels: BE, FEATURE

#687 feat: NoResourceFoundException error handling
  backend/src/main/java/com/ody/common/exception/GlobalExceptionHandler.java
Labels: BE, FEATURE

#684 refactor: NotificationHelper 리팩터링
  android/app/src/main/java/com/mulberry/ody/presentation/notification/NotificationHelper.kt
Labels: AN, REFACTOR

#682 design: 주소 입력 화면의 windowSoftInputMode 속성 추가
  android/app/src/main/AndroidManifest.xml
Labels: AN, DESIGN

#683 refactor: 약속 개설 시 입력 순서 변경 및 개설 완료 화면 제거
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/java/com/mulberry/ody/presentation/creation/MeetingCreationActivity.kt
  android/app/src/main/java/com/mulberry/ody/presentation/creation/MeetingCreationNavigateAction.kt
  android/app/src/main/java/com/mulberry/ody/presentation/creation/MeetingCreationViewModel.kt
  android/app/src/main/java/com/mulberry/ody/presentation/creation/complete/MeetingCompletionActivity.kt
  android/app/src/main/res/drawable/ic_happy_ody.xml
  android/app/src/main/res/layout/activity_meeting_completion.xml
  android/app/src/main/res/values/strings.xml
Labels: AN, REFACTOR

#675 refactor: refreshtoken 순환 참조 해결
  android/app/src/main/java/com/mulberry/ody/data/local/repository/DefaultAuthTokenRepository.kt
  android/app/src/main/java/com/mulberry/ody/data/remote/thirdparty/login/kakao/KakaoLoginRepository.kt
  android/app/src/main/java/com/mulberry/ody/data/remote/thirdparty/login/kakao/KakaoOAuthLoginService.kt
  android/app/src/main/java/com/mulberry/ody/data/retrofit/AccessTokenInterceptor.kt
  android/app/src/main/java/com/mulberry/ody/di/NetworkModule.kt
  android/app/src/main/java/com/mulberry/ody/domain/apiresult/ApiResultExtensions.kt
  android/app/src/main/java/com/mulberry/ody/domain/repository/ody/AuthTokenRepository.kt
  android/app/src/main/java/com/mulberry/ody/domain/repository/ody/LoginRepository.kt
  android/app/src/main/java/com/mulberry/ody/presentation/login/LoginViewModel.kt
  android/app/src/main/java/com/mulberry/ody/presentation/setting/SettingActivity.kt
  android/app/src/main/java/com/mulberry/ody/presentation/setting/SettingViewModel.kt
Labels: AN, REFACTOR

#690 chore: android cd 트리거 브랜치 네임으로 변경
  .github/workflows/android-cd-dev.yml
Labels: AN, INFRA

#685 test: test에 generator를 사용하도록 변경
  backend/src/test/java/com/ody/auth/controller/AuthControllerTest.java
  backend/src/test/java/com/ody/common/BaseControllerTest.java
  backend/src/test/java/com/ody/common/BaseServiceTest.java
  backend/src/test/java/com/ody/common/DtoGenerator.java
  backend/src/test/java/com/ody/common/FixtureGenerator.java
  backend/src/test/java/com/ody/common/mapper/TimeSerializerTest.java
  backend/src/test/java/com/ody/eta/service/EtaServiceTest.java
  backend/src/test/java/com/ody/mate/service/MateServiceTest.java
  backend/src/test/java/com/ody/meeting/controller/MeetingControllerTest.java
  backend/src/test/java/com/ody/meeting/service/MeetingServiceTest.java
  backend/src/test/java/com/ody/member/service/MemberServiceTest.java
  backend/src/test/java/com/ody/notification/service/NotificationServiceTest.java
Labels: BE, TEST

#691 fix: WorkManager 작업이 수행되지 않는 버그 해결
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/java/com/mulberry/ody/OdyApplication.kt
  android/app/src/main/java/com/mulberry/ody/data/local/repository/DefaultMatesEtaRepository.kt
  android/app/src/main/java/com/mulberry/ody/data/local/service/EtaDashboardAlarm.kt
  android/app/src/main/java/com/mulberry/ody/data/local/service/EtaDashboardCloseBroadcastReceiver.kt
  android/app/src/main/java/com/mulberry/ody/data/local/service/EtaDashboardNotification.kt
  android/app/src/main/java/com/mulberry/ody/data/local/service/EtaDashboardOpenBroadcastReceiver.kt
  android/app/src/main/java/com/mulberry/ody/data/local/service/EtaDashboardService.kt
  android/app/src/main/java/com/mulberry/ody/data/local/service/EtaDashboardWorker.kt
  android/app/src/main/java/com/mulberry/ody/data/remote/core/repository/DefaultMeetingRepository.kt
  android/app/src/main/java/com/mulberry/ody/data/remote/core/service/MeetingService.kt
  android/app/src/main/java/com/mulberry/ody/data/remote/thirdparty/fcm/service/FCMService.kt
  android/app/src/main/java/com/mulberry/ody/di/AppModule.kt
  android/app/src/main/java/com/mulberry/ody/domain/apiresult/ApiResultExtensions.kt
  android/app/src/main/java/com/mulberry/ody/domain/common/LocalDateTimeExtensions.kt
  android/app/src/main/java/com/mulberry/ody/domain/repository/ody/MatesEtaRepository.kt
  android/app/src/main/java/com/mulberry/ody/domain/repository/ody/MeetingRepository.kt
  android/app/src/main/java/com/mulberry/ody/presentation/join/MeetingJoinViewModel.kt
  android/app/src/main/java/com/mulberry/ody/presentation/notification/FCMNotification.kt
  android/app/src/main/java/com/mulberry/ody/presentation/notification/NotificationHelper.kt
  android/app/src/main/res/values/strings.xml
  android/app/src/test/java/com/mulberry/ody/fake/FakeMatesEtaRepository.kt
  android/app/src/test/java/com/mulberry/ody/fake/FakeMeetingRepository.kt
Labels: AN, BUG

#680 fix: 약속방 로그 목록 조회 시 입장 로그가 출발 알림 로그보다 먼저 출력되도록 수정
  backend/src/main/java/com/ody/common/domain/BaseEntity.java
  backend/src/main/java/com/ody/eta/domain/Eta.java
  backend/src/main/java/com/ody/mate/domain/Mate.java
  backend/src/main/java/com/ody/member/domain/Member.java
  backend/src/main/java/com/ody/notification/domain/Notification.java
  backend/src/main/java/com/ody/notification/repository/NotificationRepository.java
  backend/src/main/java/com/ody/notification/service/NotificationService.java
  backend/src/main/resources/db/migration/V5__alter__timestamp__set-nano.sql
  backend/src/test/java/com/ody/common/FixtureGenerator.java
  backend/src/test/java/com/ody/notification/repository/NotificationRepositoryTest.java
  backend/src/test/java/com/ody/notification/service/NotificationServiceTest.java
Labels: BE, BUG

#698 chore: 무중단 배포 적용
  .github/workflows/backend-cd-prod.yml
  backend/src/main/resources/common.yml
Labels: BE, INFRA

#697 refactor: BindingFragment에서 analytics 가능하게 수정
  android/app/src/main/java/com/mulberry/ody/presentation/common/binding/BindingFragment.kt
Labels: AN, REFACTOR

#695 refactor: ViewModel의 LiveData를 Flow로 변경
  android/app/build.gradle.kts
  android/app/src/main/java/com/mulberry/ody/presentation/address/AddressSearchFragment.kt
  android/app/src/main/java/com/mulberry/ody/presentation/address/AddressSearchViewModel.kt
  android/app/src/main/java/com/mulberry/ody/presentation/creation/MeetingCreationActivity.kt
  android/app/src/main/java/com/mulberry/ody/presentation/creation/MeetingCreationViewModel.kt
  android/app/src/main/java/com/mulberry/ody/presentation/creation/date/MeetingDateFragment.kt
  android/app/src/main/java/com/mulberry/ody/presentation/creation/destination/MeetingDestinationFragment.kt
  android/app/src/main/java/com/mulberry/ody/presentation/creation/time/MeetingTimeFragment.kt
  android/app/src/main/java/com/mulberry/ody/presentation/login/LoginActivity.kt
  android/app/src/main/java/com/mulberry/ody/presentation/login/LoginViewModel.kt
  android/app/src/main/java/com/mulberry/ody/presentation/setting/SettingActivity.kt
  android/app/src/main/java/com/mulberry/ody/presentation/setting/SettingViewModel.kt
  android/app/src/test/java/com/mulberry/ody/presentation/address/AddressSearchViewModelTest.kt
  android/app/src/test/java/com/mulberry/ody/presentation/creation/MeetingCreationViewModelTest.kt
  android/gradle/libs.versions.toml
Labels: AN, REFACTOR

#723 hotfix: 스케줄링 정확한 알림 권한 수정
  android/app/src/main/AndroidManifest.xml
Labels: AN, BUG

#725 release: 안드로이드 1.1.1 출시
  android/app/build.gradle.kts
Labels: AN, RELEASE

#711 chore: android ci 빌드 전 clean 추가
  .github/workflows/android-ci-dev.yml
Labels: AN, INFRA

#705 design: 9인치, 12인치 화면에서 DatePicker, TimePicker 크기 수정
  android/app/src/main/res/layout-sw1080dp/fragment_meeting_date.xml
  android/app/src/main/res/layout-sw1080dp/fragment_meeting_time.xml
  android/app/src/main/res/layout-sw720dp/fragment_meeting_date.xml
  android/app/src/main/res/layout-sw720dp/fragment_meeting_time.xml
Labels: AN, DESIGN

#728 refactor: color primary, secondary 적용
  android/app/src/main/res/drawable/ic_sad_ody.xml
  android/app/src/main/res/drawable/ic_together_ody.xml
  android/app/src/main/res/drawable/rectangle_cream_downside_shadow_radius_30.xml
  android/app/src/main/res/drawable/rectangle_edit_text.xml
  android/app/src/main/res/drawable/rectangle_hamburger_menu.xml
  android/app/src/main/res/drawable/rectangle_white_radius_15.xml
  android/app/src/main/res/drawable/selector_button_color.xml
  android/app/src/main/res/layout/activity_invite_code.xml
  android/app/src/main/res/layout/activity_join_complete.xml
  android/app/src/main/res/layout/activity_login.xml
  android/app/src/main/res/layout/activity_meeting_creation.xml
  android/app/src/main/res/layout/activity_meeting_join.xml
  android/app/src/main/res/layout/activity_meetings.xml
  android/app/src/main/res/layout/activity_splash.xml
  android/app/src/main/res/layout/dialog_loading.xml
  android/app/src/main/res/layout/dialog_withdrawal.xml
  android/app/src/main/res/layout/fragment_address_search.xml
  android/app/src/main/res/layout/fragment_eta_dashboard.xml
  android/app/src/main/res/layout/fragment_eta_dashboard_guide_first.xml
  android/app/src/main/res/layout/fragment_eta_dashboard_guide_second.xml
  android/app/src/main/res/layout/fragment_meeting_date.xml
  android/app/src/main/res/layout/fragment_meeting_destination.xml
  android/app/src/main/res/layout/fragment_meeting_name.xml
  android/app/src/main/res/layout/fragment_meeting_time.xml
  android/app/src/main/res/layout/fragment_notification_log.xml
  android/app/src/main/res/layout/item_address_search.xml
  android/app/src/main/res/layout/item_eta_dashboard.xml
  android/app/src/main/res/layout/item_invite_code_log.xml
  android/app/src/main/res/layout/item_meeting_catalog.xml
  android/app/src/main/res/layout/layout_missing_tooltip.xml
  android/app/src/main/res/layout/layout_navigate_to_eta.xml
  android/app/src/main/res/values-night/themes.xml
  android/app/src/main/res/values/colors.xml
  android/app/src/main/res/values/styles.xml
  android/app/src/main/res/values/themes.xml
Labels: AN, REFACTOR, DOCS

#709 feat: 어드민 API CORS 설정
  backend/src/main/java/com/ody/common/config/WebConfig.java
  backend/src/main/resources/common.yml
  backend/src/test/java/com/ody/notification/service/NotificationServiceTest.java
  backend/src/test/resources/application.yml
Labels: BE, FEATURE

#739 fix: dev 서버 복구를 위한 #680 revert
  backend/src/main/java/com/ody/common/domain/BaseEntity.java
  backend/src/main/java/com/ody/eta/domain/Eta.java
  backend/src/main/java/com/ody/mate/domain/Mate.java
  backend/src/main/java/com/ody/member/domain/Member.java
  backend/src/main/java/com/ody/notification/domain/Notification.java
  backend/src/main/java/com/ody/notification/repository/NotificationRepository.java
  backend/src/main/java/com/ody/notification/service/NotificationService.java
  backend/src/main/resources/db/migration/V5__alter__timestamp__set-nano.sql
  backend/src/test/java/com/ody/common/FixtureGenerator.java
  backend/src/test/java/com/ody/notification/repository/NotificationRepositoryTest.java
  backend/src/test/java/com/ody/notification/service/NotificationServiceTest.java
Labels: BE, INFRA

#734 design: 재촉 알림 메시지 수정
  android/app/src/main/res/values/strings.xml
Labels: AN, DESIGN

#735 design: splash 로고 깨지는 문제 수정
  android/app/src/main/res/drawable/ic_splash_logo.xml
  android/app/src/main/res/drawable/splash_screen.xml
Labels: AN, DESIGN

#731 refactor: ViewModel의 LiveData를 Flow로 변경
  android/app/src/main/java/com/mulberry/ody/data/local/db/MateEtaInfoDao.kt
  android/app/src/main/java/com/mulberry/ody/data/local/repository/DefaultMatesEtaRepository.kt
  android/app/src/main/java/com/mulberry/ody/domain/repository/ody/MatesEtaRepository.kt
  android/app/src/main/java/com/mulberry/ody/presentation/LifecycleExtensions.kt
  android/app/src/main/java/com/mulberry/ody/presentation/address/AddressSearchFragment.kt
  android/app/src/main/java/com/mulberry/ody/presentation/common/BaseViewModel.kt
  android/app/src/main/java/com/mulberry/ody/presentation/common/Event.kt
  android/app/src/main/java/com/mulberry/ody/presentation/common/MutableSingleLiveData.kt
  android/app/src/main/java/com/mulberry/ody/presentation/common/SingleLiveData.kt
  android/app/src/main/java/com/mulberry/ody/presentation/creation/MeetingCreationActivity.kt
  android/app/src/main/java/com/mulberry/ody/presentation/creation/MeetingCreationViewModel.kt
  android/app/src/main/java/com/mulberry/ody/presentation/creation/date/MeetingDateFragment.kt
  android/app/src/main/java/com/mulberry/ody/presentation/creation/destination/MeetingDestinationFragment.kt
  android/app/src/main/java/com/mulberry/ody/presentation/creation/time/MeetingTimeFragment.kt
  android/app/src/main/java/com/mulberry/ody/presentation/invitecode/InviteCodeActivity.kt
  android/app/src/main/java/com/mulberry/ody/presentation/invitecode/InviteCodeViewModel.kt
  android/app/src/main/java/com/mulberry/ody/presentation/join/MeetingJoinActivity.kt
  android/app/src/main/java/com/mulberry/ody/presentation/join/MeetingJoinViewModel.kt
  android/app/src/main/java/com/mulberry/ody/presentation/login/LoginActivity.kt
  android/app/src/main/java/com/mulberry/ody/presentation/meetings/MeetingsActivity.kt
  android/app/src/main/java/com/mulberry/ody/presentation/meetings/MeetingsViewModel.kt
  android/app/src/main/java/com/mulberry/ody/presentation/room/MeetingRoomActivity.kt
  android/app/src/main/java/com/mulberry/ody/presentation/room/MeetingRoomViewModel.kt
  android/app/src/main/java/com/mulberry/ody/presentation/room/etadashboard/EtaDashboardFragment.kt
  android/app/src/main/java/com/mulberry/ody/presentation/room/log/NotificationLogFragment.kt
  android/app/src/main/java/com/mulberry/ody/presentation/setting/SettingActivity.kt
  android/app/src/test/java/com/mulberry/ody/fake/FakeMatesEtaRepository.kt
  android/app/src/test/java/com/mulberry/ody/presentation/address/AddressSearchViewModelTest.kt
  android/app/src/test/java/com/mulberry/ody/presentation/creation/MeetingCreationViewModelTest.kt
  android/app/src/test/java/com/mulberry/ody/presentation/invitecode/InviteCodeViewModelTest.kt
  android/app/src/test/java/com/mulberry/ody/presentation/join/MeetingJoinViewModelTest.kt
  android/app/src/test/java/com/mulberry/ody/presentation/meetings/MeetingsViewModelTest.kt
  android/app/src/test/java/com/mulberry/ody/presentation/room/MeetingRoomViewModelTest.kt
  android/app/src/test/java/com/mulberry/ody/util/TestUtil.kt
  android/app/src/test/java/com/mulberry/ody/util/TestUtils.kt
Labels: AN, REFACTOR

#749 feat: revert 코드 복구를 위한 #739 revert
  backend/src/main/java/com/ody/common/domain/BaseEntity.java
  backend/src/main/java/com/ody/eta/domain/Eta.java
  backend/src/main/java/com/ody/mate/domain/Mate.java
  backend/src/main/java/com/ody/member/domain/Member.java
  backend/src/main/java/com/ody/notification/domain/Notification.java
  backend/src/main/java/com/ody/notification/repository/NotificationRepository.java
  backend/src/main/java/com/ody/notification/service/NotificationService.java
  backend/src/main/resources/db/migration/V5__alter__timestamp__set-nano.sql
  backend/src/test/java/com/ody/common/FixtureGenerator.java
  backend/src/test/java/com/ody/notification/repository/NotificationRepositoryTest.java
  backend/src/test/java/com/ody/notification/service/NotificationServiceTest.java
Labels: BE, FEATURE

#729 fix/feat: flyway V5 DML이 적용되지 않는 문제 해결 + 테스트 컨테이너 적용
  .github/workflows/backend-cd-dev.yml
  .github/workflows/backend-cd-prod.yml
  .github/workflows/backend-ci-dev.yml
  .github/workflows/backend-ci-prod.yml
  backend/build.gradle
  backend/docker-compose-local.yml
  backend/docker-compose.yml
  backend/src/main/java/com/ody/eta/repository/EtaRepository.java
  backend/src/main/resources/application-dev.yml
  backend/src/main/resources/application-local.yml
  backend/src/main/resources/application-prod.yml
  backend/src/main/resources/common.yml
  backend/src/main/resources/db/migration/V2__alter_notification_type_check.sql
  backend/src/main/resources/db/migration/V3__alter_character_set.sql
  backend/src/main/resources/db/migration/V5__alter__timestamp__set-nano.sql
  backend/src/test/java/com/ody/common/BaseRepositoryTest.java
  backend/src/test/java/com/ody/common/DatabaseCleaner.java
  backend/src/test/java/com/ody/eta/repository/EtaRepositoryTest.java
  backend/src/test/java/com/ody/member/repository/MemberRepositoryTest.java
  backend/src/test/resources/application.yml
Labels: BE, BUG, FEATURE

#744 design: 주소 검색 item 디자인 수정
  android/app/src/main/java/com/mulberry/ody/presentation/address/AddressSearchFragment.kt
  android/app/src/main/java/com/mulberry/ody/presentation/common/DimensionExtensions.kt
  android/app/src/main/java/com/mulberry/ody/presentation/setting/SettingActivity.kt
Labels: AN, DESIGN

#746 fix: 로그인 후 뒤로가기를 하면 앱이 종료되지 않고 로그인 화면으로 돌아가는 문제 수정
  android/app/src/main/java/com/mulberry/ody/presentation/login/LoginActivity.kt
Labels: AN, BUG

#701 fix: 새벽 4시에 약속 삭제 로직 Lazy 에러 해결
  backend/src/main/java/com/ody/meeting/service/MeetingService.java
  backend/src/test/java/com/ody/meeting/service/MeetingServiceTest.java
Labels: BE, BUG

#716 feat: 회원 탈퇴 시 fcmTopic 구독 취소
  backend/src/main/java/com/ody/mate/repository/MateRepository.java
  backend/src/main/java/com/ody/mate/service/MateService.java
  backend/src/main/java/com/ody/member/service/MemberService.java
  backend/src/main/java/com/ody/notification/domain/FcmTopic.java
  backend/src/main/java/com/ody/notification/service/NotificationService.java
  backend/src/test/java/com/ody/common/FixtureGenerator.java
  backend/src/test/java/com/ody/mate/repository/MateRepositoryTest.java
  backend/src/test/java/com/ody/mate/service/MateServiceTest.java
  backend/src/test/java/com/ody/notification/service/NotificationServiceTest.java
Labels: BE, FEATURE

#733 fix: 같은 약속에 있는 사람들이 탈퇴한 회원의 출발 알림 받는 문제 해결
  backend/src/main/java/com/ody/meeting/service/MeetingService.java
  backend/src/main/java/com/ody/notification/config/FcmConfig.java
  backend/src/main/java/com/ody/notification/dto/request/FcmGroupSendRequest.java
  backend/src/main/java/com/ody/notification/service/FcmPushSender.java
  backend/src/main/java/com/ody/notification/service/FcmSubscriber.java
  backend/src/main/java/com/ody/notification/service/NotificationService.java
  backend/src/main/java/com/ody/util/InstantConverter.java
  backend/src/test/java/com/ody/common/BaseControllerTest.java
  backend/src/test/java/com/ody/common/BaseServiceTest.java
  backend/src/test/java/com/ody/common/FixtureGenerator.java
  backend/src/test/java/com/ody/mate/service/MateServiceTest.java
  backend/src/test/java/com/ody/meeting/service/MeetingServiceTest.java
  backend/src/test/java/com/ody/member/controller/MemberControllerTest.java
  backend/src/test/java/com/ody/notification/service/FcmPushSenderTest.java
  backend/src/test/java/com/ody/notification/service/NotificationServiceTest.java
Labels: BE, BUG

#761 fix: Foreground Service 여러 작업 수행 가능하도록 수정
  android/app/src/main/java/com/mulberry/ody/data/local/service/EtaDashboardCloseBroadcastReceiver.kt
  android/app/src/main/java/com/mulberry/ody/data/local/service/EtaDashboardService.kt
Labels: AN, BUG

#732 feat: 서드파티 제어 및 조회 API 구현
  backend/src/main/java/com/ody/route/controller/ApiCallController.java
  backend/src/main/java/com/ody/route/domain/ApiCall.java
  backend/src/main/java/com/ody/route/domain/ClientType.java
  backend/src/main/java/com/ody/route/dto/ApiCallEnabledResponse.java
  backend/src/main/java/com/ody/route/mapper/RouteClientMapper.java
  backend/src/main/java/com/ody/route/repository/ApiCallRepository.java
  backend/src/main/java/com/ody/route/service/ApiCallService.java
  backend/src/main/java/com/ody/route/service/RouteService.java
  backend/src/main/resources/db/migration/V6__add_enabled_column.sql
  backend/src/test/java/com/ody/route/domain/ApiCallTest.java
  backend/src/test/java/com/ody/route/repository/ApiCallRepositoryTest.java
  backend/src/test/java/com/ody/route/service/ApiCallServiceTest.java
  backend/src/test/java/com/ody/route/service/RouteServiceTest.java
Labels: BE, FEATURE

#762 feat: AlarmManager 작업들 Local DB에 저장
  android/app/src/main/java/com/mulberry/ody/data/local/db/EtaReservationDao.kt
  android/app/src/main/java/com/mulberry/ody/data/local/db/OdyDatabase.kt
  android/app/src/main/java/com/mulberry/ody/data/local/entity/reserve/EtaReservationEntity.kt
  android/app/src/main/java/com/mulberry/ody/data/local/repository/DefaultMatesEtaRepository.kt
  android/app/src/main/java/com/mulberry/ody/data/local/service/EtaDashboardAlarm.kt
  android/app/src/main/java/com/mulberry/ody/data/local/service/EtaDashboardCloseBroadcastReceiver.kt
  android/app/src/main/java/com/mulberry/ody/data/local/service/EtaDashboardOpenBroadcastReceiver.kt
  android/app/src/main/java/com/mulberry/ody/data/local/service/EtaDashboardService.kt
  android/app/src/main/java/com/mulberry/ody/di/DBModule.kt
  android/app/src/main/java/com/mulberry/ody/domain/repository/ody/MatesEtaRepository.kt
  android/app/src/main/java/com/mulberry/ody/presentation/join/MeetingJoinViewModel.kt
  android/app/src/main/java/com/mulberry/ody/presentation/login/LoginViewModel.kt
  android/app/src/main/java/com/mulberry/ody/presentation/room/MeetingRoomViewModel.kt
  android/app/src/main/java/com/mulberry/ody/presentation/setting/SettingViewModel.kt
  android/app/src/test/java/com/mulberry/ody/fake/FakeMatesEtaRepository.kt
Labels: AN, FEATURE

#778 design: 약속 개설하기, 약속 참여하기 버튼 누르면 면적 넓히기
  android/app/src/main/res/layout/activity_meetings.xml
Labels: AN, DESIGN

#777 refactor: 사용 안하는 파일 제거
  android/app/src/main/res/layout/item_invite_code_log.xml
Labels: AN, DESIGN

#765 fix: 현위치 가져올 때 무한 로딩되는 버그 해결
  android/app/src/main/java/com/mulberry/ody/data/local/service/EtaDashboardService.kt
  android/app/src/main/java/com/mulberry/ody/domain/apiresult/ApiResultExtensions.kt
  android/app/src/main/java/com/mulberry/ody/presentation/common/gps/GeoLocationHelper.kt
  android/app/src/main/java/com/mulberry/ody/presentation/common/gps/LocationHelper.kt
  android/app/src/main/java/com/mulberry/ody/presentation/creation/MeetingCreationViewModel.kt
  android/app/src/main/java/com/mulberry/ody/presentation/creation/destination/MeetingDestinationFragment.kt
  android/app/src/main/java/com/mulberry/ody/presentation/join/MeetingJoinActivity.kt
  android/app/src/main/java/com/mulberry/ody/presentation/join/MeetingJoinViewModel.kt
  android/app/src/main/res/layout/activity_meeting_join.xml
  android/app/src/main/res/layout/fragment_meeting_destination.xml
  android/app/src/main/res/values/strings.xml
  android/app/src/test/java/com/mulberry/ody/fake/FakeLocationHelper.kt
  android/app/src/test/java/com/mulberry/ody/presentation/creation/MeetingCreationViewModelTest.kt
  android/app/src/test/java/com/mulberry/ody/presentation/join/MeetingJoinViewModelTest.kt
Labels: AN, BUG

#788 design: 새로운 로그인 화면 다크모드 추가
  android/app/src/main/res/drawable/ic_happy_ody.xml
  android/app/src/main/res/layout-sw1080dp/activity_login.xml
  android/app/src/main/res/layout-sw720dp/activity_login.xml
  android/app/src/main/res/layout/activity_login.xml
  android/app/src/main/res/values/styles.xml
Labels: AN, DESIGN

#775 design: 약속 이름이 길 때 말줄임표 대신 약속 이름을 최대한 보여줄 수 있도록 수정
  android/app/src/main/res/layout/item_meeting_catalog.xml
  android/app/src/main/res/layout/toolbar_notification_log.xml
Labels: AN, DESIGN

#768 fix: 원(인디케이터)을 통해 강제 이동 가능 막기
  android/app/src/main/res/layout/activity_meeting_creation.xml
Labels: AN, BUG

#767 fix: refresh token 만료 시에도 자동 로그인 하는 문제
  android/app/src/main/java/com/mulberry/ody/data/remote/thirdparty/login/kakao/KakaoLoginRepository.kt
Labels: AN

#717 feat: 외부 API 어드민 페이지 구축
  backend/build.gradle
  backend/src/main/java/com/ody/route/controller/ApiCallPageController.java
  backend/src/main/resources/common.yml
  backend/src/main/resources/static/css/api-call.css
  backend/src/main/resources/static/js/api-call.js
  backend/src/main/resources/templates/api-call.html
Labels: BE, FEATURE

#736 chore: ci/cd 롤백 전략 구축
  .github/workflows/backend-cd-dev.yml
  .github/workflows/backend-cd-prod.yml
Labels: BE, INFRA

#796 fix: 다크모드 초대코드 복사 창에서 왼쪽 위 흰색 제거
  android/app/src/main/res/layout/fragment_notification_log.xml
Labels: AN, BUG

#776 design: 약속 개설하기 버튼 이름 변경
  android/app/src/main/res/layout/activity_meetings.xml
  android/app/src/main/res/values/strings.xml
Labels: AN, DESIGN

#764 fix: 약속 참여 후 로그 화면으로 navigate되지 않는 버그 해결
  android/app/src/main/java/com/mulberry/ody/presentation/join/MeetingJoinActivity.kt
Labels: AN, BUG

#779 design: 오디 버튼 비활성화 토스트 메시지 변경
  android/app/src/main/res/values/strings.xml
Labels: AN, DESIGN

#812 chore: prod cd 트리거 수정
  .github/workflows/android-cd-dev.yml
  .github/workflows/backend-cd-prod.yml
Labels: AN, BE, INFRA

#793 refactor: 상태에 따라 소요시간을 mapping 해주는 로직 삭제
  backend/src/main/java/com/ody/eta/dto/response/MateEtaResponse.java
  backend/src/main/java/com/ody/meeting/controller/MeetingController.java
Labels: BE, REFACTOR

#781 refactor: RouteClient 생성 로직 통일
  backend/src/main/java/com/ody/route/config/RouteClientProperties.java
  backend/src/main/java/com/ody/route/config/RouteClientProperty.java
  backend/src/main/java/com/ody/route/config/RouteConfig.java
  backend/src/main/java/com/ody/route/config/RouteProperties.java
  backend/src/main/java/com/ody/route/service/GoogleRouteClient.java
  backend/src/main/java/com/ody/route/service/OdsayRouteClient.java
  backend/src/main/resources/common.yml
  backend/src/test/java/com/ody/common/BaseRouteClientTest.java
  backend/src/test/java/com/ody/route/service/GoogleRouteClientTest.java
  backend/src/test/java/com/ody/route/service/OdsayRouteClientTest.java
  backend/src/test/resources/application.yml
Labels: BE, REFACTOR

#800 refactor: 알림 누르고 뒤로가면 약속 목록으로 가게 변경
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/java/com/mulberry/ody/presentation/notification/FCMNotification.kt
Labels: AN, REFACTOR

#804 design: DatePicker, TimePicker 9인치, 12인치 다크모드 수정
  android/app/src/main/res/layout-sw1080dp/fragment_meeting_date.xml
  android/app/src/main/res/layout-sw1080dp/fragment_meeting_time.xml
  android/app/src/main/res/layout-sw720dp/fragment_meeting_date.xml
  android/app/src/main/res/layout-sw720dp/fragment_meeting_time.xml
Labels: AN, DESIGN

#806 fix: 다크모드일 때 스플래시 로고 이상하게 보이는 문제 수정
  android/app/src/main/res/values-night/themes.xml
Labels: AN, BUG

#798 refactor: 약속 시간 이후 30분까지 nudge가 가능하도록 수정
  backend/src/main/java/com/ody/mate/service/MateService.java
  backend/src/test/java/com/ody/mate/service/MateServiceTest.java
Labels: BE, FEATURE

#782 feat: RouteClient 외부 API 요청 응답 로깅
  backend/src/main/java/com/ody/eta/service/EtaService.java
  backend/src/main/java/com/ody/route/config/RouteClientLoggingInterceptor.java
  backend/src/main/java/com/ody/route/config/RouteConfig.java
  backend/src/main/java/com/ody/route/service/RouteService.java
Labels: BE, FEATURE

#743 fix : jasypt 비밀번호 변경으로 인한 재 암호화
  backend/src/main/resources/application-prod.yml
  backend/src/main/resources/common.yml
Labels: BE, BUG

#818 chore: jayspt 비밀번호 충돌 해결
  backend/src/main/resources/application-dev.yml
  backend/src/main/resources/common.yml
Labels: BE, BUG

#794 fix: 출발 도착지가 가까운 경우 0으로 반환되는 문제 해결
  backend/src/main/java/com/ody/mate/service/MateService.java
  backend/src/main/java/com/ody/route/domain/RouteTime.java
  backend/src/main/java/com/ody/route/mapper/OdsayResponseMapper.java
  backend/src/main/java/com/ody/route/service/RouteService.java
  backend/src/test/java/com/ody/route/mapper/OdsayResponseMapperTest.java
  backend/src/test/java/com/ody/route/service/OdsayRouteClientTest.java
  backend/src/test/java/com/ody/route/service/RouteServiceTest.java
Labels: BE, BUG

#799 fix: 탈퇴한 회원 알림 로그 제외
  backend/src/main/java/com/ody/mate/repository/MateRepository.java
  backend/src/main/java/com/ody/mate/service/MateService.java
  backend/src/main/java/com/ody/meeting/controller/MeetingController.java
  backend/src/main/java/com/ody/notification/domain/Notification.java
  backend/src/main/java/com/ody/notification/repository/NotificationRepository.java
  backend/src/main/java/com/ody/notification/service/NotificationService.java
  backend/src/test/java/com/ody/common/FixtureGenerator.java
  backend/src/test/java/com/ody/notification/repository/NotificationRepositoryTest.java
  backend/src/test/java/com/ody/notification/service/NotificationServiceTest.java
Labels: BE, BUG, REFACTOR

#820 fix: RouteClient 호출시 key 오류로 인한 에러
  backend/src/main/resources/common.yml
Labels: BE, BUG

#807 feat: 약속 나가기 기능 구현
  android/app/src/main/java/com/mulberry/ody/data/local/repository/DefaultMatesEtaRepository.kt
  android/app/src/main/java/com/mulberry/ody/data/local/service/EtaDashboardAlarm.kt
  android/app/src/main/java/com/mulberry/ody/data/remote/core/entity/notification/mapper/NotificationLogsResponseMapper.kt
  android/app/src/main/java/com/mulberry/ody/data/remote/core/repository/DefaultMeetingRepository.kt
  android/app/src/main/java/com/mulberry/ody/data/remote/core/service/MeetingService.kt
  android/app/src/main/java/com/mulberry/ody/domain/model/LogType.kt
  android/app/src/main/java/com/mulberry/ody/domain/model/NotificationLog.kt
  android/app/src/main/java/com/mulberry/ody/domain/model/NotificationLogType.kt
  android/app/src/main/java/com/mulberry/ody/domain/repository/ody/MatesEtaRepository.kt
  android/app/src/main/java/com/mulberry/ody/domain/repository/ody/MeetingRepository.kt
  android/app/src/main/java/com/mulberry/ody/presentation/room/MeetingRoomViewModel.kt
  android/app/src/main/java/com/mulberry/ody/presentation/room/log/ExitMeetingRoomDialog.kt
  android/app/src/main/java/com/mulberry/ody/presentation/room/log/NotificationLogBindingAdapter.kt
  android/app/src/main/java/com/mulberry/ody/presentation/room/log/NotificationLogFragment.kt
  android/app/src/main/java/com/mulberry/ody/presentation/room/log/listener/ExitMeetingRoomListener.kt
  android/app/src/main/java/com/mulberry/ody/presentation/room/log/listener/NotificationLogListener.kt
  android/app/src/main/java/com/mulberry/ody/presentation/room/log/model/MeetingDetailUiModel.kt
  android/app/src/main/java/com/mulberry/ody/presentation/room/log/model/MeetingDetailUiModelMapper.kt
  android/app/src/main/java/com/mulberry/ody/presentation/room/log/model/NotificationLogUiModel.kt
  android/app/src/main/res/drawable/ic_exit.xml
  android/app/src/main/res/layout/dialog_exit_meeting_room.xml
  android/app/src/main/res/layout/dialog_withdrawal.xml
  android/app/src/main/res/layout/fragment_notification_log.xml
  android/app/src/main/res/values/strings.xml
  android/app/src/test/java/com/mulberry/ody/TestFixtures.kt
  android/app/src/test/java/com/mulberry/ody/fake/FakeMatesEtaRepository.kt
  android/app/src/test/java/com/mulberry/ody/fake/FakeMeetingRepository.kt
Labels: AN, FEATURE

#825 release: 백엔드 버전 2.2 배포
  android/app/build.gradle.kts
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/java/com/mulberry/ody/data/local/db/OdyDatabase.kt
  android/app/src/main/java/com/mulberry/ody/data/local/entity/eta/MateEtaListTypeConverter.kt
  android/app/src/main/java/com/mulberry/ody/data/remote/core/entity/meeting/mapper/MatesEtaResponseMapper.kt
  android/app/src/main/java/com/mulberry/ody/di/DBModule.kt
  android/app/src/main/java/com/mulberry/ody/domain/model/EtaStatus.kt
  android/app/src/main/java/com/mulberry/ody/domain/model/EtaType.kt
  android/app/src/main/java/com/mulberry/ody/domain/model/MateEta.kt
  android/app/src/main/java/com/mulberry/ody/domain/model/MateEtaInfo.kt
  android/app/src/main/java/com/mulberry/ody/presentation/notification/FCMNotification.kt
  android/app/src/main/java/com/mulberry/ody/presentation/room/etadashboard/EtaDashboardBindingAdapter.kt
  android/app/src/main/java/com/mulberry/ody/presentation/room/etadashboard/model/EtaDurationMinuteTypeUiModel.kt
  android/app/src/main/java/com/mulberry/ody/presentation/room/etadashboard/model/EtaStatusUiModel.kt
  android/app/src/main/java/com/mulberry/ody/presentation/room/etadashboard/model/EtaTypeUiModel.kt
  android/app/src/main/java/com/mulberry/ody/presentation/room/etadashboard/model/EtaTypeUiModelMapper.kt
  android/app/src/main/java/com/mulberry/ody/presentation/room/etadashboard/model/MateEtaUiModel.kt
  android/app/src/main/java/com/mulberry/ody/presentation/room/etadashboard/model/MateEtaUiModelMapper.kt
  android/app/src/main/res/layout-sw1080dp/fragment_meeting_date.xml
  android/app/src/main/res/layout-sw1080dp/fragment_meeting_time.xml
  android/app/src/main/res/layout-sw720dp/fragment_meeting_date.xml
  android/app/src/main/res/layout-sw720dp/fragment_meeting_time.xml
  android/app/src/main/res/layout/item_eta_dashboard.xml
  android/app/src/main/res/values-night/themes.xml
  android/app/src/test/java/com/mulberry/ody/TestFixtures.kt
  android/app/src/test/java/com/mulberry/ody/presentation/room/MeetingRoomViewModelTest.kt
  android/gradle/libs.versions.toml
  backend/src/main/java/com/ody/eta/dto/response/MateEtaResponse.java
  backend/src/main/java/com/ody/mate/controller/MateController.java
  backend/src/main/java/com/ody/mate/controller/MateControllerSwagger.java
  backend/src/main/java/com/ody/mate/repository/MateRepository.java
  backend/src/main/java/com/ody/mate/service/MateService.java
  backend/src/main/java/com/ody/meeting/controller/MeetingController.java
  backend/src/main/java/com/ody/notification/domain/Notification.java
  backend/src/main/java/com/ody/notification/domain/NotificationType.java
  backend/src/main/java/com/ody/notification/repository/NotificationRepository.java
  backend/src/main/java/com/ody/notification/service/NotificationService.java
  backend/src/main/java/com/ody/route/domain/RouteTime.java
  backend/src/main/java/com/ody/route/mapper/OdsayResponseMapper.java
  backend/src/main/java/com/ody/route/service/RouteService.java
  backend/src/main/resources/application-dev.yml
  backend/src/main/resources/application-prod.yml
  backend/src/main/resources/common.yml
  backend/src/main/resources/db/migration/V7__add_notification_type_leave.sql
  backend/src/test/java/com/ody/common/FixtureGenerator.java
  backend/src/test/java/com/ody/mate/service/MateServiceTest.java
  backend/src/test/java/com/ody/notification/repository/NotificationRepositoryTest.java
  backend/src/test/java/com/ody/notification/service/NotificationServiceTest.java
  backend/src/test/java/com/ody/route/mapper/OdsayResponseMapperTest.java
  backend/src/test/java/com/ody/route/service/OdsayRouteClientTest.java
  backend/src/test/java/com/ody/route/service/RouteServiceTest.java
Labels: BE, RELEASE

#828 design: 약속 생성/참여 플로팅 버튼 margin 제거
  android/app/src/main/res/layout/activity_meetings.xml
Labels: AN, DESIGN

#809 refactor: 재촉하기 연속으로 못 누르게 수정
  android/app/src/main/java/com/mulberry/ody/presentation/room/MeetingRoomViewModel.kt
  android/app/src/main/java/com/mulberry/ody/presentation/room/etadashboard/EtaDashboardFragment.kt
  android/app/src/main/res/values/strings.xml
  android/app/src/test/java/com/mulberry/ody/presentation/room/MeetingRoomViewModelTest.kt
Labels: AN, REFACTOR

#826 feat: 약속 시간 30분 지난 후 재촉하면 불가 토스트 메시지
  android/app/src/main/java/com/mulberry/ody/presentation/room/MeetingRoomActivity.kt
  android/app/src/main/java/com/mulberry/ody/presentation/room/MeetingRoomViewModel.kt
  android/app/src/main/res/values/strings.xml
Labels: AN, FEATURE

#832 fix: Room Entity 마이그레이션 버그 수정
  android/app/src/main/java/com/mulberry/ody/data/local/db/OdyDatabase.kt
  android/app/src/main/java/com/mulberry/ody/data/local/entity/eta/MateEtaListTypeConverter.kt
  android/app/src/main/java/com/mulberry/ody/data/local/entity/eta/OldMateEtaListTypeConverter.kt
  android/app/src/main/java/com/mulberry/ody/domain/model/EtaType2.kt
  android/app/src/main/java/com/mulberry/ody/domain/model/MateEta2.kt
Labels: AN, BUG

#816 docs: 리드미 작성
  README.md
  android/README.md
Labels: AN, BE, DOCS

#841 docs: android 리드미 링크 수정
  README.md
Labels: AN, DOCS

#839 refactor: single click listener로 리팩터링
  android/app/src/main/java/com/mulberry/ody/presentation/common/CommonBindingAdapter.kt
  android/app/src/main/java/com/mulberry/ody/presentation/common/listener/SingleClickListener.kt
  android/app/src/main/java/com/mulberry/ody/presentation/room/etadashboard/EtaDashboardBindingAdapter.kt
  android/app/src/main/java/com/mulberry/ody/presentation/room/etadashboard/EtaDashboardGuideFirstFragment.kt
  android/app/src/main/java/com/mulberry/ody/presentation/room/etadashboard/EtaDashboardGuideSecondFragment.kt
  android/app/src/main/java/com/mulberry/ody/presentation/setting/withdrawal/WithDrawalDialog.kt
  android/app/src/main/res/layout-sw1080dp/activity_login.xml
  android/app/src/main/res/layout-sw720dp/activity_login.xml
  android/app/src/main/res/layout/activity_invite_code.xml
  android/app/src/main/res/layout/activity_login.xml
  android/app/src/main/res/layout/activity_meeting_creation.xml
  android/app/src/main/res/layout/activity_meeting_join.xml
  android/app/src/main/res/layout/activity_meetings.xml
  android/app/src/main/res/layout/dialog_exit_meeting_room.xml
  android/app/src/main/res/layout/fragment_address_search.xml
  android/app/src/main/res/layout/fragment_meeting_destination.xml
  android/app/src/main/res/layout/fragment_meeting_name.xml
  android/app/src/main/res/layout/fragment_notification_log.xml
  android/app/src/main/res/layout/item_address_search.xml
  android/app/src/main/res/layout/item_meeting_catalog.xml
  android/app/src/main/res/layout/item_setting.xml
  android/app/src/main/res/layout/layout_navigate_to_eta.xml
  android/app/src/main/res/layout/toolbar_address_search.xml
  android/app/src/main/res/layout/toolbar_back.xml
  android/app/src/main/res/layout/toolbar_eta_dashboard.xml
  android/app/src/main/res/layout/toolbar_intro.xml
  android/app/src/main/res/layout/toolbar_notification_log.xml
  android/app/src/main/res/layout/toolbar_setting.xml
Labels: AN, REFACTOR

#837 docs: 백엔드 리드미 추가
  README.md
  android/README.md
  backend/README.md
Labels: BE, DOCS

#846 release: 안드로이드 1.2.1 배포
  README.md
  android/README.md
  android/app/build.gradle.kts
  android/app/src/main/java/com/mulberry/ody/presentation/common/CommonBindingAdapter.kt
  android/app/src/main/java/com/mulberry/ody/presentation/common/listener/SingleClickListener.kt
  android/app/src/main/java/com/mulberry/ody/presentation/room/etadashboard/EtaDashboardBindingAdapter.kt
  android/app/src/main/java/com/mulberry/ody/presentation/room/etadashboard/EtaDashboardGuideFirstFragment.kt
  android/app/src/main/java/com/mulberry/ody/presentation/room/etadashboard/EtaDashboardGuideSecondFragment.kt
  android/app/src/main/java/com/mulberry/ody/presentation/setting/withdrawal/WithDrawalDialog.kt
  android/app/src/main/res/layout-sw1080dp/activity_login.xml
  android/app/src/main/res/layout-sw720dp/activity_login.xml
  android/app/src/main/res/layout/activity_invite_code.xml
  android/app/src/main/res/layout/activity_login.xml
  android/app/src/main/res/layout/activity_meeting_creation.xml
  android/app/src/main/res/layout/activity_meeting_join.xml
  android/app/src/main/res/layout/activity_meetings.xml
  android/app/src/main/res/layout/dialog_exit_meeting_room.xml
  android/app/src/main/res/layout/fragment_address_search.xml
  android/app/src/main/res/layout/fragment_meeting_destination.xml
  android/app/src/main/res/layout/fragment_meeting_name.xml
  android/app/src/main/res/layout/fragment_notification_log.xml
  android/app/src/main/res/layout/item_address_search.xml
  android/app/src/main/res/layout/item_meeting_catalog.xml
  android/app/src/main/res/layout/item_setting.xml
  android/app/src/main/res/layout/layout_navigate_to_eta.xml
  android/app/src/main/res/layout/toolbar_address_search.xml
  android/app/src/main/res/layout/toolbar_back.xml
  android/app/src/main/res/layout/toolbar_eta_dashboard.xml
  android/app/src/main/res/layout/toolbar_intro.xml
  android/app/src/main/res/layout/toolbar_notification_log.xml
  android/app/src/main/res/layout/toolbar_setting.xml
  backend/README.md
Labels: AN, RELEASE

#843 feat: 초대 코드 복사하기 방식 변경
  android/app/src/main/java/com/mulberry/ody/presentation/room/MeetingRoomViewModel.kt
  android/app/src/main/java/com/mulberry/ody/presentation/room/log/NotificationLogFragment.kt
  android/app/src/main/java/com/mulberry/ody/presentation/room/log/model/InviteCodeCopyInfo.kt
  android/app/src/main/java/com/mulberry/ody/presentation/room/log/model/MeetingDetailUiModel.kt
  android/app/src/main/res/values/strings.xml
Labels: AN, FEATURE

#848 fix: cd 스크립트 local.properties 제대로 들어가지 않는 문제 수정
  .github/workflows/android-cd-dev.yml
Labels: AN, INFRA

#844 feat: 알림 타입별 on/off 기능 구현
  android/app/src/main/java/com/mulberry/ody/data/local/db/OdyDatastore.kt
  android/app/src/main/java/com/mulberry/ody/di/AppModule.kt
  android/app/src/main/java/com/mulberry/ody/presentation/common/binding/BindingActivity.kt
  android/app/src/main/java/com/mulberry/ody/presentation/notification/FCMNotification.kt
  android/app/src/main/java/com/mulberry/ody/presentation/setting/SettingActivity.kt
  android/app/src/main/java/com/mulberry/ody/presentation/setting/adapter/SettingViewHolder.kt
  android/app/src/main/java/com/mulberry/ody/presentation/setting/adapter/SettingsAdapter.kt
  android/app/src/main/java/com/mulberry/ody/presentation/setting/adapter/SettingsViewHolder.kt
  android/app/src/main/java/com/mulberry/ody/presentation/setting/listener/SettingListener.kt
  android/app/src/main/java/com/mulberry/ody/presentation/setting/model/SettingItemType.kt
  android/app/src/main/java/com/mulberry/ody/presentation/setting/model/SettingUiModel.kt
  android/app/src/main/res/drawable/ic_notification.xml
  android/app/src/main/res/layout/item_setting.xml
  android/app/src/main/res/layout/item_setting_divider.xml
  android/app/src/main/res/layout/item_setting_header.xml
  android/app/src/main/res/values-night/colors.xml
  android/app/src/main/res/values/colors.xml
  android/app/src/main/res/values/strings.xml
Labels: AN, FEATURE

#850 refactor: Room Entity 마이그레이션 코드 리팩터링
  android/app/src/main/java/com/mulberry/ody/data/local/db/OdyDatabase.kt
  android/app/src/main/java/com/mulberry/ody/data/local/entity/eta/OldMateEtaListTypeConverter.kt
  android/app/src/main/java/com/mulberry/ody/data/local/entity/eta/migration/EtaType.kt
  android/app/src/main/java/com/mulberry/ody/data/local/entity/eta/migration/OdyDatabaseMigration.kt
  android/app/src/main/java/com/mulberry/ody/data/local/entity/eta/migration/OldMateEta.kt
  android/app/src/main/java/com/mulberry/ody/data/local/entity/eta/migration/OldMateEtaListTypeConverter.kt
  android/app/src/main/java/com/mulberry/ody/domain/model/EtaType2.kt
  android/app/src/main/java/com/mulberry/ody/domain/model/MateEta2.kt
Labels: AN, REFACTOR

#849 design: 로그 화면의 문자열 수정
  android/app/src/main/res/values/strings.xml
Labels: AN, DESIGN

#856 release: 안드로이드 1.2.2 배포
  .github/workflows/android-cd-dev.yml
  android/app/build.gradle.kts
  android/app/src/main/java/com/mulberry/ody/data/local/db/OdyDatabase.kt
  android/app/src/main/java/com/mulberry/ody/data/local/db/OdyDatastore.kt
  android/app/src/main/java/com/mulberry/ody/data/local/entity/eta/OldMateEtaListTypeConverter.kt
  android/app/src/main/java/com/mulberry/ody/data/local/entity/eta/migration/EtaType.kt
  android/app/src/main/java/com/mulberry/ody/data/local/entity/eta/migration/OdyDatabaseMigration.kt
  android/app/src/main/java/com/mulberry/ody/data/local/entity/eta/migration/OldMateEta.kt
  android/app/src/main/java/com/mulberry/ody/data/local/entity/eta/migration/OldMateEtaListTypeConverter.kt
  android/app/src/main/java/com/mulberry/ody/di/AppModule.kt
  android/app/src/main/java/com/mulberry/ody/domain/model/EtaType2.kt
  android/app/src/main/java/com/mulberry/ody/domain/model/LogType.kt
  android/app/src/main/java/com/mulberry/ody/domain/model/MateEta2.kt
  android/app/src/main/java/com/mulberry/ody/presentation/common/binding/BindingActivity.kt
  android/app/src/main/java/com/mulberry/ody/presentation/notification/FCMNotification.kt
  android/app/src/main/java/com/mulberry/ody/presentation/room/MeetingRoomViewModel.kt
  android/app/src/main/java/com/mulberry/ody/presentation/room/log/NotificationLogFragment.kt
  android/app/src/main/java/com/mulberry/ody/presentation/room/log/listener/InviteCodeCopyListener.kt
  android/app/src/main/java/com/mulberry/ody/presentation/room/log/model/InviteCodeCopyInfo.kt
  android/app/src/main/java/com/mulberry/ody/presentation/room/log/model/MeetingDetailUiModel.kt
  android/app/src/main/java/com/mulberry/ody/presentation/setting/SettingActivity.kt
  android/app/src/main/java/com/mulberry/ody/presentation/setting/adapter/SettingViewHolder.kt
  android/app/src/main/java/com/mulberry/ody/presentation/setting/adapter/SettingsAdapter.kt
  android/app/src/main/java/com/mulberry/ody/presentation/setting/adapter/SettingsViewHolder.kt
  android/app/src/main/java/com/mulberry/ody/presentation/setting/listener/SettingListener.kt
  android/app/src/main/java/com/mulberry/ody/presentation/setting/model/SettingItemType.kt
  android/app/src/main/java/com/mulberry/ody/presentation/setting/model/SettingUiModel.kt
  android/app/src/main/res/drawable/ic_notification.xml
  android/app/src/main/res/layout/item_setting.xml
  android/app/src/main/res/layout/item_setting_divider.xml
  android/app/src/main/res/layout/item_setting_header.xml
  android/app/src/main/res/values-night/colors.xml
  android/app/src/main/res/values/colors.xml
  android/app/src/main/res/values/strings.xml
Labels: AN, RELEASE

#859 release: 안드로이드 1.2.2 cd 테스트 배포
  android/app/build.gradle.kts
Labels: AN, TEST, RELEASE

#863 fix: 안드로이드 cd 배포 시 개인정보 페이지 열리지 않는 문제 수정
  .github/workflows/android-cd-dev.yml
Labels: AN, BUG, INFRA

#865 fix: 안드로이드 cd 배포 시 개인정보 페이지 열리지 않는 문제 수정
  .github/workflows/android-cd-dev.yml
Labels: AN, BUG, INFRA

#866 release: 안드로이드 1.2.2 cd 테스트 배포
  android/app/build.gradle.kts
Labels: AN, INFRA

#867 release: 안드로이드 1.2.2 cd 테스트 배포
  android/app/build.gradle.kts
Labels: AN, RELEASE

#868 fix: 안드로이드 cd 배포 시 개인정보 페이지 열리지 않는 문제 수정
  .github/workflows/android-cd-dev.yml
Labels: AN, BUG, INFRA

#869 release: 안드로이드 1.2.2 cd 테스트 배포
  android/app/build.gradle.kts
Labels: AN, RELEASE

#871 fix: 안드로이드 cd 배포 시 개인정보 페이지 열리지 않는 문제 수정
  .github/workflows/android-cd-dev.yml
Labels: AN, BUG, INFRA

#872 release: 안드로이드 1.2.2 cd 테스트 배포
  android/app/build.gradle.kts
Labels: AN, TEST, RELEASE
