Repository woowacourse-teams/2024-ody, pull requests merged in 2024-08, with the labels that each got.

#189 refactor: 2차 스프린트 구현 사항 리팩터링
  android/app/src/main/java/com/woowacourse/ody/presentation/address/AddressSearchDialog.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/creation/MeetingCreationViewModel.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/creation/date/MeetingDateFragment.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/invitecode/InviteCodeActivity.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/invitecode/InviteCodeViewModel.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/join/complete/JoinCompleteActivity.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/room/MeetingRoomActivity.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/splash/SplashActivity.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/splash/SplashNavigateAction.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/splash/SplashViewModel.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/splash/SplashViewModelFactory.kt
  android/app/src/main/res/layout/activity_invite_code.xml
  android/app/src/main/res/layout/fragment_join_nickname.xml
  android/app/src/main/res/layout/fragment_meeting_name.xml
Labels: AN, REFACTOR

#219 design: 폰트, 컬러 xml 지정
  android/app/src/main/res/drawable/rectangle_edit_text.xml
  android/app/src/main/res/drawable/rectangle_gray_radius_20.xml
  android/app/src/main/res/drawable/rectangle_purple_radius_20.xml
  android/app/src/main/res/drawable/selector_bottom_button.xml
  android/app/src/main/res/layout/activity_intro.xml
  android/app/src/main/res/layout/activity_invite_code.xml
  android/app/src/main/res/layout/activity_join_complete.xml
  android/app/src/main/res/layout/activity_meeting_creation.xml
  android/app/src/main/res/layout/activity_meeting_join.xml
  android/app/src/main/res/layout/activity_splash.xml
  android/app/src/main/res/layout/bottom_sheet_code_copy.xml
  android/app/src/main/res/layout/fragment_destination.xml
  android/app/src/main/res/layout/fragment_join_departure.xml
  android/app/src/main/res/layout/fragment_join_nickname.xml
  android/app/src/main/res/layout/fragment_meeting_date.xml
  android/app/src/main/res/layout/fragment_meeting_destination.xml
  android/app/src/main/res/layout/fragment_meeting_name.xml
  android/app/src/main/res/layout/fragment_meeting_time.xml
  android/app/src/main/res/layout/item_invite_code_log.xml
  android/app/src/main/res/layout/item_notification_log.xml
  android/app/src/main/res/values/colors.xml
  android/app/src/main/res/values/styles.xml
Labels: AN, DESIGN

#196 refactor: 2차 스프린트 리팩터링
  android/app/src/main/java/com/woowacourse/ody/OdyApplication.kt
  android/app/src/main/java/com/woowacourse/ody/data/remote/core/repository/DefaultNotificationLogRepository.kt
  android/app/src/main/java/com/woowacourse/ody/data/remote/thirdparty/fcm/service/FCMService.kt
  android/app/src/main/java/com/woowacourse/ody/domain/repository/ody/NotificationLogRepository.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/intro/IntroActivity.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/notification/NotificationHelper.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/room/CopyInviteCodeListener.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/room/MeetingRoomActivity.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/room/MeetingRoomViewModel.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/room/adapter/InviteCodeViewHolder.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/room/adapter/NotificationLogsAdapter.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/room/listener/CopyInviteCodeListener.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/room/listener/ShareListener.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/room/model/NotificationUiModelMapper.kt
  android/app/src/main/res/layout/activity_meeting_room.xml
  android/app/src/main/res/layout/bottom_sheet_code_copy.xml
  android/app/src/main/res/layout/item_invite_code_log.xml
  android/app/src/main/res/layout/toolbar_log.xml
  android/app/src/test/java/com/woowacourse/ody/fake/FakeNotificationLogRepository.kt
Labels: AN, REFACTOR

#181 refactor: 서비스가 DTO 반환하도록 수정
  backend/src/main/java/com/ody/mate/controller/MateController.java
  backend/src/main/java/com/ody/mate/domain/Mate.java
  backend/src/main/java/com/ody/mate/domain/Nickname.java
  backend/src/main/java/com/ody/mate/repository/MateRepository.java
  backend/src/main/java/com/ody/mate/service/MateService.java
  backend/src/main/java/com/ody/meeting/controller/MeetingController.java
  backend/src/main/java/com/ody/meeting/dto/request/MeetingSaveRequest.java
  backend/src/main/java/com/ody/meeting/dto/response/MateResponse.java
  backend/src/main/java/com/ody/meeting/service/MeetingService.java
  backend/src/main/java/com/ody/notification/domain/Notification.java
  backend/src/main/java/com/ody/notification/dto/request/FcmSendRequest.java
  backend/src/main/java/com/ody/notification/dto/response/NotiLogFindResponse.java
  backend/src/main/java/com/ody/notification/service/FcmEventScheduler.java
  backend/src/main/java/com/ody/notification/service/FcmPushSender.java
  backend/src/main/java/com/ody/notification/service/NotificationService.java
  backend/src/test/java/com/ody/notification/service/FcmEventSchedulerTest.java
  backend/src/test/java/com/ody/notification/service/NotificationServiceTest.java
Labels: BE, REFACTOR

#220 refactor: BaseActivity, BaseFragment
  android/app/src/main/java/com/woowacourse/ody/presentation/common/binding/BindingActivity.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/common/binding/BindingFragment.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/creation/MeetingCreationActivity.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/creation/date/MeetingDateFragment.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/creation/destination/MeetingDestinationFragment.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/creation/name/MeetingNameFragment.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/creation/time/MeetingTimeFragment.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/intro/IntroActivity.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/invitecode/InviteCodeActivity.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/join/MeetingJoinActivity.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/join/departure/JoinDepartureFragment.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/join/nickname/JoinNickNameFragment.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/room/MeetingRoomActivity.kt
Labels: AN, REFACTOR

#242 docs: 서비스 소개글 작성
  README.md
Labels: AN, BE, DOCS

#246 docs: 약속 참여 API 문서화
  backend/src/main/java/com/ody/mate/controller/MateController.java
  backend/src/main/java/com/ody/mate/controller/MateControllerSwagger.java
  backend/src/main/java/com/ody/mate/dto/request/MateSaveRequest.java
  backend/src/main/java/com/ody/meeting/dto/response/MateResponse.java
  backend/src/main/java/com/ody/meeting/dto/response/MeetingSaveResponse.java
  backend/src/main/java/com/ody/swagger/annotation/ErrorCode404.java
Labels: BE, DOCS

#245 docs: 약속 단건 조회 API 문서화
  backend/src/main/java/com/ody/meeting/controller/MeetingController.java
  backend/src/main/java/com/ody/meeting/controller/MeetingControllerSwagger.java
  backend/src/main/java/com/ody/meeting/dto/response/MeetingWithMatesResponse.java
  backend/src/main/java/com/ody/meeting/service/MeetingService.java
Labels: BE, DOCS

#249 docs: 약속 개설 API 문서화
  backend/src/main/java/com/ody/meeting/controller/MeetingController.java
  backend/src/main/java/com/ody/meeting/controller/MeetingControllerSwagger.java
  backend/src/main/java/com/ody/meeting/dto/request/MeetingSaveRequestV1.java
  backend/src/main/java/com/ody/meeting/dto/response/MeetingSaveResponseV1.java
Labels: BE, DOCS

#250 refactor : 약속 개설 API 구현
  backend/src/main/java/com/ody/mate/controller/MateControllerSwagger.java
  backend/src/main/java/com/ody/meeting/controller/MeetingController.java
  backend/src/main/java/com/ody/meeting/controller/MeetingControllerSwagger.java
  backend/src/main/java/com/ody/meeting/dto/request/MeetingSaveRequestV1.java
  backend/src/main/java/com/ody/meeting/dto/response/MeetingSaveResponseV1.java
  backend/src/main/java/com/ody/meeting/repository/MeetingRepository.java
  backend/src/main/java/com/ody/meeting/service/MeetingService.java
  backend/src/main/java/com/ody/notification/repository/NotificationRepository.java
  backend/src/main/java/com/ody/route/mapper/OdsayResponseMapper.java
  backend/src/main/java/com/ody/route/service/OdsayRouteClient.java
  backend/src/test/java/com/ody/meeting/controller/MeetingControllerTest.java
  backend/src/test/java/com/ody/meeting/repository/MeetingRepositoryTest.java
  backend/src/test/java/com/ody/meeting/service/MeetingServiceTest.java
Labels: BE, REFACTOR

#252 design: 유저 현황 화면 디자인
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/java/com/woowacourse/ody/presentation/creation/MeetingCreationActivity.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/join/MeetingJoinActivity.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/room/etadashboard/EtaDashboardActivity.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/room/listener/ShareListener.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/room/log/BindingAdapter.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/room/log/NotificationLogActivity.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/room/log/NotificationLogViewModel.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/room/log/NotificationLogViewModelFactory.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/room/log/adapter/InviteCodeViewHolder.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/room/log/adapter/NotificationLogViewHolder.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/room/log/adapter/NotificationLogsAdapter.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/room/log/listener/CopyInviteCodeListener.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/room/log/listener/ShareListener.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/room/log/model/MeetingUiModel.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/room/log/model/MeetingUiModelMapper.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/room/log/model/NotificationLogUiModel.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/room/log/model/NotificationUiModelMapper.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/splash/SplashActivity.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/splash/SplashNavigateAction.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/splash/SplashViewModel.kt
  android/app/src/main/res/drawable/oval.xml
  android/app/src/main/res/drawable/rectangle_tooltip.xml
  android/app/src/main/res/layout/activity_eta_dashboard.xml
  android/app/src/main/res/layout/activity_notification_log.xml
  android/app/src/main/res/layout/bottom_sheet_code_copy.xml
  android/app/src/main/res/layout/item_eta_dashboard.xml
  android/app/src/main/res/layout/item_invite_code_log.xml
  android/app/src/main/res/layout/item_notification_log.xml
  android/app/src/main/res/layout/toolbar_meeting_room.xml
  android/app/src/main/res/values/colors.xml
  android/app/src/main/res/values/strings.xml
Labels: AN, DESIGN

#260 design: 홈 화면 리스트 디자인
  android/app/src/main/res/drawable/ic_arrow_down.xml
  android/app/src/main/res/drawable/ic_arrow_up.xml
  android/app/src/main/res/drawable/ic_ody.xml
  android/app/src/main/res/drawable/rectangle_radius_15_stroke_1_gray_350.xml
  android/app/src/main/res/drawable/rectangle_white_radius_15.xml
  android/app/src/main/res/layout/activity_meeting_list.xml
  android/app/src/main/res/layout/item_meeting.xml
  android/app/src/main/res/layout/layout_navigate_to_meeting_room.xml
  android/app/src/main/res/values/strings.xml
Labels: AN, DESIGN

#261 feat: 유저 현황 화면 api v1 연결
  android/app/src/main/java/com/woowacourse/ody/data/remote/core/entity/meeting/mapper/MatesEtaResponseMapper.kt
  android/app/src/main/java/com/woowacourse/ody/data/remote/core/entity/meeting/mapper/MeetingRequestMapper.kt
  android/app/src/main/java/com/woowacourse/ody/data/remote/core/entity/meeting/mapper/MeetingResponseMapper.kt
  android/app/src/main/java/com/woowacourse/ody/data/remote/core/entity/meeting/request/MatesEtaRequest.kt
  android/app/src/main/java/com/woowacourse/ody/data/remote/core/entity/meeting/response/MateEtaResponse.kt
  android/app/src/main/java/com/woowacourse/ody/data/remote/core/entity/meeting/response/MatesEtaResponse.kt
  android/app/src/main/java/com/woowacourse/ody/data/remote/core/repository/DefaultMeetingRepository.kt
  android/app/src/main/java/com/woowacourse/ody/data/remote/core/service/MeetingService.kt
  android/app/src/main/java/com/woowacourse/ody/domain/model/EtaType.kt
  android/app/src/main/java/com/woowacourse/ody/domain/model/MateEta.kt
  android/app/src/main/java/com/woowacourse/ody/domain/repository/ody/MeetingRepository.kt
Labels: AN, FEATURE

#262 design: 홈 화면 리스트 없는 경우 디자인
  android/app/src/main/res/layout/activity_meeting_list.xml
  android/app/src/main/res/values/strings.xml
  android/app/src/test/java/com/woowacourse/ody/fake/FakeMeetingRepository.kt
Labels: AN, DESIGN

#265 feat: 유저 현황 화면 리스트 어댑터 구현
  android/app/src/main/java/com/woowacourse/ody/presentation/room/etadashboard/EtaDashboardActivity.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/room/etadashboard/EtaDashboardBindingAdapter.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/room/etadashboard/adapter/MateEtaViewHolder.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/room/etadashboard/adapter/MateEtasAdapter.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/room/etadashboard/listener/MissingToolTipListener.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/room/etadashboard/model/EtaDurationMinuteTypeUiModel.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/room/etadashboard/model/EtaTypeUiModel.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/room/etadashboard/model/EtaTypeUiModelMapper.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/room/etadashboard/model/MateEtaUiModel.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/room/etadashboard/model/MateEtaUiModelMapper.kt
  android/app/src/main/res/layout/item_eta_dashboard.xml
  android/app/src/main/res/layout/layout_missing_tooltip.xml
Labels: AN, FEATURE

#270 fix: 시간 데이터 초 제거 후 반환하도록 수정
  backend/src/main/java/com/ody/mate/dto/response/MateSaveResponse.java
  backend/src/main/java/com/ody/meeting/dto/response/MeetingSaveResponse.java
  backend/src/main/java/com/ody/meeting/dto/response/MeetingSaveResponseV1.java
  backend/src/main/java/com/ody/meeting/dto/response/MeetingWithMatesResponse.java
Labels: BE, BUG

#268 refactor: v1/mates 응답값 수정
  android/app/src/main/java/com/woowacourse/ody/data/remote/core/entity/join/response/JoinResponse.kt
  android/app/src/main/java/com/woowacourse/ody/data/remote/core/entity/join/response/JoinResponseMapper.kt
  android/app/src/main/java/com/woowacourse/ody/data/remote/core/entity/meeting/mapper/MeetingResponseMapper.kt
  android/app/src/main/java/com/woowacourse/ody/data/remote/core/repository/DefaultJoinRepository.kt
  android/app/src/main/java/com/woowacourse/ody/domain/model/ReserveInfo.kt
  android/app/src/main/java/com/woowacourse/ody/domain/repository/ody/JoinRepository.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/join/MeetingJoinViewModel.kt
Labels: AN, REFACTOR

#271 feat: 플로팅 버튼 화면 이동 구현
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/java/com/woowacourse/ody/presentation/FloatingButtonActivity.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/FloatingButtonListener.kt
  android/app/src/main/res/layout/activity_meeting_list.xml
Labels: AN, FEATURE

#272 feat: 홈 화면 리스트 어댑터 구현
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/java/com/woowacourse/ody/presentation/meetinglist/MeetingsActivity.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/meetinglist/MeetingsBindingAdapter.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/meetinglist/MeetingsViewModel.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/meetinglist/adapter/MeetingViewHolder.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/meetinglist/adapter/MeetingsAdapter.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/meetinglist/model/MeetingUiModel.kt
  android/app/src/main/res/layout/activity_meeting_list.xml
  android/app/src/main/res/layout/item_meeting.xml
  android/app/src/main/res/values/strings.xml
  android/app/src/test/java/com/woowacourse/ody/fake/FakeMeetingRepository.kt
Labels: AN, FEATURE

#256 refactor: 약속 단건 조회 API 구현
  backend/src/main/java/com/ody/mate/service/MateService.java
  backend/src/main/java/com/ody/meeting/controller/MeetingControllerSwagger.java
  backend/src/main/java/com/ody/meeting/service/MeetingService.java
  backend/src/test/java/com/ody/mate/service/MateServiceTest.java
  backend/src/test/java/com/ody/meeting/service/MeetingServiceTest.java
Labels: BE, REFACTOR

#276 feat: 위치 권한 받아오는 기능 구현
  android/app/build.gradle.kts
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/java/com/woowacourse/ody/presentation/common/binding/BindingActivity.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/intro/IntroActivity.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/meetinglist/MeetingsBindingAdapter.kt
  android/app/src/main/res/layout/item_meeting.xml
  android/app/src/main/res/values/strings.xml
  android/app/src/test/java/com/woowacourse/ody/fake/FakeMeetingRepository.kt
  android/gradle/libs.versions.toml
Labels: AN, FEATURE

#279 feat: 약속 목록 조회 api 연결
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/java/com/woowacourse/ody/data/remote/core/entity/meeting/mapper/MeetingCatalogMapper.kt
  android/app/src/main/java/com/woowacourse/ody/data/remote/core/entity/meeting/response/MeetingCatalogResponse.kt
  android/app/src/main/java/com/woowacourse/ody/data/remote/core/entity/meeting/response/MeetingCatalogsResponse.kt
  android/app/src/main/java/com/woowacourse/ody/data/remote/core/repository/DefaultMeetingRepository.kt
  android/app/src/main/java/com/woowacourse/ody/data/remote/core/service/MeetingService.kt
  android/app/src/main/java/com/woowacourse/ody/domain/model/MeetingCatalog.kt
  android/app/src/main/java/com/woowacourse/ody/domain/repository/ody/MeetingRepository.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/FloatingButtonActivity.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/FloatingButtonListener.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/creation/MeetingCreationActivity.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/creation/MeetingCreationNavigateAction.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/creation/MeetingCreationViewModel.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/home/HomeActivity.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/home/HomeBindingAdapter.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/home/HomeViewModel.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/home/HomeViewModelFactory.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/home/adapter/MeetingCatalogViewHolder.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/home/adapter/MeetingCatalogsAdapter.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/home/listener/HomeListener.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/home/listener/ToggleFoldListener.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/home/model/MeetingCatalogUiModel.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/home/model/MeetingCatalogUiModelMapper.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/intro/IntroNavigateAction.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/intro/IntroViewModel.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/intro/listener/IntroListener.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/meetinglist/MeetingsActivity.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/meetinglist/MeetingsViewModel.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/meetinglist/adapter/MeetingViewHolder.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/meetinglist/adapter/MeetingsAdapter.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/meetinglist/model/MeetingUiModel.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/splash/SplashActivity.kt
  android/app/src/main/res/layout/activity_home.xml
  android/app/src/main/res/layout/activity_intro.xml
  android/app/src/main/res/layout/item_meeting_catalog.xml
  android/app/src/main/res/layout/layout_navigate_to_meeting_room.xml
  android/app/src/main/res/values/strings.xml
  android/app/src/test/java/com/woowacourse/ody/fake/FakeMeetingRepository.kt
Labels: AN, FEATURE

#281 feat: 단일 약속 api 연결
  android/app/src/main/java/com/woowacourse/ody/data/remote/core/repository/DefaultMeetingRepository.kt
  android/app/src/main/java/com/woowacourse/ody/data/remote/core/service/MeetingService.kt
  android/app/src/main/java/com/woowacourse/ody/domain/repository/ody/MeetingRepository.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/home/HomeActivity.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/home/model/MeetingCatalogUiModel.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/home/model/MeetingCatalogUiModelMapper.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/room/log/NotificationLogViewModel.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/room/log/NotificationLogViewModelFactory.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/splash/SplashActivity.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/splash/SplashViewModel.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/splash/SplashViewModelFactory.kt
  android/app/src/main/res/layout/activity_home.xml
  android/app/src/main/res/layout/item_meeting_catalog.xml
  android/app/src/main/res/layout/layout_navigate_to_meeting_room.xml
  android/app/src/main/res/values/strings.xml
  android/app/src/test/java/com/woowacourse/ody/fake/FakeMeetingRepository.kt
Labels: AN, FEATURE

#282 feat: gps 위경도 받아오는 기능 구현
  android/app/src/main/java/com/woowacourse/ody/data/local/service/EtaDashBoardWorker.kt
  android/app/src/main/java/com/woowacourse/ody/data/remote/core/repository/DefaultMeetingRepository.kt
Labels: AN, FEATURE

#277 feat: 약속 참여자 상태 목록 조회 API 기능 구현
  backend/src/main/java/com/ody/eta/domain/Eta.java
  backend/src/main/java/com/ody/eta/domain/EtaStatus.java
  backend/src/main/java/com/ody/eta/dto/request/MateEtaRequest.java
  backend/src/main/java/com/ody/eta/dto/response/MateEtaResponse.java
  backend/src/main/java/com/ody/eta/dto/response/MateEtaResponses.java
  backend/src/main/java/com/ody/eta/repository/EtaRepository.java
  backend/src/main/java/com/ody/eta/service/EtaService.java
  backend/src/main/java/com/ody/mate/controller/MateController.java
  backend/src/main/java/com/ody/mate/controller/MateControllerSwagger.java
  backend/src/main/java/com/ody/mate/domain/Mate.java
  backend/src/main/java/com/ody/mate/dto/request/MateSaveRequest.java
  backend/src/main/java/com/ody/mate/dto/response/MateEtaResponse.java
  backend/src/main/java/com/ody/mate/repository/MateRepository.java
  backend/src/main/java/com/ody/mate/service/MateService.java
  backend/src/main/java/com/ody/meeting/controller/MeetingController.java
  backend/src/main/java/com/ody/meeting/controller/MeetingControllerSwagger.java
  backend/src/main/java/com/ody/meeting/domain/Meeting.java
  backend/src/main/java/com/ody/meeting/repository/MeetingRepository.java
  backend/src/main/java/com/ody/meeting/service/MeetingService.java
  backend/src/main/java/com/ody/notification/service/NotificationService.java
  backend/src/main/java/com/ody/route/domain/DepartureTime.java
  backend/src/main/java/com/ody/route/service/RouteService.java
  backend/src/main/java/com/ody/util/DistanceCalculator.java
  backend/src/test/java/com/ody/common/BaseServiceTest.java
  backend/src/test/java/com/ody/common/DatabaseCleaner.java
  backend/src/test/java/com/ody/common/Fixture.java
  backend/src/test/java/com/ody/eta/domain/EtaStatusTest.java
  backend/src/test/java/com/ody/eta/domain/EtaTest.java
  backend/src/test/java/com/ody/eta/repository/EtaRepositoryTest.java
  backend/src/test/java/com/ody/eta/service/EtaServiceTest.java
  backend/src/test/java/com/ody/mate/repository/MateRepositoryTest.java
  backend/src/test/java/com/ody/mate/service/MateServiceTest.java
  backend/src/test/java/com/ody/meeting/controller/MeetingControllerTest.java
  backend/src/test/java/com/ody/meeting/repository/MeetingRepositoryTest.java
  backend/src/test/java/com/ody/meeting/service/MeetingServiceTest.java
  backend/src/test/java/com/ody/notification/repository/NotificationRepositoryTest.java
  backend/src/test/java/com/ody/notification/service/FcmEventSchedulerTest.java
  backend/src/test/java/com/ody/notification/service/NotificationServiceTest.java
  backend/src/test/java/com/ody/util/DistanceCalculatorTest.java
Labels: BE, FEATURE

#284 refactor: 유저 위치 현황 조회 시 자신의 닉네임 response로 받도록 수정
  android/app/src/main/java/com/woowacourse/ody/data/local/repository/DefaultMatesEtaRepository.kt
  android/app/src/main/java/com/woowacourse/ody/data/local/service/EtaDashBoardWorker.kt
  android/app/src/main/java/com/woowacourse/ody/data/local/service/MateEtaInfoResponse.kt
  android/app/src/main/java/com/woowacourse/ody/data/local/service/MateEtaResponse.kt
  android/app/src/main/java/com/woowacourse/ody/data/remote/core/entity/meeting/mapper/MatesEtaResponseMapper.kt
  android/app/src/main/java/com/woowacourse/ody/data/remote/core/entity/meeting/response/MatesEtaResponse.kt
  android/app/src/main/java/com/woowacourse/ody/data/remote/core/repository/DefaultMeetingRepository.kt
  android/app/src/main/java/com/woowacourse/ody/domain/model/MateEtaInfo.kt
  android/app/src/main/java/com/woowacourse/ody/domain/repository/ody/MatesEtaRepository.kt
  android/app/src/main/java/com/woowacourse/ody/domain/repository/ody/MeetingRepository.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/room/etadashboard/EtaDashboardActivity.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/room/etadashboard/EtaDashboardViewModel.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/room/etadashboard/model/MateEtaUiModelMapper.kt
  android/app/src/test/java/com/woowacourse/ody/fake/FakeMeetingRepository.kt
Labels: AN, REFACTOR

#287 fix: update 미반영 오류 문제 해결
  backend/src/main/java/com/ody/eta/service/EtaService.java
Labels: BE, BUG

#291 refactor: HomeActivity -> MeetingsActivity로 이름 변경
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/java/com/woowacourse/ody/presentation/creation/MeetingCreationActivity.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/creation/MeetingCreationNavigateAction.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/creation/MeetingCreationViewModel.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/home/adapter/MeetingCatalogViewHolder.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/meetings/MeetingsActivity.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/meetings/MeetingsBindingAdapter.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/meetings/MeetingsViewModel.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/meetings/MeetingsViewModelFactory.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/meetings/adapter/MeetingsAdapter.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/meetings/adapter/MeetingsViewHolder.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/meetings/listener/MeetingsListener.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/meetings/listener/ToggleFoldListener.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/meetings/model/MeetingUiModel.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/meetings/model/MeetingUiModelMapper.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/room/log/NotificationLogViewModel.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/room/log/model/MeetingDetailUiModel.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/room/log/model/MeetingDetailUiModelMapper.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/splash/SplashActivity.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/splash/SplashNavigateAction.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/splash/SplashViewModel.kt
  android/app/src/main/res/layout/activity_meetings.xml
  android/app/src/main/res/layout/item_meeting_catalog.xml
  android/app/src/main/res/layout/layout_navigate_to_meeting_room.xml
  android/app/src/main/res/values/strings.xml
Labels: AN, REFACTOR

#292 fix: 유저 현황표 폴링 방식 수정
  android/app/src/main/java/com/woowacourse/ody/data/local/repository/DefaultMatesEtaRepository.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/join/MeetingJoinViewModel.kt
Labels: AN, BUG

#293 refactor: 데모데이 이슈 문제 해결
  backend/src/main/java/com/ody/eta/domain/Eta.java
  backend/src/main/java/com/ody/eta/domain/EtaStatus.java
  backend/src/main/java/com/ody/eta/dto/response/MateEtaResponse.java
  backend/src/main/java/com/ody/eta/service/EtaService.java
  backend/src/main/java/com/ody/meeting/controller/MeetingController.java
  backend/src/main/java/com/ody/meeting/service/MeetingService.java
Labels: BE, REFACTOR

#304 feat: 현황 화면 툴바 리스너 등록
  android/app/src/main/java/com/woowacourse/ody/presentation/room/etadashboard/EtaDashboardActivity.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/room/log/NotificationLogActivity.kt
  android/app/src/main/res/layout/activity_eta_dashboard.xml
Labels: AN, FEATURE

#305 fix: 모임 참여 화면 flow 수정
  android/app/src/main/java/com/woowacourse/ody/presentation/invitecode/InviteCodeActivity.kt
Labels: AN, FEATURE

#306 fix: 리스트 깜빡임 현상 해결
  android/app/src/main/java/com/woowacourse/ody/presentation/room/etadashboard/EtaDashboardActivity.kt
  android/app/src/main/res/layout/activity_eta_dashboard.xml
Labels: AN, BUG

#301 fix: 개설하기에서 뒤로가기 버튼 누르면 현 화면 없애기 및 오디 캐릭터 추가
  android/app/src/main/java/com/woowacourse/ody/presentation/creation/MeetingCreationActivity.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/meetings/MeetingsActivity.kt
  android/app/src/main/res/drawable/ic_happy_ody.xml
  android/app/src/main/res/drawable/ic_sad_ody.xml
  android/app/src/main/res/drawable/ic_together_ody.xml
  android/app/src/main/res/layout/activity_join_complete.xml
  android/app/src/main/res/layout/activity_meeting_completion.xml
  android/app/src/main/res/layout/activity_meetings.xml
Labels: AN, BUG

#308 test: 2차 스프린트 구현 사항 테스트
  android/app/build.gradle.kts
  android/app/src/androidTest/java/com/woowacourse/ody/.gitkeep
  android/app/src/androidTest/java/com/woowacourse/ody/presentation/creation/MeetingCreationActivityTest.kt
  android/app/src/androidTest/java/com/woowacourse/ody/presentation/invitecode/InviteCodeActivityTest.kt
  android/app/src/androidTest/java/com/woowacourse/ody/presentation/join/MeetingJoinActivityTest.kt
  android/app/src/main/res/layout/fragment_destination.xml
  android/app/src/test/java/com/woowacourse/ody/ExampleUnitTest.kt
  android/app/src/test/java/com/woowacourse/ody/domain/validator/AddressValidatorTest.kt
  android/gradle/libs.versions.toml
Labels: AN, TEST

#309 feat: 로그에서 30분전이면 오디 버튼이 아예 안뜨게 구현
  android/app/src/main/java/com/woowacourse/ody/presentation/room/log/NotificationLogActivity.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/room/log/model/MeetingDetailUiModel.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/room/log/model/MeetingDetailUiModelMapper.kt
  android/app/src/main/res/layout/activity_notification_log.xml
Labels: AN, FEATURE

#314 fix: 약속 로그 관련 수정 사항
  android/app/src/main/res/layout/activity_notification_log.xml
Labels: AN, REFACTOR

#302 feat: 내 약속 목록 조회 시 현재 이후 약속만 조회
  backend/src/main/java/com/ody/meeting/domain/Meeting.java
  backend/src/main/java/com/ody/meeting/service/MeetingService.java
  backend/src/test/java/com/ody/meeting/service/MeetingServiceTest.java
Labels: BE, FEATURE

#315 fix: 약속 리스트 관련 수정 사항
  android/app/src/main/java/com/woowacourse/ody/presentation/meetings/MeetingsActivity.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/meetings/MeetingsBindingAdapter.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/meetings/MeetingsNavigateAction.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/meetings/MeetingsViewModel.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/meetings/adapter/MeetingsAdapter.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/meetings/adapter/MeetingsViewHolder.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/meetings/listener/MeetingsItemListener.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/meetings/listener/MeetingsListener.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/meetings/listener/ToggleFoldListener.kt
  android/app/src/main/res/layout/activity_meetings.xml
  android/app/src/main/res/layout/item_meeting_catalog.xml
  android/app/src/main/res/layout/layout_navigate_to_eta.xml
  android/app/src/main/res/values/strings.xml
Labels: AN, REFACTOR

#317 fix: 행방불명상태의 소요시간 응답 오류 해결
  backend/src/main/java/com/ody/eta/domain/Eta.java
  backend/src/main/java/com/ody/eta/dto/response/MateEtaResponse.java
  backend/src/test/java/com/ody/eta/domain/EtaTest.java
Labels: BE, BUG

#320 fix: 행방불명 오류 해결
  backend/src/main/java/com/ody/eta/domain/EtaStatus.java
  backend/src/main/java/com/ody/eta/dto/response/MateEtaResponse.java
  backend/src/test/java/com/ody/eta/domain/EtaStatusTest.java
Labels: BE, BUG

#323 fix: 해결되지 않은 행방불명 오류 해결
  backend/src/main/java/com/ody/eta/dto/response/MateEtaResponse.java
  backend/src/main/java/com/ody/eta/service/EtaService.java
Labels: BE, BUG

#321 fix: compress 메서드 수정, gps 온오프 확인
  android/app/src/main/java/com/woowacourse/ody/data/local/service/EtaDashBoardWorker.kt
  android/app/src/main/java/com/woowacourse/ody/data/remote/core/entity/join/request/JoinRequestMapper.kt
  android/app/src/main/java/com/woowacourse/ody/data/remote/core/entity/meeting/mapper/MeetingRequestMapper.kt
  android/app/src/main/java/com/woowacourse/ody/data/remote/core/repository/DefaultMeetingRepository.kt
Labels: AN, BUG

#325 fix: 도착한 상태인 사람의 소요시간이 -1로 반환되고 있는 문제 해결
  backend/src/main/java/com/ody/eta/domain/EtaStatus.java
Labels: BE, BUG

#329 fix: 미팅 목록 아이템 접기/펴기 버튼 터치영역 늘리기
  android/app/src/main/res/layout/item_meeting_catalog.xml
Labels: AN, BUG

#327 fix: 로그화면 오디 버튼 사라지는 타이밍 변경
  android/app/src/main/java/com/woowacourse/ody/presentation/room/log/model/MeetingDetailUiModelMapper.kt
Labels: AN, BUG

#332 fix: 로그 화면에서 값이 없는 화면이 나타나는 버그
  android/app/src/main/java/com/woowacourse/ody/presentation/room/log/NotificationLogViewModel.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/room/log/model/MeetingDetailUiModel.kt
Labels: AN, BUG

#334 design: 초대 코드 item과 모임 정보 칸과의 간격을 늘림
  android/app/src/main/res/layout/item_invite_code_log.xml
Labels: AN, DESIGN

#338 feat: EtaDashboardViewModelTest 구현
  android/app/build.gradle.kts
  android/app/src/main/java/com/woowacourse/ody/presentation/room/etadashboard/EtaDashboardViewModel.kt
  android/app/src/test/java/com/woowacourse/ody/fake/FakeMatesEtaRepository.kt
  android/app/src/test/java/com/woowacourse/ody/util/CoroutinesTestExtension.kt
  android/app/src/test/java/com/woowacourse/ody/util/InstantTaskExecutorExtension.kt
  android/app/src/test/java/com/woowacourse/ody/util/TestUtil.kt
  android/app/src/test/java/com/woowacourse/ody/viewmodel/EtaDashBoardViewModelTest.kt
  android/gradle/libs.versions.toml
Labels: AN, FEATURE

#341 fix: 로그 화면 닉네임들 길어지면 안보이는 버그 수정
  android/app/src/main/res/layout/activity_notification_log.xml
  android/app/src/main/res/layout/fragment_meeting_date.xml
  android/app/src/main/res/layout/item_notification_log.xml
Labels: AN, BUG

#340 refactor: response. requset api 순서에 맞게 맞추기, 패키지 위치 수정
  android/app/src/main/java/com/woowacourse/ody/data/local/entity/eta/MatesEtaInfoResponse.kt
  android/app/src/main/java/com/woowacourse/ody/data/local/repository/DefaultMatesEtaRepository.kt
  android/app/src/main/java/com/woowacourse/ody/data/local/service/EtaDashboardWorker.kt
  android/app/src/main/java/com/woowacourse/ody/data/remote/core/entity/join/mapper/JoinRequestMapper.kt
  android/app/src/main/java/com/woowacourse/ody/data/remote/core/entity/join/mapper/JoinResponseMapper.kt
  android/app/src/main/java/com/woowacourse/ody/data/remote/core/entity/join/response/MateResponse.kt
  android/app/src/main/java/com/woowacourse/ody/data/remote/core/entity/meeting/mapper/MatesEtaResponseMapper.kt
  android/app/src/main/java/com/woowacourse/ody/data/remote/core/entity/meeting/request/MatesEtaRequest.kt
  android/app/src/main/java/com/woowacourse/ody/data/remote/core/entity/meeting/request/MeetingRequest.kt
  android/app/src/main/java/com/woowacourse/ody/data/remote/core/entity/meeting/response/MatesEtaResponse.kt
  android/app/src/main/java/com/woowacourse/ody/data/remote/core/entity/meeting/response/MeetingCatalogResponse.kt
  android/app/src/main/java/com/woowacourse/ody/data/remote/core/entity/meeting/response/MeetingResponse.kt
  android/app/src/main/java/com/woowacourse/ody/data/remote/core/entity/notification/mapper/NotificationLogsResponseMapper.kt
  android/app/src/main/java/com/woowacourse/ody/data/remote/core/repository/DefaultJoinRepository.kt
  android/app/src/main/java/com/woowacourse/ody/data/remote/core/repository/DefaultNotificationLogRepository.kt
  android/app/src/main/java/com/woowacourse/ody/domain/model/MeetingCatalog.kt
Labels: AN, REFACTOR

#254 docs: test coverage report 스크립트 추가
  .github/workflows/backend-cd-dev.yml
  .github/workflows/backend-ci-dev.yml
  backend/build.gradle
Labels: BE, INFRA

#303 refactor : 나노초 제거를 직렬화 도구로 수행
  backend/src/main/java/com/ody/common/mapper/TimeSerializer.java
  backend/src/main/java/com/ody/eta/dto/response/MateEtaResponses.java
  backend/src/main/java/com/ody/eta/service/EtaService.java
  backend/src/main/java/com/ody/mate/controller/MateControllerSwagger.java
  backend/src/main/java/com/ody/mate/dto/response/MateSaveResponse.java
  backend/src/main/java/com/ody/meeting/controller/MeetingControllerSwagger.java
  backend/src/main/java/com/ody/meeting/dto/response/MeetingFindByMemberResponse.java
  backend/src/main/java/com/ody/meeting/dto/response/MeetingSaveResponse.java
  backend/src/main/java/com/ody/meeting/dto/response/MeetingSaveResponseV1.java
  backend/src/main/java/com/ody/meeting/dto/response/MeetingWithMatesResponse.java
  backend/src/main/java/com/ody/meeting/repository/MeetingRepository.java
  backend/src/main/java/com/ody/route/service/RouteService.java
  backend/src/test/java/com/ody/common/mapper/TimeSerializerTest.java
  backend/src/test/java/com/ody/mate/controller/MateControllerTest.java
  backend/src/test/java/com/ody/meeting/controller/MeetingControllerTest.java
Labels: BE, REFACTOR

#350 config: 앱 출시를 위한 수정
  android/app/build.gradle.kts
  android/app/src/main/AndroidManifest.xml
Labels: AN, INFRA

#353 refactor: 버전 카탈로그에 맞게 수정
  android/app/build.gradle.kts
  android/build.gradle.kts
  android/gradle/libs.versions.toml
Labels: AN, REFACTOR

#347 refactor: 권한 체크, 권한 요청 분리
  android/app/src/main/java/com/woowacourse/ody/OdyApplication.kt
  android/app/src/main/java/com/woowacourse/ody/data/local/service/EtaDashboardWorker.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/common/PermissionHelper.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/common/binding/BindingActivity.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/meetings/MeetingsActivity.kt
  android/app/src/main/res/values/strings.xml
Labels: AN, REFACTOR

#359 feat: 서버 응답 400, 500번대 예외 처리
  android/app/src/main/java/com/woowacourse/ody/data/remote/core/RetrofitClient.kt
  android/app/src/main/java/com/woowacourse/ody/data/remote/core/repository/DefaultMeetingRepository.kt
  android/app/src/main/java/com/woowacourse/ody/data/remote/core/service/MeetingService.kt
  android/app/src/main/java/com/woowacourse/ody/data/retrofit/ApiResultCall.kt
  android/app/src/main/java/com/woowacourse/ody/data/retrofit/ApiResultCallAdapter.kt
  android/app/src/main/java/com/woowacourse/ody/domain/apiresult/ApiResult.kt
  android/app/src/main/java/com/woowacourse/ody/domain/apiresult/ApiResultExtensions.kt
  android/app/src/main/java/com/woowacourse/ody/domain/repository/ody/MeetingRepository.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/meetings/MeetingsActivity.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/meetings/MeetingsViewModel.kt
  android/app/src/test/java/com/woowacourse/ody/fake/FakeMeetingRepository.kt
Labels: AN, FEATURE

#361 refactor: 로깅 관련 코드 리팩터링
  android/app/src/main/java/com/woowacourse/ody/OdyApplication.kt
  android/app/src/main/java/com/woowacourse/ody/data/local/service/EtaDashboardWorker.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/address/AddressSearchDialog.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/address/AddressSearchViewModel.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/address/AddressSearchViewModelFactory.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/common/analytics/AnalyticsExtension.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/common/analytics/AnalyticsHelper.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/common/analytics/FirebaseAnalyticsHelper.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/common/binding/BindingActivity.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/common/binding/BindingFragment.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/creation/MeetingCreationActivity.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/creation/MeetingCreationViewModel.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/creation/MeetingCreationViewModelFactory.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/invitecode/InviteCodeActivity.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/invitecode/InviteCodeViewModel.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/invitecode/InviteCodeViewModelFactory.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/join/MeetingJoinActivity.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/join/MeetingJoinViewModel.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/join/MeetingJoinViewModelFactory.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/meetings/MeetingsActivity.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/meetings/MeetingsViewModel.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/meetings/MeetingsViewModelFactory.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/room/log/NotificationLogActivity.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/room/log/NotificationLogViewModel.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/room/log/NotificationLogViewModelFactory.kt
Labels: AN, REFACTOR

#348 chore: 로깅 프레임워크 적용 및 모니터링 대시보드 구성
  .github/workflows/backend-cd-dev.yml
  .github/workflows/backend-ci-dev.yml
  backend/.gitignore
  backend/build.gradle
  backend/src/main/java/com/ody/common/config/WebConfig.java
  backend/src/main/java/com/ody/common/exception/GlobalExceptionHandler.java
  backend/src/main/java/com/ody/common/interceptor/CustomFilter.java
  backend/src/main/java/com/ody/common/interceptor/LoggingInterceptor.java
  backend/src/main/resources/application.yml
  backend/src/main/resources/logback-spring.xml
Labels: BE, INFRA

#389 design: 툴바 폰트 크기 줄이기
  android/app/src/main/res/drawable/ic_share.xml
  android/app/src/main/res/layout/toolbar_intro.xml
  android/app/src/main/res/layout/toolbar_meeting_room.xml
  android/app/src/main/res/values/styles.xml
Labels: AN, DESIGN

#390 fix: Last Location null 발생
  android/app/src/main/java/com/woowacourse/ody/data/local/service/EtaDashboardWorker.kt
Labels: AN, BUG

#388 design: 로그인 화면 디자인
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/java/com/woowacourse/ody/presentation/login/LoginActivity.kt
  android/app/src/main/res/drawable-hdpi/img_calendar.png
  android/app/src/main/res/drawable-hdpi/img_clap.png
  android/app/src/main/res/drawable-hdpi/img_kakao_login.png
  android/app/src/main/res/drawable-mdpi/img_calendar.png
  android/app/src/main/res/drawable-mdpi/img_clap.png
  android/app/src/main/res/drawable-mdpi/img_kakao_login.png
  android/app/src/main/res/drawable-xhdpi/img_calendar.png
  android/app/src/main/res/drawable-xhdpi/img_clap.png
  android/app/src/main/res/drawable-xhdpi/img_kakao_login.png
  android/app/src/main/res/drawable-xxhdpi/img_calendar.png
  android/app/src/main/res/drawable-xxhdpi/img_clap.png
  android/app/src/main/res/drawable-xxhdpi/img_kakao_login.png
  android/app/src/main/res/drawable-xxxhdpi/img_calendar.png
  android/app/src/main/res/drawable-xxxhdpi/img_clap.png
  android/app/src/main/res/drawable-xxxhdpi/img_kakao_login.png
  android/app/src/main/res/layout/activity_login.xml
Labels: AN, DESIGN

#392 test: InviteCodeViewModel 테스트
  android/app/build.gradle.kts
  android/app/src/main/java/com/woowacourse/ody/presentation/common/SingleLiveData.kt
  android/app/src/test/java/com/woowacourse/ody/fake/FakeAnalyticsHelper.kt
  android/app/src/test/java/com/woowacourse/ody/fake/FakeMeetingRepository.kt
  android/app/src/test/java/com/woowacourse/ody/util/TestUtil.kt
  android/app/src/test/java/com/woowacourse/ody/viewmodel/InviteCodeViewModelTest.kt
Labels: AN, TEST

#367 fix: 동일한 topic을 구독하여 참여하지 않은 메이트의 알림 받음
  backend/src/main/java/com/ody/meeting/domain/Meeting.java
  backend/src/main/java/com/ody/notification/domain/FcmTopic.java
  backend/src/main/java/com/ody/notification/dto/request/FcmSendRequest.java
  backend/src/main/java/com/ody/notification/service/FcmPushSender.java
  backend/src/main/java/com/ody/notification/service/FcmSubscriber.java
  backend/src/main/java/com/ody/notification/service/NotificationService.java
  backend/src/test/java/com/ody/notification/service/FcmEventSchedulerTest.java
Labels: BE, BUG

#396 test: 3차 스프린트 구현 사항 테스트
  android/app/src/main/java/com/woowacourse/ody/data/remote/core/entity/meeting/mapper/MatesEtaResponseMapper.kt
  android/app/src/main/java/com/woowacourse/ody/domain/model/MateEta.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/creation/MeetingCreationViewModel.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/join/MeetingJoinViewModel.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/meetings/MeetingsActivity.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/room/MeetingRoomViewModel.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/room/etadashboard/model/MateEtaUiModelMapper.kt
  android/app/src/test/java/com/woowacourse/ody/TestFixtures.kt
  android/app/src/test/java/com/woowacourse/ody/fake/FakeGeoLocationRepository.kt
  android/app/src/test/java/com/woowacourse/ody/fake/FakeJoinRepository.kt
  android/app/src/test/java/com/woowacourse/ody/fake/FakeMatesEtaRepository.kt
  android/app/src/test/java/com/woowacourse/ody/fake/FakeMeetingRepository.kt
  android/app/src/test/java/com/woowacourse/ody/fake/FakeNotificationLogRepository.kt
  android/app/src/test/java/com/woowacourse/ody/viewmodel/AddressSearchViewModelTest.kt
  android/app/src/test/java/com/woowacourse/ody/viewmodel/MeetingCreationViewModelTest.kt
  android/app/src/test/java/com/woowacourse/ody/viewmodel/MeetingJoinViewModelTest.kt
  android/app/src/test/java/com/woowacourse/ody/viewmodel/MeetingRoomViewModelTest.kt
Labels: AN, TEST

#398 test: MeetingsViewModel 테스트 작성
  android/app/src/main/java/com/woowacourse/ody/presentation/meetings/MeetingsViewModel.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/meetings/model/MeetingUiModelMapper.kt
  android/app/src/test/java/com/woowacourse/ody/TestFixtures.kt
  android/app/src/test/java/com/woowacourse/ody/fake/FakeMeetingRepository.kt
  android/app/src/test/java/com/woowacourse/ody/viewmodel/MeetingsViewModelTest.kt
Labels: AN, TEST

#403 chore: unitTest 패키지 구조 수정
  android/app/src/test/java/com/woowacourse/ody/presentation/address/AddressSearchViewModelTest.kt
  android/app/src/test/java/com/woowacourse/ody/presentation/creation/MeetingCreationViewModelTest.kt
  android/app/src/test/java/com/woowacourse/ody/presentation/invitecode/InviteCodeViewModelTest.kt
  android/app/src/test/java/com/woowacourse/ody/presentation/join/MeetingJoinViewModelTest.kt
  android/app/src/test/java/com/woowacourse/ody/presentation/meetings/MeetingsViewModelTest.kt
  android/app/src/test/java/com/woowacourse/ody/presentation/room/MeetingRoomViewModelTest.kt
Labels: AN, REFACTOR

#401 design: 현황 화면 뱃지 애니메이션 추가
  android/app/src/main/java/com/woowacourse/ody/presentation/room/etadashboard/EtaDashboardBindingAdapter.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/room/etadashboard/EtaDashboardFragment.kt
  android/app/src/main/res/anim/bounce_duration_500.xml
  android/app/src/main/res/layout/item_eta_dashboard.xml
Labels: AN, DESIGN

#409 design: 로그 화면 디자인 수정
  android/app/build.gradle.kts
  android/app/src/main/java/com/woowacourse/ody/domain/model/Mate.kt
  android/app/src/main/java/com/woowacourse/ody/domain/model/NotificationLog.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/common/CommonBindingAdapter.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/room/MeetingRoomActivity.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/room/MeetingRoomViewModel.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/room/etadashboard/EtaDashboardFragment.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/room/etadashboard/listener/MenuListener.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/room/log/BindingAdapter.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/room/log/NotificationLogBindingAdapter.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/room/log/NotificationLogFragment.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/room/log/adapter/InviteCodeViewHolder.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/room/log/adapter/MateViewHolder.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/room/log/adapter/MatesAdapter.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/room/log/adapter/NotificationLogsAdapter.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/room/log/listener/CopyInviteCodeListener.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/room/log/model/MateUiModel.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/room/log/model/MateUiModelMapper.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/room/log/model/NotificationLogUiModel.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/room/log/model/NotificationUiModelMapper.kt
  android/app/src/main/res/drawable/ic_menu.xml
  android/app/src/main/res/drawable/ic_person.xml
  android/app/src/main/res/drawable/rectangle_hamburger_menu.xml
  android/app/src/main/res/layout/activity_meeting_room.xml
  android/app/src/main/res/layout/bottom_sheet_code_copy.xml
  android/app/src/main/res/layout/fragment_eta_dashboard.xml
  android/app/src/main/res/layout/fragment_notification_log.xml
  android/app/src/main/res/layout/item_invite_code_log.xml
  android/app/src/main/res/layout/item_mate.xml
  android/app/src/main/res/layout/item_notification_log.xml
  android/app/src/main/res/layout/toolbar_eta_dashboard.xml
  android/app/src/main/res/layout/toolbar_notification_log.xml
  android/app/src/main/res/values/strings.xml
  android/gradle/libs.versions.toml
Labels: AN, DESIGN

#406 refactor: splash 라이브러리 사용으로 변경
  android/app/build.gradle.kts
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/java/com/woowacourse/ody/presentation/meetings/MeetingsActivity.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/splash/SplashActivity.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/splash/SplashNavigateAction.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/splash/SplashViewModel.kt
  android/app/src/main/res/drawable/splash_screen.xml
  android/app/src/main/res/layout/activity_splash.xml
  android/app/src/main/res/values-night/themes.xml
  android/app/src/main/res/values/themes.xml
  android/gradle/libs.versions.toml
Labels: AN, REFACTOR

#394 feat: 재촉하기 API 구현
  backend/src/main/java/com/ody/eta/service/EtaService.java
  backend/src/main/java/com/ody/mate/controller/MateController.java
  backend/src/main/java/com/ody/mate/controller/MateControllerSwagger.java
  backend/src/main/java/com/ody/mate/domain/EtaStatus.java
  backend/src/main/java/com/ody/mate/repository/MateRepository.java
  backend/src/main/java/com/ody/mate/service/MateService.java
  backend/src/main/java/com/ody/notification/domain/Notification.java
  backend/src/main/java/com/ody/notification/domain/NotificationType.java
  backend/src/main/java/com/ody/notification/domain/message/NudgeMessage.java
  backend/src/main/java/com/ody/notification/domain/message/PushMessage.java
  backend/src/main/java/com/ody/notification/dto/request/NudgeRequest.java
  backend/src/main/java/com/ody/notification/service/FcmPushSender.java
  backend/src/main/java/com/ody/notification/service/NotificationService.java
  backend/src/main/java/com/ody/swagger/annotation/ErrorCode400.java
  backend/src/test/java/com/ody/eta/service/EtaServiceTest.java
  backend/src/test/java/com/ody/mate/service/MateServiceTest.java
  backend/src/test/java/com/ody/notification/service/NotificationServiceTest.java
Labels: BE, FEATURE

#411 feat: 네트워크 오류, 서버 오류 시 스낵바/토스트 구현
  android/app/src/main/java/com/woowacourse/ody/data/local/db/OdyDatastore.kt
  android/app/src/main/java/com/woowacourse/ody/data/remote/core/repository/DefaultInviteCodeRepository.kt
  android/app/src/main/java/com/woowacourse/ody/data/remote/core/repository/DefaultJoinRepository.kt
  android/app/src/main/java/com/woowacourse/ody/data/remote/core/repository/DefaultMeetingRepository.kt
  android/app/src/main/java/com/woowacourse/ody/data/remote/core/repository/DefaultNotificationLogRepository.kt
  android/app/src/main/java/com/woowacourse/ody/data/remote/core/service/JoinService.kt
  android/app/src/main/java/com/woowacourse/ody/data/remote/core/service/MeetingService.kt
  android/app/src/main/java/com/woowacourse/ody/data/remote/core/service/NotificationService.kt
  android/app/src/main/java/com/woowacourse/ody/data/remote/thirdparty/location/KakaoRetrofitClient.kt
  android/app/src/main/java/com/woowacourse/ody/data/remote/thirdparty/location/repository/KakaoGeoLocationRepository.kt
  android/app/src/main/java/com/woowacourse/ody/data/remote/thirdparty/location/service/KakaoLocationService.kt
  android/app/src/main/java/com/woowacourse/ody/domain/repository/location/GeoLocationRepository.kt
  android/app/src/main/java/com/woowacourse/ody/domain/repository/ody/InviteCodeRepository.kt
  android/app/src/main/java/com/woowacourse/ody/domain/repository/ody/JoinRepository.kt
  android/app/src/main/java/com/woowacourse/ody/domain/repository/ody/MeetingRepository.kt
  android/app/src/main/java/com/woowacourse/ody/domain/repository/ody/NotificationLogRepository.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/address/AddressSearchDialog.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/address/AddressSearchViewModel.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/common/BaseViewModel.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/common/binding/BindingActivity.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/creation/MeetingCreationActivity.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/creation/MeetingCreationViewModel.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/invitecode/InviteCodeActivity.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/invitecode/InviteCodeViewModel.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/join/MeetingJoinActivity.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/join/MeetingJoinViewModel.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/meetings/MeetingsActivity.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/meetings/MeetingsViewModel.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/room/MeetingRoomActivity.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/room/MeetingRoomViewModel.kt
  android/app/src/main/res/values/strings.xml
  android/app/src/test/java/com/woowacourse/ody/fake/FakeGeoLocationRepository.kt
  android/app/src/test/java/com/woowacourse/ody/fake/FakeJoinRepository.kt
  android/app/src/test/java/com/woowacourse/ody/fake/FakeMeetingRepository.kt
  android/app/src/test/java/com/woowacourse/ody/fake/FakeNotificationLogRepository.kt
Labels: AN, FEATURE

#405 docs: 약속 참여자 도착 현황 조회 API 문서화
  backend/src/main/java/com/ody/meeting/controller/MeetingController.java
  backend/src/main/java/com/ody/meeting/controller/MeetingControllerSwagger.java
  backend/src/main/java/com/ody/meeting/dto/response/MateEtaResponseV2.java
  backend/src/main/java/com/ody/meeting/dto/response/MateEtaResponsesV2.java
Labels: BE, DOCS

#415 config: 난독화 적용
  android/app/build.gradle.kts
  android/app/proguard-rules.pro
Labels: AN, FEATURE

#418 refactor: ETA 조회 API 응답 수정
  android/app/src/main/java/com/woowacourse/ody/data/local/entity/eta/MatesEtaInfoResponse.kt
  android/app/src/main/java/com/woowacourse/ody/data/local/repository/DefaultMatesEtaRepository.kt
  android/app/src/main/java/com/woowacourse/ody/data/local/service/EtaDashboardWorker.kt
  android/app/src/main/java/com/woowacourse/ody/data/remote/core/entity/meeting/mapper/MatesEtaResponseMapper.kt
  android/app/src/main/java/com/woowacourse/ody/data/remote/core/entity/meeting/response/MateEtaResponse.kt
  android/app/src/main/java/com/woowacourse/ody/data/remote/core/entity/meeting/response/MatesEtaResponse.kt
  android/app/src/main/java/com/woowacourse/ody/data/remote/core/service/MeetingService.kt
  android/app/src/main/java/com/woowacourse/ody/domain/model/MateEta.kt
  android/app/src/main/java/com/woowacourse/ody/domain/model/MateEtaInfo.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/room/etadashboard/model/MateEtaUiModelMapper.kt
  android/app/src/test/java/com/woowacourse/ody/TestFixtures.kt
Labels: AN, REFACTOR

#417 refactor: ETA 조회 API 응답 수정
  backend/src/main/java/com/ody/eta/dto/request/MateEtaRequest.java
  backend/src/main/java/com/ody/eta/dto/response/MateEtaResponses.java
  backend/src/main/java/com/ody/eta/service/EtaService.java
  backend/src/main/java/com/ody/mate/service/MateService.java
  backend/src/main/java/com/ody/meeting/controller/MeetingController.java
  backend/src/main/java/com/ody/meeting/dto/response/MateEtaResponseV2.java
  backend/src/main/java/com/ody/meeting/dto/response/MateEtaResponsesV2.java
  backend/src/main/java/com/ody/meeting/service/MeetingService.java
  backend/src/test/java/com/ody/eta/service/EtaServiceTest.java
  backend/src/test/java/com/ody/mate/service/MateServiceTest.java
  backend/src/test/java/com/ody/meeting/controller/MeetingControllerTest.java
Labels: BE, REFACTOR

#426 feat: 위치 현황 카카오톡 공유 기능 구현
  .github/workflows/android-ci-dev.yml
  android/app/build.gradle.kts
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/java/com/woowacourse/ody/OdyApplication.kt
  android/app/src/main/java/com/woowacourse/ody/data/remote/thirdparty/image/FirebaseImageStorage.kt
  android/app/src/main/java/com/woowacourse/ody/domain/repository/image/ImageStorage.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/common/image/CaptureExtensions.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/common/image/ImageShareContent.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/common/image/ImageShareHelper.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/common/image/KakaoImageShareHelper.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/room/MeetingRoomActivity.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/room/MeetingRoomViewModel.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/room/MeetingRoomViewModelFactory.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/room/etadashboard/EtaDashboardFragment.kt
  android/app/src/main/res/layout/fragment_eta_dashboard.xml
  android/app/src/main/res/values/strings.xml
  android/app/src/test/java/com/woowacourse/ody/fake/FakeImageShareHelper.kt
  android/app/src/test/java/com/woowacourse/ody/fake/FakeImageStorage.kt
  android/app/src/test/java/com/woowacourse/ody/presentation/room/MeetingRoomViewModelTest.kt
  android/gradle/libs.versions.toml
  android/settings.gradle.kts
Labels: AN, FEATURE

#430 feat: 로딩 중 ProgressBar 다이얼로그 띄우는 기능 구현
  android/app/proguard-rules.pro
  android/app/src/main/java/com/woowacourse/ody/presentation/address/AddressSearchDialog.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/address/AddressSearchViewModel.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/common/BaseViewModel.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/common/LoadingDialog.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/common/binding/BindingActivity.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/creation/MeetingCreationActivity.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/creation/MeetingCreationViewModel.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/invitecode/InviteCodeActivity.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/invitecode/InviteCodeViewModel.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/join/MeetingJoinActivity.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/join/MeetingJoinViewModel.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/meetings/MeetingsActivity.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/meetings/MeetingsViewModel.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/room/MeetingRoomActivity.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/room/MeetingRoomViewModel.kt
  android/app/src/main/res/layout/dialog_loading.xml
Labels: AN, DESIGN

#420 feat: 콕찌르기 기능
  android/app/src/main/java/com/woowacourse/ody/data/remote/core/repository/DefaultMeetingRepository.kt
  android/app/src/main/java/com/woowacourse/ody/data/remote/core/service/MeetingService.kt
  android/app/src/main/java/com/woowacourse/ody/domain/model/NotificationType.kt
  android/app/src/main/java/com/woowacourse/ody/domain/repository/ody/MeetingRepository.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/common/binding/BindingFragment.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/notification/NotificationHelper.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/room/MeetingRoomViewModel.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/room/etadashboard/EtaDashboardBindingAdapter.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/room/etadashboard/EtaDashboardFragment.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/room/etadashboard/adapter/MateEtaViewHolder.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/room/etadashboard/adapter/MateEtasAdapter.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/room/etadashboard/listener/NudgeListener.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/room/etadashboard/model/MateEtaUiModel.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/room/etadashboard/model/MateEtaUiModelMapper.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/room/log/NotificationLogBindingAdapter.kt
  android/app/src/main/res/layout/item_eta_dashboard.xml
  android/app/src/main/res/values/strings.xml
  android/app/src/test/java/com/woowacourse/ody/fake/FakeMeetingRepository.kt
  android/app/src/test/java/com/woowacourse/ody/presentation/room/MeetingRoomViewModelTest.kt
Labels: AN, FEATURE

#431 feat: 초대 코드 카카오톡 공유하기 기능 구현
  android/app/src/main/java/com/woowacourse/ody/presentation/common/image/ImageShareContent.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/common/image/KakaoImageShareHelper.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/room/MeetingRoomViewModel.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/room/etadashboard/EtaDashboardFragment.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/room/etadashboard/listener/ShareListener.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/room/log/NotificationLogFragment.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/room/log/listener/InviteCodeCopyListener.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/room/log/listener/MenuListener.kt
  android/app/src/main/res/layout/fragment_eta_dashboard.xml
  android/app/src/main/res/layout/fragment_notification_log.xml
  android/app/src/main/res/layout/toolbar_eta_dashboard.xml
  android/app/src/main/res/layout/toolbar_notification_log.xml
  android/app/src/main/res/values/strings.xml
Labels: AN, FEATURE

#435 refactor: Firebase Analytics 로깅을 비동기로 남기도록 수정
  android/app/src/main/java/com/woowacourse/ody/presentation/common/binding/BindingFragment.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/meetings/MeetingsActivity.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/room/MeetingRoomViewModel.kt
Labels: AN, REFACTOR

#441 fix: fragment 로깅 찍는 시점 수정
  android/app/src/main/java/com/woowacourse/ody/presentation/common/binding/BindingFragment.kt
Labels: AN, BUG

#436 chore: HTTPS 적용
  .github/workflows/backend-cd-dev.yml
  .github/workflows/backend-cd-prod.yml
  backend/build.gradle
  backend/src/main/java/com/ody/swagger/config/SwaggerConfig.java
  backend/src/main/resources/application.yml
Labels: BE, INFRA

#422 chore: 로그 관련 중복 코드 제거 및 로그 내 Request Body 개행 제거
  backend/src/main/java/com/ody/common/interceptor/LoggingInterceptor.java
  backend/src/main/java/com/ody/common/interceptor/ServletWappingFilter.java
  backend/src/main/java/com/ody/common/interceptor/dto/RequestResponseWrappers.java
  backend/src/main/resources/logback-spring.xml
Labels: BE, INFRA

#438 chore: deprecated API 제거
  backend/src/main/java/com/ody/mate/controller/MateController.java
  backend/src/main/java/com/ody/mate/controller/MateControllerSwagger.java
  backend/src/main/java/com/ody/meeting/controller/MeetingController.java
  backend/src/main/java/com/ody/meeting/controller/MeetingControllerSwagger.java
  backend/src/test/java/com/ody/meeting/controller/MeetingControllerTest.java
Labels: BE, REFACTOR

#445 fix: 앱이 메뉴에서 보이지 않는 이슈 해결
  android/app/src/main/AndroidManifest.xml
Labels: AN, BUG

#439 refactor: 약속 참여 API 응답 수정
  backend/src/main/java/com/ody/eta/service/EtaService.java
  backend/src/main/java/com/ody/mate/controller/MateController.java
  backend/src/main/java/com/ody/mate/controller/MateControllerSwagger.java
  backend/src/main/java/com/ody/mate/domain/Mate.java
  backend/src/main/java/com/ody/mate/domain/Nickname.java
  backend/src/main/java/com/ody/mate/dto/request/MateSaveRequestV2.java
  backend/src/main/java/com/ody/mate/dto/response/MateSaveResponseV2.java
  backend/src/main/java/com/ody/mate/repository/MateRepository.java
  backend/src/main/java/com/ody/mate/service/MateService.java
  backend/src/main/java/com/ody/meeting/service/MeetingService.java
  backend/src/main/java/com/ody/member/domain/Member.java
  backend/src/main/java/com/ody/notification/service/NotificationService.java
  backend/src/main/java/com/ody/route/domain/DepartureTime.java
  backend/src/test/java/com/ody/mate/domain/NicknameTest.java
  backend/src/test/java/com/ody/mate/service/MateServiceTest.java
  backend/src/test/java/com/ody/notification/service/NotificationServiceTest.java
Labels: BE, REFACTOR

#446 chore: dev 서버 DB MySQL 교체 작업
  .github/workflows/backend-cd-dev.yml
  .github/workflows/backend-cd-prod.yml
  .github/workflows/backend-ci-dev.yml
  .github/workflows/backend-ci-prod.yml
  backend/docker-compose.yml
Labels: BE, INFRA

#455 fix: develop 스키마 validation 오류 해결 BE BUG
  backend/build.gradle
  backend/src/main/resources/application.yml
  backend/src/main/resources/schema.sql
Labels: BE, BUG

#457 feat: 재촉하기 알림에 닉네임이 보이게 변경
  android/app/src/main/java/com/woowacourse/ody/data/remote/core/entity/meeting/mapper/MeetingRequestMapper.kt
  android/app/src/main/java/com/woowacourse/ody/data/remote/core/entity/meeting/request/NudgeRequest.kt
  android/app/src/main/java/com/woowacourse/ody/data/remote/core/repository/DefaultMeetingRepository.kt
  android/app/src/main/java/com/woowacourse/ody/data/remote/core/service/MeetingService.kt
  android/app/src/main/java/com/woowacourse/ody/domain/model/Nudge.kt
  android/app/src/main/java/com/woowacourse/ody/domain/repository/ody/MeetingRepository.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/notification/NotificationHelper.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/room/MeetingRoomViewModel.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/room/etadashboard/EtaDashboardBindingAdapter.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/room/etadashboard/listener/NudgeListener.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/room/etadashboard/model/MateEtaUiModel.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/room/etadashboard/model/MateEtaUiModelMapper.kt
  android/app/src/main/res/values/strings.xml
  android/app/src/test/java/com/woowacourse/ody/fake/FakeMeetingRepository.kt
  android/app/src/test/java/com/woowacourse/ody/presentation/room/MeetingRoomViewModelTest.kt
Labels: AN, FEATURE

#447 refactor: 위경도 좌표 검증 로직 제거 및 Coordinate 객체 생성
  backend/src/main/java/com/ody/common/config/WebConfig.java
  backend/src/main/java/com/ody/eta/dto/request/MateEtaRequest.java
  backend/src/main/java/com/ody/eta/service/EtaService.java
  backend/src/main/java/com/ody/mate/domain/Mate.java
  backend/src/main/java/com/ody/mate/dto/request/MateSaveRequest.java
  backend/src/main/java/com/ody/mate/dto/request/MateSaveRequestV2.java
  backend/src/main/java/com/ody/mate/dto/response/MateSaveResponse.java
  backend/src/main/java/com/ody/mate/service/MateService.java
  backend/src/main/java/com/ody/meeting/controller/MeetingController.java
  backend/src/main/java/com/ody/meeting/controller/MeetingControllerSwagger.java
  backend/src/main/java/com/ody/meeting/domain/Coordinates.java
  backend/src/main/java/com/ody/meeting/domain/Location.java
  backend/src/main/java/com/ody/meeting/domain/Meeting.java
  backend/src/main/java/com/ody/meeting/dto/response/MateEtaResponsesV2.java
  backend/src/main/java/com/ody/meeting/dto/response/MeetingSaveResponse.java
  backend/src/main/java/com/ody/meeting/dto/response/MeetingSaveResponseV1.java
  backend/src/main/java/com/ody/meeting/dto/response/MeetingWithMatesResponse.java
  backend/src/main/java/com/ody/notification/domain/FcmTopic.java
  backend/src/main/java/com/ody/notification/domain/message/PushMessage.java
  backend/src/main/java/com/ody/route/service/OdsayRouteClient.java
  backend/src/main/java/com/ody/route/service/RouteClient.java
  backend/src/main/java/com/ody/route/service/RouteService.java
  backend/src/main/java/com/ody/swagger/config/SwaggerConfig.java
  backend/src/main/java/com/ody/util/DistanceCalculator.java
  backend/src/test/java/com/ody/common/FakeRouteClient.java
  backend/src/test/java/com/ody/eta/service/EtaServiceTest.java
  backend/src/test/java/com/ody/mate/repository/MateRepositoryTest.java
  backend/src/test/java/com/ody/meeting/controller/MeetingControllerTest.java
  backend/src/test/java/com/ody/meeting/domain/CoordinatesTest.java
  backend/src/test/java/com/ody/meeting/domain/LocationTest.java
  backend/src/test/java/com/ody/notification/repository/NotificationRepositoryTest.java
  backend/src/test/java/com/ody/route/service/OdsayRouteClientTest.java
  backend/src/test/java/com/ody/util/DistanceCalculatorTest.java
Labels: BE, REFACTOR

#448 feat: 카카오 소셜 로그인 구현 및 엑세스 토큰 발급
  backend/build.gradle
  backend/src/main/java/com/ody/auth/AuthProperties.java
  backend/src/main/java/com/ody/auth/JwtTokenProvider.java
  backend/src/main/java/com/ody/auth/controller/AuthController.java
  backend/src/main/java/com/ody/auth/controller/AuthControllerSwagger.java
  backend/src/main/java/com/ody/auth/domain/AuthorizationHeader.java
  backend/src/main/java/com/ody/auth/dto/request/AuthRequest.java
  backend/src/main/java/com/ody/auth/dto/response/AuthResponse.java
  backend/src/main/java/com/ody/auth/service/AuthService.java
  backend/src/main/java/com/ody/auth/token/AccessToken.java
  backend/src/main/java/com/ody/auth/token/RefreshToken.java
  backend/src/main/java/com/ody/common/argumentresolver/AuthMemberArgumentResolver.java
  backend/src/main/java/com/ody/common/config/WebConfig.java
  backend/src/main/java/com/ody/member/domain/AuthProvider.java
  backend/src/main/java/com/ody/member/domain/DeviceToken.java
  backend/src/main/java/com/ody/member/domain/Member.java
  backend/src/main/java/com/ody/member/domain/ProviderType.java
  backend/src/main/java/com/ody/member/repository/MemberRepository.java
  backend/src/main/java/com/ody/member/service/MemberService.java
  backend/src/main/java/com/ody/notification/domain/message/NudgeMessage.java
  backend/src/main/java/com/ody/notification/service/FcmSubscriber.java
  backend/src/main/resources/schema.sql
  backend/src/test/java/com/ody/auth/JwtTokenProviderTest.java
  backend/src/test/java/com/ody/auth/controller/AuthControllerTest.java
  backend/src/test/java/com/ody/auth/domain/AuthorizationHeaderTest.java
  backend/src/test/java/com/ody/auth/service/AuthServiceTest.java
  backend/src/test/java/com/ody/common/BaseControllerTest.java
  backend/src/test/java/com/ody/common/BaseServiceTest.java
  backend/src/test/java/com/ody/common/Fixture.java
  backend/src/test/java/com/ody/common/TestAuthConfig.java
  backend/src/test/java/com/ody/common/TokenFixture.java
  backend/src/test/java/com/ody/mate/controller/MateControllerTest.java
  backend/src/test/java/com/ody/mate/service/MateServiceTest.java
  backend/src/test/java/com/ody/meeting/controller/MeetingControllerTest.java
  backend/src/test/java/com/ody/meeting/service/MeetingServiceTest.java
  backend/src/test/java/com/ody/member/controller/MemberControllerTest.java
  backend/src/test/java/com/ody/member/domain/DeviceTokenTest.java
  backend/src/test/java/com/ody/member/repository/MemberRepositoryTest.java
  backend/src/test/java/com/ody/member/service/MemberServiceTest.java
Labels: BE, FEATURE

#461 refactor: 로그 목록 조회, 약속 단건 조회 API에 imageUrl 필드 추가
  backend/src/main/java/com/ody/mate/controller/MateController.java
  backend/src/main/java/com/ody/mate/controller/MateControllerSwagger.java
  backend/src/main/java/com/ody/mate/domain/Mate.java
  backend/src/main/java/com/ody/mate/dto/response/MateResponse.java
  backend/src/main/java/com/ody/mate/repository/MateRepository.java
  backend/src/main/java/com/ody/meeting/controller/MeetingController.java
  backend/src/main/java/com/ody/notification/dto/response/NotiLogFindResponse.java
  backend/src/test/java/com/ody/mate/controller/MateControllerTest.java
Labels: BE, REFACTOR

#452 refactor: 약속 참여 api 수정 및 닉네임 입력 화면 삭제
  android/app/src/androidTest/java/com/woowacourse/ody/presentation/join/MeetingJoinActivityTest.kt
  android/app/src/main/java/com/woowacourse/ody/data/remote/core/entity/join/mapper/JoinRequestMapper.kt
  android/app/src/main/java/com/woowacourse/ody/data/remote/core/entity/join/request/JoinRequest.kt
  android/app/src/main/java/com/woowacourse/ody/data/remote/core/entity/join/response/JoinResponse.kt
  android/app/src/main/java/com/woowacourse/ody/data/remote/core/service/JoinService.kt
  android/app/src/main/java/com/woowacourse/ody/domain/model/MeetingJoinInfo.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/join/MeetingJoinActivity.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/join/MeetingJoinInfoType.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/join/MeetingJoinViewModel.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/join/nickname/JoinNickNameFragment.kt
  android/app/src/main/res/layout/fragment_join_nickname.xml
  android/app/src/test/java/com/woowacourse/ody/presentation/join/MeetingJoinViewModelTest.kt
Labels: AN, REFACTOR

#462 feat: 로그 목록 조회, 약속 단건 조회 response에 imageUrl 필드 추가
  android/app/src/main/java/com/woowacourse/ody/data/remote/core/entity/meeting/mapper/MeetingResponseMapper.kt
  android/app/src/main/java/com/woowacourse/ody/data/remote/core/entity/meeting/response/MateResponse.kt
  android/app/src/main/java/com/woowacourse/ody/data/remote/core/entity/notification/mapper/NotificationLogsResponseMapper.kt
  android/app/src/main/java/com/woowacourse/ody/data/remote/core/entity/notification/response/NotificationLogResponse.kt
  android/app/src/main/java/com/woowacourse/ody/domain/model/Mate.kt
  android/app/src/main/java/com/woowacourse/ody/domain/model/NotificationLog.kt
  android/app/src/test/java/com/woowacourse/ody/TestFixtures.kt
Labels: AN, FEATURE

#463 chore: 안드로이드 CD 구축
  .github/workflows/android-cd-dev.yml
Labels: AN, INFRA

#467 fix: 약속 목록이 제대로 ui에 반영되지 않는 버그 해결
  android/app/src/main/java/com/woowacourse/ody/presentation/login/LoginActivity.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/meetings/MeetingsActivity.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/meetings/MeetingsViewModel.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/room/log/NotificationLogBindingAdapter.kt
  android/app/src/main/res/drawable/ic_happy_ody.xml
  android/app/src/main/res/drawable/ic_sad_ody.xml
  android/app/src/main/res/drawable/ic_together_ody.xml
  android/app/src/main/res/layout/activity_login.xml
  android/app/src/main/res/layout/activity_meetings.xml
  android/app/src/main/res/values/strings.xml
Labels: AN, BUG

#470 design: 초대코드 공유 이미지 링크 수정
  android/app/src/main/java/com/woowacourse/ody/presentation/room/log/NotificationLogFragment.kt
Labels: AN, DESIGN

#472 feat: 약속 리스트에서 뒤로가기 2번 하면 나갈 수 있는 기능 구현
  android/app/build.gradle.kts
  android/app/src/main/java/com/woowacourse/ody/presentation/meetings/MeetingsActivity.kt
  android/app/src/main/res/values/strings.xml
Labels: AN, FEATURE
