Repository woowacourse-teams/2024-ody, pull requests merged in 2024-11, with the labels that each got.

#873 fix: 약속 참여할 때 가끔 바로 로그화면으로 가지지 않는 버그 수정
  android/app/src/main/java/com/mulberry/ody/presentation/join/MeetingJoinActivity.kt
  android/app/src/main/java/com/mulberry/ody/presentation/join/MeetingJoinViewModel.kt
  android/app/src/main/java/com/mulberry/ody/presentation/join/listener/MeetingJoinListener.kt
  android/app/src/test/java/com/mulberry/ody/presentation/join/MeetingJoinViewModelTest.kt
Labels: AN, BUG

#882 fix: 약속을 나간 경우에도 eta 폴링 요청을 계속 보내는 버그 수정
  android/app/src/main/java/com/mulberry/ody/data/local/repository/DefaultMatesEtaRepository.kt
Labels: AN, BUG

#875 refactor: repeatOnLifecycle 확장 함수 수정
  README.md
  android/app/src/main/java/com/mulberry/ody/presentation/LifecycleExtensions.kt
  android/app/src/main/java/com/mulberry/ody/presentation/address/AddressSearchFragment.kt
  android/app/src/main/java/com/mulberry/ody/presentation/creation/MeetingCreationActivity.kt
  android/app/src/main/java/com/mulberry/ody/presentation/creation/date/MeetingDateFragment.kt
  android/app/src/main/java/com/mulberry/ody/presentation/creation/destination/MeetingDestinationFragment.kt
  android/app/src/main/java/com/mulberry/ody/presentation/creation/time/MeetingTimeFragment.kt
  android/app/src/main/java/com/mulberry/ody/presentation/invitecode/InviteCodeActivity.kt
  android/app/src/main/java/com/mulberry/ody/presentation/join/MeetingJoinActivity.kt
  android/app/src/main/java/com/mulberry/ody/presentation/login/LoginActivity.kt
  android/app/src/main/java/com/mulberry/ody/presentation/meetings/MeetingsActivity.kt
  android/app/src/main/java/com/mulberry/ody/presentation/room/MeetingRoomActivity.kt
  android/app/src/main/java/com/mulberry/ody/presentation/room/etadashboard/EtaDashboardFragment.kt
  android/app/src/main/java/com/mulberry/ody/presentation/room/log/ExitMeetingRoomDialog.kt
  android/app/src/main/java/com/mulberry/ody/presentation/room/log/NotificationLogFragment.kt
  android/app/src/main/java/com/mulberry/ody/presentation/setting/SettingActivity.kt
Labels: AN, REFACTOR

#884 design: 나가기 로그 타입 문자열 수정
  android/app/src/main/java/com/mulberry/ody/data/remote/core/entity/notification/mapper/NotificationLogsResponseMapper.kt
Labels: AN, DESIGN

#886 fix: ODsay 호출 시 RouteTime 매핑 실패
  backend/src/main/java/com/ody/eta/service/EtaService.java
  backend/src/main/java/com/ody/route/config/RouteClientLoggingInterceptor.java
  backend/src/main/java/com/ody/route/config/RouteClientProperties.java
  backend/src/main/java/com/ody/route/config/RouteClientProperty.java
  backend/src/main/java/com/ody/route/config/RouteConfig.java
  backend/src/main/java/com/ody/route/config/RouteProperties.java
  backend/src/main/java/com/ody/route/service/GoogleRouteClient.java
  backend/src/main/java/com/ody/route/service/OdsayRouteClient.java
  backend/src/main/java/com/ody/route/service/RouteService.java
  backend/src/main/resources/common.yml
  backend/src/test/java/com/ody/common/BaseRouteClientTest.java
  backend/src/test/java/com/ody/route/service/GoogleRouteClientTest.java
  backend/src/test/java/com/ody/route/service/OdsayRouteClientTest.java
  backend/src/test/resources/application.yml
Labels: BE, BUG

#888 release: 안드로이드 1.2.3 배포
  android/app/build.gradle.kts
  android/app/src/main/java/com/mulberry/ody/data/local/repository/DefaultMatesEtaRepository.kt
  android/app/src/main/java/com/mulberry/ody/data/remote/core/entity/notification/mapper/NotificationLogsResponseMapper.kt
  android/app/src/main/java/com/mulberry/ody/presentation/LifecycleExtensions.kt
  android/app/src/main/java/com/mulberry/ody/presentation/address/AddressSearchFragment.kt
  android/app/src/main/java/com/mulberry/ody/presentation/creation/MeetingCreationActivity.kt
  android/app/src/main/java/com/mulberry/ody/presentation/creation/date/MeetingDateFragment.kt
  android/app/src/main/java/com/mulberry/ody/presentation/creation/destination/MeetingDestinationFragment.kt
  android/app/src/main/java/com/mulberry/ody/presentation/creation/time/MeetingTimeFragment.kt
  android/app/src/main/java/com/mulberry/ody/presentation/invitecode/InviteCodeActivity.kt
  android/app/src/main/java/com/mulberry/ody/presentation/join/MeetingJoinActivity.kt
  android/app/src/main/java/com/mulberry/ody/presentation/join/MeetingJoinViewModel.kt
  android/app/src/main/java/com/mulberry/ody/presentation/join/listener/MeetingJoinListener.kt
  android/app/src/main/java/com/mulberry/ody/presentation/login/LoginActivity.kt
  android/app/src/main/java/com/mulberry/ody/presentation/meetings/MeetingsActivity.kt
  android/app/src/main/java/com/mulberry/ody/presentation/room/MeetingRoomActivity.kt
  android/app/src/main/java/com/mulberry/ody/presentation/room/etadashboard/EtaDashboardFragment.kt
  android/app/src/main/java/com/mulberry/ody/presentation/room/log/ExitMeetingRoomDialog.kt
  android/app/src/main/java/com/mulberry/ody/presentation/room/log/NotificationLogFragment.kt
  android/app/src/main/java/com/mulberry/ody/presentation/setting/SettingActivity.kt
  android/app/src/test/java/com/mulberry/ody/presentation/join/MeetingJoinViewModelTest.kt
  backend/src/main/java/com/ody/eta/service/EtaService.java
  backend/src/main/java/com/ody/route/config/RouteConfig.java
  backend/src/main/java/com/ody/route/service/GoogleRouteClient.java
  backend/src/main/java/com/ody/route/service/OdsayRouteClient.java
  backend/src/main/java/com/ody/route/service/RouteService.java
  backend/src/main/resources/common.yml
  backend/src/test/java/com/ody/common/BaseRouteClientTest.java
  backend/src/test/java/com/ody/route/service/GoogleRouteClientTest.java
  backend/src/test/java/com/ody/route/service/OdsayRouteClientTest.java
  backend/src/test/resources/application.yml
Labels: AN, RELEASE

#890 release: 백엔드 버전 2.3 배포
  backend/src/main/java/com/ody/mate/domain/Mate.java
  backend/src/main/java/com/ody/route/config/RouteClientLoggingInterceptor.java
  backend/src/main/java/com/ody/route/config/RouteClientProperties.java
  backend/src/main/java/com/ody/route/config/RouteClientProperty.java
  backend/src/test/java/com/ody/mate/controller/MateControllerTest.java
Labels: BE, RELEASE

#892 chore: 나갔던 약속에 재참여가 되지 않는 문제 개선 SQL 추가
  backend/src/main/resources/db/migration/V8__drop_unique_meeting_and_member.sql
  backend/src/main/resources/db/migration/V9__add_unique_meeting_and_member_and_deleted_at.sql
Labels: BE, INFRA

#897 chore: matching main and develop cd scripts
  .github/workflows/android-cd-dev.yml
  .github/workflows/backend-cd-prod.yml
Labels: AN, BE, INFRA

#895 release: 백엔드 버전 2.3.1 배포
  backend/src/main/resources/db/migration/V8__drop_unique_meeting_and_member.sql
  backend/src/main/resources/db/migration/V9__add_unique_meeting_and_member_and_deleted_at.sql
Labels: BE, RELEASE

#878 refactor: memberService에서 인증관련 로직 분리
  backend/README.md
  backend/src/main/java/com/ody/auth/JwtTokenProvider.java
  backend/src/main/java/com/ody/auth/domain/Authorizer.java
  backend/src/main/java/com/ody/auth/domain/logincontext/ExistingUserForExistingDevice.java
  backend/src/main/java/com/ody/auth/domain/logincontext/ExistingUserForNewDevice.java
  backend/src/main/java/com/ody/auth/domain/logincontext/LoginContext.java
  backend/src/main/java/com/ody/auth/domain/logincontext/NewUserForExistingDevice.java
  backend/src/main/java/com/ody/auth/domain/logincontext/NewUserForNewDevice.java
  backend/src/main/java/com/ody/auth/domain/logincontext/OtherUserForExistingDevice.java
  backend/src/main/java/com/ody/auth/service/AuthService.java
  backend/src/main/java/com/ody/auth/token/AccessToken.java
  backend/src/main/java/com/ody/auth/token/JwtToken.java
  backend/src/main/java/com/ody/auth/token/RefreshToken.java
  backend/src/main/java/com/ody/member/domain/Member.java
  backend/src/main/java/com/ody/member/service/MemberService.java
  backend/src/test/java/com/ody/auth/domain/authorizeType/ExistingUserForExistingDeviceTest.java
  backend/src/test/java/com/ody/auth/domain/authorizeType/ExistingUserForNewDeviceTest.java
  backend/src/test/java/com/ody/auth/domain/authorizeType/NewUserForExistingDeviceTest.java
  backend/src/test/java/com/ody/auth/domain/authorizeType/NewUserForNewDeviceTest.java
  backend/src/test/java/com/ody/auth/domain/authorizeType/OtherUserForExistingDeviceTest.java
  backend/src/test/java/com/ody/auth/service/AuthServiceTest.java
  backend/src/test/java/com/ody/common/DtoGenerator.java
  backend/src/test/java/com/ody/member/service/MemberServiceTest.java
  backend/src/test/java/com/ody/route/repository/ApiCallRepositoryTest.java
Labels: BE, REFACTOR

#898 fix: ODsay 호출 시 OdsayResponse 매핑 안 되는 문제 해결
  backend/src/main/java/com/ody/common/config/WebConfig.java
  backend/src/main/java/com/ody/route/config/RouteClientLoggingInterceptor.java
  backend/src/main/java/com/ody/route/dto/OdsayResponse.java
  backend/src/main/java/com/ody/route/mapper/OdsayResponseMapper.java
  backend/src/main/java/com/ody/route/service/OdsayRouteClient.java
  backend/src/main/java/com/ody/route/service/RouteService.java
Labels: BE, BUG

#903 fix: RouteClinet 로깅 및 리팩터링 누락 코드 추가
  backend/src/main/java/com/ody/eta/service/EtaService.java
  backend/src/main/java/com/ody/route/config/RouteClientProperties.java
  backend/src/main/java/com/ody/route/config/RouteClientProperty.java
  backend/src/main/java/com/ody/route/config/RouteConfig.java
  backend/src/main/java/com/ody/route/config/RouteProperties.java
  backend/src/main/java/com/ody/route/service/GoogleRouteClient.java
  backend/src/main/java/com/ody/route/service/OdsayRouteClient.java
  backend/src/main/resources/common.yml
  backend/src/test/java/com/ody/common/BaseRouteClientTest.java
  backend/src/test/java/com/ody/route/service/GoogleRouteClientTest.java
  backend/src/test/java/com/ody/route/service/OdsayRouteClientTest.java
  backend/src/test/resources/application.yml
Labels: BE, BUG, INFRA

#909 refactor: 약속방 중복참여 에러 메세지 수정
  backend/src/main/java/com/ody/mate/service/MateService.java
Labels: BE, REFACTOR

#912 release: 백엔드 버전 2.3.2 배포
  README.md
  backend/README.md
  backend/src/main/java/com/ody/auth/JwtTokenProvider.java
  backend/src/main/java/com/ody/auth/domain/Authorizer.java
  backend/src/main/java/com/ody/auth/domain/logincontext/ExistingUserForExistingDevice.java
  backend/src/main/java/com/ody/auth/domain/logincontext/ExistingUserForNewDevice.java
  backend/src/main/java/com/ody/auth/domain/logincontext/LoginContext.java
  backend/src/main/java/com/ody/auth/domain/logincontext/NewUserForExistingDevice.java
  backend/src/main/java/com/ody/auth/domain/logincontext/NewUserForNewDevice.java
  backend/src/main/java/com/ody/auth/domain/logincontext/OtherUserForExistingDevice.java
  backend/src/main/java/com/ody/auth/service/AuthService.java
  backend/src/main/java/com/ody/auth/token/AccessToken.java
  backend/src/main/java/com/ody/auth/token/JwtToken.java
  backend/src/main/java/com/ody/auth/token/RefreshToken.java
  backend/src/main/java/com/ody/common/config/WebConfig.java
  backend/src/main/java/com/ody/eta/service/EtaService.java
  backend/src/main/java/com/ody/mate/service/MateService.java
  backend/src/main/java/com/ody/member/domain/Member.java
  backend/src/main/java/com/ody/member/service/MemberService.java
  backend/src/main/java/com/ody/route/config/RouteClientLoggingInterceptor.java
  backend/src/main/java/com/ody/route/config/RouteClientProperties.java
  backend/src/main/java/com/ody/route/config/RouteClientProperty.java
  backend/src/main/java/com/ody/route/config/RouteConfig.java
  backend/src/main/java/com/ody/route/config/RouteProperties.java
  backend/src/main/java/com/ody/route/dto/OdsayResponse.java
  backend/src/main/java/com/ody/route/mapper/OdsayResponseMapper.java
  backend/src/main/java/com/ody/route/service/GoogleRouteClient.java
  backend/src/main/java/com/ody/route/service/OdsayRouteClient.java
  backend/src/main/java/com/ody/route/service/RouteService.java
  backend/src/main/resources/common.yml
  backend/src/test/java/com/ody/auth/domain/authorizeType/ExistingUserForExistingDeviceTest.java
  backend/src/test/java/com/ody/auth/domain/authorizeType/ExistingUserForNewDeviceTest.java
  backend/src/test/java/com/ody/auth/domain/authorizeType/NewUserForExistingDeviceTest.java
  backend/src/test/java/com/ody/auth/domain/authorizeType/NewUserForNewDeviceTest.java
  backend/src/test/java/com/ody/auth/domain/authorizeType/OtherUserForExistingDeviceTest.java
  backend/src/test/java/com/ody/auth/service/AuthServiceTest.java
  backend/src/test/java/com/ody/common/BaseRouteClientTest.java
  backend/src/test/java/com/ody/common/DtoGenerator.java
  backend/src/test/java/com/ody/member/service/MemberServiceTest.java
  backend/src/test/java/com/ody/route/repository/ApiCallRepositoryTest.java
  backend/src/test/java/com/ody/route/service/GoogleRouteClientTest.java
  backend/src/test/java/com/ody/route/service/OdsayRouteClientTest.java
  backend/src/test/resources/application.yml
Labels: BE, RELEASE

#907 refactor: 초대코드 유효하지 않은 메시지 서버로부터 받게 변경
  android/app/src/main/java/com/mulberry/ody/data/remote/core/entity/ErrorResponse.kt
  android/app/src/main/java/com/mulberry/ody/data/retrofit/ApiResultCall.kt
  android/app/src/main/java/com/mulberry/ody/domain/apiresult/ApiResult.kt
  android/app/src/main/java/com/mulberry/ody/domain/apiresult/ApiResultExtensions.kt
  android/app/src/main/java/com/mulberry/ody/presentation/common/binding/BindingActivity.kt
  android/app/src/main/java/com/mulberry/ody/presentation/invitecode/InviteCodeActivity.kt
  android/app/src/main/java/com/mulberry/ody/presentation/invitecode/InviteCodeViewModel.kt
  android/app/src/test/java/com/mulberry/ody/presentation/invitecode/InviteCodeViewModelTest.kt
Labels: AN, REFACTOR

#910 refacator: API 의존성 관리 로직 개선
  backend/build.gradle
  backend/docker-compose-local.yml
  backend/src/main/java/com/ody/common/config/RedisConfig.java
  backend/src/main/java/com/ody/route/domain/RouteClientKey.java
  backend/src/main/java/com/ody/route/repository/RouteClientRedisTemplate.java
  backend/src/main/java/com/ody/route/service/RouteClientCircuitBreaker.java
  backend/src/main/java/com/ody/route/service/RouteClientManager.java
  backend/src/main/java/com/ody/route/service/RouteService.java
  backend/src/main/resources/application-dev.yml
  backend/src/main/resources/application-local.yml
  backend/src/main/resources/application-prod.yml
  backend/src/main/resources/common.yml
  backend/src/test/java/com/ody/common/BaseControllerTest.java
  backend/src/test/java/com/ody/common/BaseRedisTest.java
  backend/src/test/java/com/ody/common/BaseServiceTest.java
  backend/src/test/java/com/ody/common/RedisTestContainersConfig.java
  backend/src/test/java/com/ody/route/repository/RouteClientRedisTemplateTest.java
  backend/src/test/java/com/ody/route/service/RouteClientCircuitBreakerTest.java
  backend/src/test/java/com/ody/route/service/RouteClientManagerTest.java
  backend/src/test/java/com/ody/route/service/RouteServiceTest.java
Labels: BE, REFACTOR, INFRA

#918 chore: Redis 연결 설정 오류 해결
  backend/src/main/java/com/ody/common/config/RedisConfig.java
  backend/src/main/resources/common.yml
Labels: BE, BUG, INFRA

#915 fix: 재촉을 못할때는 재촉 요청이 안가게 수정
  android/app/src/main/java/com/mulberry/ody/presentation/room/MeetingRoomViewModel.kt
Labels: AN, BUG

#914 feat: API 호출 카운팅 동시성 제어
  backend/build.gradle
  backend/src/main/java/com/ody/common/aop/DistributedLock.java
  backend/src/main/java/com/ody/common/aop/DistributedLockAop.java
  backend/src/main/java/com/ody/common/config/RedisConfig.java
  backend/src/main/java/com/ody/common/redis/RedissonLockManager.java
  backend/src/main/java/com/ody/eta/service/EtaService.java
  backend/src/main/java/com/ody/meeting/service/MeetingService.java
  backend/src/test/java/com/ody/common/BaseServiceTest.java
  backend/src/test/java/com/ody/common/RedisTestContainersConfig.java
  backend/src/test/java/com/ody/common/redis/RouteClientRedisTemplateTest.java
  backend/src/test/java/com/ody/eta/service/EtaServiceTest.java
  backend/src/test/java/com/ody/meeting/service/MeetingServiceTest.java
  backend/src/test/java/com/ody/route/service/ApiCallServiceTest.java
  backend/src/test/java/com/ody/route/service/RouteServiceTest.java
Labels: BE, FEATURE

#906 refactor: 비동기 + 이벤트 리스닝 방식으로 알림 로직 개선
  backend/src/main/java/com/ody/common/config/AsyncConfig.java
  backend/src/main/java/com/ody/common/exception/AsyncExceptionHandler.java
  backend/src/main/java/com/ody/mate/service/MateService.java
  backend/src/main/java/com/ody/meeting/service/MeetingService.java
  backend/src/main/java/com/ody/notification/service/FcmEventListener.java
  backend/src/main/java/com/ody/notification/service/FcmEventPublisher.java
  backend/src/main/java/com/ody/notification/service/FcmPushSender.java
  backend/src/main/java/com/ody/notification/service/NotificationService.java
  backend/src/main/java/com/ody/notification/service/event/NoticeEvent.java
  backend/src/main/java/com/ody/notification/service/event/NudgeEvent.java
  backend/src/main/java/com/ody/notification/service/event/PushEvent.java
  backend/src/main/java/com/ody/notification/service/event/SubscribeEvent.java
  backend/src/main/java/com/ody/notification/service/event/UnSubscribeEvent.java
  backend/src/test/java/com/ody/common/BaseServiceTest.java
  backend/src/test/java/com/ody/common/exception/AsyncExceptionHandlerTest.java
  backend/src/test/java/com/ody/mate/controller/MateControllerTest.java
  backend/src/test/java/com/ody/mate/service/MateServiceTest.java
  backend/src/test/java/com/ody/meeting/service/MeetingServiceTest.java
  backend/src/test/java/com/ody/notification/service/FcmEventListenerTest.java
  backend/src/test/java/com/ody/notification/service/FcmPushSenderTest.java
  backend/src/test/java/com/ody/notification/service/NotificationServiceTest.java
Labels: BE, REFACTOR

#919 feat: 주소 검색 무한 스크롤 구현
  android/app/build.gradle.kts
  android/app/src/main/java/com/mulberry/ody/data/remote/thirdparty/address/AddressPagingSource.kt
  android/app/src/main/java/com/mulberry/ody/data/remote/thirdparty/address/KakaoAddressRepository.kt
  android/app/src/main/java/com/mulberry/ody/data/remote/thirdparty/address/KakaoAddressService.kt
  android/app/src/main/java/com/mulberry/ody/data/remote/thirdparty/address/response/AddressResponseMapper.kt
  android/app/src/main/java/com/mulberry/ody/domain/apiresult/ApiResultExtensions.kt
  android/app/src/main/java/com/mulberry/ody/domain/model/Addresses.kt
  android/app/src/main/java/com/mulberry/ody/domain/repository/location/AddressRepository.kt
  android/app/src/main/java/com/mulberry/ody/presentation/address/AddressSearchFragment.kt
  android/app/src/main/java/com/mulberry/ody/presentation/address/AddressSearchViewModel.kt
  android/app/src/main/java/com/mulberry/ody/presentation/address/adapter/AddressesAdapter.kt
  android/app/src/main/java/com/mulberry/ody/presentation/address/listener/AddressListener.kt
  android/app/src/main/java/com/mulberry/ody/presentation/address/listener/AddressViewHolder.kt
  android/app/src/main/java/com/mulberry/ody/presentation/address/model/AddressUiModel.kt
  android/app/src/main/java/com/mulberry/ody/presentation/address/model/AddressUiModelMapper.kt
  android/app/src/main/res/layout/item_address_search.xml
  android/app/src/test/java/com/mulberry/ody/TestFixtures.kt
  android/app/src/test/java/com/mulberry/ody/fake/FakeAddressRepository.kt
  android/app/src/test/java/com/mulberry/ody/presentation/address/AddressSearchViewModelTest.kt
  android/gradle/libs.versions.toml
Labels: AN, FEATURE
