Repository woowacourse-teams/2024-ody, pull requests merged in 2024-09, with the labels that each got.

#477 docs: 회원 삭제 API 문서화
  backend/src/main/java/com/ody/member/controller/MemberController.java
  backend/src/main/java/com/ody/member/controller/MemberControllerSwagger.java
Labels: BE, DOCS

#474 refactor: 지난 약속에 참여하지 못하도록 예외처리
  backend/src/main/java/com/ody/meeting/service/MeetingService.java
  backend/src/test/java/com/ody/meeting/service/MeetingServiceTest.java
Labels: BE, REFACTOR

#496 feat: 설정 화면에서 개인정보 처리 방침, 서비스 이용 약관 링크 연결
  .github/workflows/android-ci-dev.yml
  android/app/build.gradle.kts
  android/app/src/main/java/com/mulberry/ody/presentation/setting/SettingActivity.kt
Labels: AN, FEATURE

#491 fix: 약속이 개설되지 않는 버그 수정
  android/app/proguard-rules.pro
Labels: AN, BUG

#410 feat: 애플리케이션 재시작 시 PENDING 상태 알림 스케줄링 및 새벽 4시마다 지난 모임 삭제 기능 추가
  backend/src/main/java/com/ody/common/config/ClockConfig.java
  backend/src/main/java/com/ody/common/domain/BaseEntity.java
  backend/src/main/java/com/ody/mate/repository/MateRepository.java
  backend/src/main/java/com/ody/mate/service/MateService.java
  backend/src/main/java/com/ody/meeting/controller/MeetingControllerSwagger.java
  backend/src/main/java/com/ody/meeting/domain/Meeting.java
  backend/src/main/java/com/ody/meeting/repository/MeetingRepository.java
  backend/src/main/java/com/ody/meeting/service/MeetingService.java
  backend/src/main/java/com/ody/notification/domain/FcmTopic.java
  backend/src/main/java/com/ody/notification/domain/Notification.java
  backend/src/main/java/com/ody/notification/domain/message/PushMessage.java
  backend/src/main/java/com/ody/notification/dto/request/FcmSendRequest.java
  backend/src/main/java/com/ody/notification/repository/NotificationRepository.java
  backend/src/main/java/com/ody/notification/service/FcmPushSender.java
  backend/src/main/java/com/ody/notification/service/FcmSubscriber.java
  backend/src/main/java/com/ody/notification/service/NotificationService.java
  backend/src/test/java/com/ody/common/BaseControllerTest.java
  backend/src/test/java/com/ody/common/BaseServiceTest.java
  backend/src/test/java/com/ody/mate/repository/MateRepositoryTest.java
  backend/src/test/java/com/ody/mate/service/MateServiceTest.java
  backend/src/test/java/com/ody/meeting/repository/MeetingRepositoryTest.java
  backend/src/test/java/com/ody/notification/repository/NotificationRepositoryTest.java
  backend/src/test/java/com/ody/notification/service/FcmEventSchedulerTest.java
  backend/src/test/java/com/ody/notification/service/NotificationServiceTest.java
Labels: BE, FEATURE

#493 feat: 로그아웃 기능 구현
  backend/src/main/java/com/ody/auth/JwtTokenProvider.java
  backend/src/main/java/com/ody/auth/controller/AuthController.java
  backend/src/main/java/com/ody/auth/controller/AuthControllerSwagger.java
  backend/src/main/java/com/ody/auth/service/AuthService.java
  backend/src/main/java/com/ody/auth/token/AccessToken.java
  backend/src/main/java/com/ody/auth/token/RefreshToken.java
  backend/src/main/java/com/ody/member/domain/Member.java
  backend/src/main/java/com/ody/member/service/MemberService.java
  backend/src/main/java/com/ody/swagger/annotation/ErrorCode401.java
  backend/src/test/java/com/ody/auth/service/AuthServiceTest.java
  backend/src/test/java/com/ody/common/TokenFixture.java
  backend/src/test/java/com/ody/member/service/MemberServiceTest.java
Labels: BE, FEATURE

#501 chore: Dev 서버 Down 오류 해결
  backend/src/main/resources/application-dev.yml
  backend/src/main/resources/application-local.yml
  backend/src/main/resources/application-prod.yml
  backend/src/main/resources/schema.sql
Labels: BE, BUG, INFRA

#460 refactor: debug, release 모드에 따른 BASE_URL 분기처리
  .github/workflows/android-cd-dev.yml
  .github/workflows/android-ci-dev.yml
  android/app/build.gradle.kts
  android/app/src/main/java/com/mulberry/ody/data/remote/core/RetrofitClient.kt
Labels: AN, REFACTOR

#519 fix: dev 서버 약속 생성 불가
  backend/src/main/resources/application.yml
Labels: BE, BUG

#516 design: 기본적으로 보여주던 수도권 안내 멘트 삭제
  android/app/src/main/res/layout/activity_meeting_join.xml
  android/app/src/main/res/layout/fragment_meeting_destination.xml
Labels: AN, DESIGN

#509 refactor: 출발 알림이 아닌 type들의 초기 상태를 DONE으로 변경
  backend/src/main/java/com/ody/notification/domain/Notification.java
  backend/src/main/java/com/ody/notification/domain/NotificationType.java
  backend/src/main/java/com/ody/notification/service/FcmPushSender.java
  backend/src/test/java/com/ody/notification/service/NotificationServiceTest.java
Labels: BE, REFACTOR

#507 refactor: 초대코대 코드 유일성 높이도록 개선
  backend/src/main/java/com/ody/meeting/controller/MeetingController.java
  backend/src/main/java/com/ody/meeting/domain/Meeting.java
  backend/src/main/java/com/ody/meeting/repository/MeetingRepository.java
  backend/src/main/java/com/ody/meeting/service/MeetingService.java
  backend/src/main/java/com/ody/util/InviteCodeGenerator.java
  backend/src/main/resources/application-dev.yml
  backend/src/main/resources/schema.sql
  backend/src/test/java/com/ody/common/Fixture.java
  backend/src/test/java/com/ody/mate/service/MateServiceTest.java
  backend/src/test/java/com/ody/meeting/repository/MeetingRepositoryTest.java
  backend/src/test/java/com/ody/meeting/service/MeetingServiceTest.java
  backend/src/test/java/com/ody/util/InviteCodeGeneratorTest.java
Labels: BE, REFACTOR

#511 refactor: 민감한 설정을 jasypt를 활용해 암호화 적용
  .github/workflows/backend-cd-dev.yml
  .github/workflows/backend-cd-prod.yml
  .github/workflows/backend-ci-dev.yml
  .github/workflows/backend-ci-prod.yml
  backend/Dockerfile
  backend/build.gradle
  backend/src/main/java/com/ody/common/config/JasyptConfig.java
  backend/src/main/java/com/ody/notification/config/FcmConfig.java
  backend/src/main/resources/application-dev.yml
  backend/src/main/resources/application-prod.yml
  backend/src/main/resources/application.yml
  backend/src/main/resources/common.yml
  backend/src/test/java/com/ody/common/BaseControllerTest.java
  backend/src/test/java/com/ody/util/InviteCodeGeneratorTest.java
Labels: BE, REFACTOR

#504 chore: logging 향상을 위한 MDC 도입
  backend/src/main/java/com/ody/common/filter/LoggingFilter.java
  backend/src/main/java/com/ody/eta/domain/EtaStatus.java
  backend/src/main/resources/logback-spring.xml
Labels: BE, INFRA

#512 feat: 회원 삭제 API
  backend/src/main/java/com/ody/eta/domain/Eta.java
  backend/src/main/java/com/ody/eta/service/EtaService.java
  backend/src/main/java/com/ody/mate/domain/Mate.java
  backend/src/main/java/com/ody/mate/repository/MateRepository.java
  backend/src/main/java/com/ody/mate/service/MateService.java
  backend/src/main/java/com/ody/meeting/controller/MeetingController.java
  backend/src/main/java/com/ody/member/controller/MemberController.java
  backend/src/main/java/com/ody/member/controller/MemberControllerSwagger.java
  backend/src/main/java/com/ody/member/domain/Member.java
  backend/src/main/java/com/ody/member/service/MemberService.java
  backend/src/main/java/com/ody/notification/domain/Notification.java
  backend/src/main/java/com/ody/notification/domain/NotificationStatus.java
  backend/src/main/java/com/ody/notification/domain/NotificationType.java
  backend/src/main/java/com/ody/notification/dto/response/NotiLogFindResponse.java
  backend/src/main/java/com/ody/notification/dto/response/NotiLogFindResponses.java
  backend/src/main/java/com/ody/notification/repository/NotificationRepository.java
  backend/src/main/java/com/ody/notification/service/FcmPushSender.java
  backend/src/main/java/com/ody/notification/service/NotificationService.java
  backend/src/main/resources/schema.sql
  backend/src/test/java/com/ody/auth/controller/AuthControllerTest.java
  backend/src/test/java/com/ody/common/BaseRepositoryTest.java
  backend/src/test/java/com/ody/common/BaseServiceTest.java
  backend/src/test/java/com/ody/common/DatabaseCleaner.java
  backend/src/test/java/com/ody/common/FixtureGenerator.java
  backend/src/test/java/com/ody/common/FixtureGeneratorConfig.java
  backend/src/test/java/com/ody/eta/domain/EtaTest.java
  backend/src/test/java/com/ody/eta/repository/EtaRepositoryTest.java
  backend/src/test/java/com/ody/mate/repository/MateRepositoryTest.java
  backend/src/test/java/com/ody/mate/service/MateServiceTest.java
  backend/src/test/java/com/ody/meeting/repository/MeetingRepositoryTest.java
  backend/src/test/java/com/ody/meeting/service/MeetingServiceTest.java
  backend/src/test/java/com/ody/member/controller/MemberControllerTest.java
  backend/src/test/java/com/ody/member/repository/MemberRepositoryTest.java
  backend/src/test/java/com/ody/member/service/MemberServiceTest.java
  backend/src/test/java/com/ody/notification/repository/NotificationRepositoryTest.java
  backend/src/test/java/com/ody/notification/service/NotificationServiceTest.java
Labels: BE, FEATURE

#527 fix: jasypt 비밀번호 못 읽는 문제 해결
  backend/Dockerfile
  backend/src/main/resources/common.yml
Labels: BE, REFACTOR

#530 fix: 도커에 전달된 환경변수를 애플케이션이 못 읽는 문제 해결
  .github/workflows/backend-cd-dev.yml
  backend/Dockerfile
  backend/src/main/resources/common.yml
Labels: BE, BUG, INFRA

#534 fix: 회원 삭제 구현 후 로그 목록 조회 API 오작동
  backend/src/main/java/com/ody/common/aop/DeletedFilterAspect.java
  backend/src/main/java/com/ody/common/aop/DisabledDeletedFilter.java
  backend/src/main/java/com/ody/mate/domain/Mate.java
  backend/src/main/java/com/ody/member/domain/Member.java
  backend/src/main/java/com/ody/member/service/MemberService.java
  backend/src/main/java/com/ody/notification/dto/response/NotiLogFindResponse.java
  backend/src/main/java/com/ody/notification/service/NotificationService.java
  backend/src/test/java/com/ody/mate/repository/MateRepositoryTest.java
  backend/src/test/java/com/ody/member/repository/MemberRepositoryTest.java
  backend/src/test/java/com/ody/member/service/MemberServiceTest.java
  backend/src/test/java/com/ody/notification/service/NotificationServiceTest.java
Labels: BE, BUG

#518 feat: 회원 탈퇴 기능 구현
  android/app/proguard-rules.pro
  android/app/src/main/java/com/mulberry/ody/OdyApplication.kt
  android/app/src/main/java/com/mulberry/ody/data/local/db/OdyDatastore.kt
  android/app/src/main/java/com/mulberry/ody/data/remote/core/entity/notification/mapper/NotificationLogsResponseMapper.kt
  android/app/src/main/java/com/mulberry/ody/data/remote/core/service/MemberService.kt
  android/app/src/main/java/com/mulberry/ody/data/remote/thirdparty/login/kakao/KakaoLoginRepository.kt
  android/app/src/main/java/com/mulberry/ody/domain/model/LogType.kt
  android/app/src/main/java/com/mulberry/ody/domain/model/NotificationLog.kt
  android/app/src/main/java/com/mulberry/ody/presentation/common/CommonBindingAdapter.kt
  android/app/src/main/java/com/mulberry/ody/presentation/login/LoginActivity.kt
  android/app/src/main/java/com/mulberry/ody/presentation/login/LoginViewModel.kt
  android/app/src/main/java/com/mulberry/ody/presentation/login/LoginViewModelFactory.kt
  android/app/src/main/java/com/mulberry/ody/presentation/room/log/NotificationLogBindingAdapter.kt
  android/app/src/main/java/com/mulberry/ody/presentation/room/log/model/NotificationLogUiModel.kt
  android/app/src/main/java/com/mulberry/ody/presentation/setting/SettingActivity.kt
  android/app/src/main/java/com/mulberry/ody/presentation/setting/SettingViewModel.kt
  android/app/src/main/java/com/mulberry/ody/presentation/setting/SettingViewModelFactory.kt
  android/app/src/main/java/com/mulberry/ody/presentation/setting/withdrawal/WithDrawalDialog.kt
  android/app/src/main/res/layout/dialog_withdrawal.xml
  android/app/src/main/res/layout/item_mate.xml
  android/app/src/main/res/layout/item_notification_log.xml
  android/app/src/main/res/layout/item_setting.xml
  android/app/src/main/res/values/strings.xml
  android/app/src/test/java/com/mulberry/ody/TestFixtures.kt
Labels: AN, FEATURE

#539 feat: 카카오 연결끊기
  backend/src/main/java/com/ody/auth/config/KakaoConfig.java
  backend/src/main/java/com/ody/auth/config/KakaoProperties.java
  backend/src/main/java/com/ody/auth/service/KakaoAuthUnlinkClient.java
  backend/src/main/java/com/ody/auth/service/KakaoAuthUnlinkClientErrorHandler.java
  backend/src/main/java/com/ody/auth/service/SocialAuthUnlinkClient.java
  backend/src/main/java/com/ody/mate/domain/Mate.java
  backend/src/main/java/com/ody/member/controller/MemberController.java
  backend/src/main/java/com/ody/member/controller/MemberControllerSwagger.java
  backend/src/main/java/com/ody/member/domain/DeviceToken.java
  backend/src/main/java/com/ody/member/domain/Member.java
  backend/src/main/java/com/ody/member/service/MemberService.java
  backend/src/main/java/com/ody/notification/dto/response/NotiLogFindResponse.java
  backend/src/main/resources/common.yml
  backend/src/main/resources/schema.sql
  backend/src/test/java/com/ody/auth/service/KakaoAuthUnlinkClientTest.java
  backend/src/test/java/com/ody/member/controller/MemberControllerTest.java
  backend/src/test/java/com/ody/member/repository/MemberRepositoryTest.java
  backend/src/test/java/com/ody/member/service/MemberServiceTest.java
  backend/src/test/java/com/ody/notification/service/NotificationServiceTest.java
Labels: BE, FEATURE

#549 fix: Dev 서버 Swagger 접속 에러 해결
  .github/workflows/backend-cd-dev.yml
  backend/src/main/java/com/ody/notification/repository/NotificationRepository.java
Labels: BE, BUG, INFRA

#540 refactor: Nickname 객체 로직 정리
  backend/src/main/java/com/ody/auth/dto/request/AuthRequest.java
  backend/src/main/java/com/ody/eta/dto/response/MateEtaResponse.java
  backend/src/main/java/com/ody/mate/domain/Mate.java
  backend/src/main/java/com/ody/mate/domain/Nickname.java
  backend/src/main/java/com/ody/mate/dto/response/MateResponse.java
  backend/src/main/java/com/ody/meeting/dto/response/MateEtaResponseV2.java
  backend/src/main/java/com/ody/member/domain/Member.java
  backend/src/main/java/com/ody/notification/domain/message/DirectMessage.java
  backend/src/main/java/com/ody/notification/domain/message/GroupMessage.java
  backend/src/test/java/com/ody/auth/controller/AuthControllerTest.java
  backend/src/test/java/com/ody/auth/service/AuthServiceTest.java
  backend/src/test/java/com/ody/common/Fixture.java
  backend/src/test/java/com/ody/common/FixtureGenerator.java
  backend/src/test/java/com/ody/meeting/service/MeetingServiceTest.java
  backend/src/test/java/com/ody/member/repository/MemberRepositoryTest.java
  backend/src/test/java/com/ody/member/service/MemberServiceTest.java
Labels: BE, REFACTOR

#558 fix: Nickname 객체 로직 정리 merge conflict 발생
  backend/src/main/java/com/ody/member/service/MemberService.java
  backend/src/main/java/com/ody/notification/dto/response/NotiLogFindResponse.java
Labels: BE, BUG

#559 fix: Odsay API 요청 정지 복구
  backend/src/main/java/com/ody/route/config/RouteProperties.java
  backend/src/main/resources/common.yml
Labels: BE, BUG

#548 design: 재촉하기 버튼 가이드 화면 구현
  android/app/src/main/java/com/mulberry/ody/data/local/db/OdyDatastore.kt
  android/app/src/main/java/com/mulberry/ody/presentation/room/etadashboard/EtaDashboardBindingAdapter.kt
  android/app/src/main/java/com/mulberry/ody/presentation/room/etadashboard/EtaDashboardFragment.kt
  android/app/src/main/java/com/mulberry/ody/presentation/room/etadashboard/EtaDashboardGuideFirstFragment.kt
  android/app/src/main/java/com/mulberry/ody/presentation/room/etadashboard/EtaDashboardGuideSecondFragment.kt
  android/app/src/main/res/drawable/ic_arrow_right.xml
  android/app/src/main/res/drawable/ic_close.xml
  android/app/src/main/res/drawable/ic_diagonal_line.xml
  android/app/src/main/res/layout/fragment_eta_dashboard.xml
  android/app/src/main/res/layout/fragment_eta_dashboard_guide_first.xml
  android/app/src/main/res/layout/fragment_eta_dashboard_guide_second.xml
  android/app/src/main/res/layout/item_eta_dashboard.xml
  android/app/src/main/res/values/colors.xml
  android/app/src/main/res/values/strings.xml
Labels: AN, DESIGN

#568 refactor: 회원 탈퇴 시 카카오 api 호출 제거
  android/app/src/main/java/com/mulberry/ody/data/remote/thirdparty/login/kakao/KakaoLoginRepository.kt
Labels: AN, REFACTOR

#573 fix: odsay 호출 문제 해결
  backend/src/main/java/com/ody/mate/service/MateService.java
Labels: BE, BUG

#572 feat: 푸시 메세지를 클릭했을 때 앱 내로 접속
  android/app/src/main/java/com/mulberry/ody/data/remote/thirdparty/fcm/service/FCMService.kt
  android/app/src/main/java/com/mulberry/ody/domain/model/NotificationType.kt
  android/app/src/main/java/com/mulberry/ody/presentation/notification/NotificationHelper.kt
  android/app/src/main/res/values/strings.xml
Labels: AN, FEATURE

#555 refactor: 소요시간 계산 외부 api 의존성 낮추기
  backend/src/main/java/com/ody/route/config/RouteConfig.java
  backend/src/main/java/com/ody/route/dto/DistanceMatrixElementStatus.java
  backend/src/main/java/com/ody/route/dto/DistanceMatrixResponse.java
  backend/src/main/java/com/ody/route/dto/DistanceMatrixStatus.java
  backend/src/main/java/com/ody/route/service/GoogleRouteClient.java
  backend/src/main/java/com/ody/route/service/RouteService.java
  backend/src/main/resources/common.yml
  backend/src/test/java/com/ody/common/BaseRouteClientTest.java
  backend/src/test/java/com/ody/common/TestRouteConfig.java
  backend/src/test/java/com/ody/route/service/GoogleRouteClientTest.java
  backend/src/test/java/com/ody/route/service/OdsayRouteClientTest.java
  backend/src/test/java/com/ody/route/service/RouteServiceTest.java
  backend/src/test/java/com/ody/route/service/StubGoogleRouteClient.java
  backend/src/test/java/com/ody/route/service/StubOdsayRouteClient.java
  backend/src/test/resources/application.yml
Labels: BE, REFACTOR

#578 fix: hilt 적용된 뒤 초대하기, 리프래시 토큰 안되는 버그
  android/app/src/main/java/com/mulberry/ody/di/ActivityModule.kt
  android/app/src/main/java/com/mulberry/ody/di/AppModule.kt
  android/app/src/main/java/com/mulberry/ody/di/ServiceModule.kt
Labels: AN, BUG

#577 chore: Flyway로 데이터베이스 마이그레이션
  backend/build.gradle
  backend/src/main/resources/application-dev.yml
  backend/src/main/resources/application-local.yml
  backend/src/main/resources/application-prod.yml
  backend/src/main/resources/db/migration/V1__init.sql
Labels: BE, INFRA

#564 chore: AWS 로드밸런서 적용
  .github/workflows/backend-cd-prod.yml
  backend/build.gradle
Labels: BE, INFRA

#574 chore: prod DB를 RDS 클러스터로 변경
  backend/src/main/java/com/ody/common/config/ReplicationDataSourceConfig.java
  backend/src/main/java/com/ody/common/config/ReplicationDataSourceRouter.java
  backend/src/main/java/com/ody/common/config/ReplicationType.java
  backend/src/main/resources/application-prod.yml
  backend/src/main/resources/common.yml
Labels: BE, INFRA

#580 refactor: 주소 검색 다이얼로그를 상호명으로 검색할 수 있는 api로 변경
  android/app/proguard-rules.pro
  android/app/src/main/assets/address.html
  android/app/src/main/java/com/mulberry/ody/data/remote/thirdparty/address/KakaoAddressRepository.kt
  android/app/src/main/java/com/mulberry/ody/data/remote/thirdparty/address/KakaoAddressService.kt
  android/app/src/main/java/com/mulberry/ody/data/remote/thirdparty/address/response/AddressResponse.kt
  android/app/src/main/java/com/mulberry/ody/data/remote/thirdparty/address/response/AddressResponseMapper.kt
  android/app/src/main/java/com/mulberry/ody/data/remote/thirdparty/address/response/Document.kt
  android/app/src/main/java/com/mulberry/ody/data/remote/thirdparty/address/response/Meta.kt
  android/app/src/main/java/com/mulberry/ody/data/remote/thirdparty/address/response/SameName.kt
  android/app/src/main/java/com/mulberry/ody/data/remote/thirdparty/location/KakaoRetrofitClient.kt
  android/app/src/main/java/com/mulberry/ody/data/remote/thirdparty/location/entity/response/Address.kt
  android/app/src/main/java/com/mulberry/ody/data/remote/thirdparty/location/entity/response/Document.kt
  android/app/src/main/java/com/mulberry/ody/data/remote/thirdparty/location/entity/response/LocationResponseMapper.kt
  android/app/src/main/java/com/mulberry/ody/data/remote/thirdparty/location/entity/response/LocationSearchResponse.kt
  android/app/src/main/java/com/mulberry/ody/data/remote/thirdparty/location/entity/response/Meta.kt
  android/app/src/main/java/com/mulberry/ody/data/remote/thirdparty/location/entity/response/RoadAddress.kt
  android/app/src/main/java/com/mulberry/ody/data/remote/thirdparty/location/repository/KakaoGeoLocationRepository.kt
  android/app/src/main/java/com/mulberry/ody/data/remote/thirdparty/location/service/KakaoLocationService.kt
  android/app/src/main/java/com/mulberry/ody/di/RepositoryModule.kt
  android/app/src/main/java/com/mulberry/ody/di/ServiceModule.kt
  android/app/src/main/java/com/mulberry/ody/domain/model/Address.kt
  android/app/src/main/java/com/mulberry/ody/domain/repository/location/AddressRepository.kt
  android/app/src/main/java/com/mulberry/ody/domain/repository/location/GeoLocationRepository.kt
  android/app/src/main/java/com/mulberry/ody/presentation/address/AddressSearchDialog.kt
  android/app/src/main/java/com/mulberry/ody/presentation/address/AddressSearchFragment.kt
  android/app/src/main/java/com/mulberry/ody/presentation/address/AddressSearchViewModel.kt
  android/app/src/main/java/com/mulberry/ody/presentation/address/adapter/AddressesAdapter.kt
  android/app/src/main/java/com/mulberry/ody/presentation/address/listener/AddressListener.kt
  android/app/src/main/java/com/mulberry/ody/presentation/address/listener/AddressReceiveListener.kt
  android/app/src/main/java/com/mulberry/ody/presentation/address/listener/AddressSearchListener.kt
  android/app/src/main/java/com/mulberry/ody/presentation/address/listener/AddressViewHolder.kt
  android/app/src/main/java/com/mulberry/ody/presentation/address/model/AddressUiModel.kt
  android/app/src/main/java/com/mulberry/ody/presentation/address/model/AddressUiModelMapper.kt
  android/app/src/main/java/com/mulberry/ody/presentation/address/web/AddressSearchInterface.kt
  android/app/src/main/java/com/mulberry/ody/presentation/address/web/LocalContentWebViewClient.kt
  android/app/src/main/java/com/mulberry/ody/presentation/common/binding/BindingFragment.kt
  android/app/src/main/java/com/mulberry/ody/presentation/creation/MeetingCreationActivity.kt
  android/app/src/main/java/com/mulberry/ody/presentation/creation/MeetingCreationViewModel.kt
  android/app/src/main/java/com/mulberry/ody/presentation/creation/destination/MeetingDestinationFragment.kt
  android/app/src/main/java/com/mulberry/ody/presentation/join/MeetingJoinActivity.kt
  android/app/src/main/java/com/mulberry/ody/presentation/join/MeetingJoinViewModel.kt
  android/app/src/main/res/layout/activity_meeting_creation.xml
  android/app/src/main/res/layout/activity_meeting_join.xml
  android/app/src/main/res/layout/dialog_address_search.xml
  android/app/src/main/res/layout/fragment_address_search.xml
  android/app/src/main/res/layout/fragment_meeting_destination.xml
  android/app/src/main/res/layout/item_address_search.xml
  android/app/src/main/res/layout/toolbar_address_search.xml
  android/app/src/main/res/values/strings.xml
  android/app/src/test/java/com/mulberry/ody/TestFixtures.kt
  android/app/src/test/java/com/mulberry/ody/fake/FakeAddressRepository.kt
  android/app/src/test/java/com/mulberry/ody/fake/FakeGeoLocationRepository.kt
  android/app/src/test/java/com/mulberry/ody/presentation/address/AddressSearchViewModelTest.kt
  android/app/src/test/java/com/mulberry/ody/presentation/creation/MeetingCreationViewModelTest.kt
  android/app/src/test/java/com/mulberry/ody/presentation/join/MeetingJoinViewModelTest.kt
Labels: AN, REFACTOR

#585 chore: 병합 충돌로 인한 CI 깨짐 해결
  backend/src/main/resources/db/migration/V2__alter_notification_type_check.sql
Labels: BE, BUG

#592 hotfix: READ / WRITE DB 연결 조건 수정
  backend/src/main/java/com/ody/common/config/ReplicationType.java
Labels: BE, BUG

#589 feat: 주소 검색할 때 디폴트 현재 위치 제공
  android/app/proguard-rules.pro
  android/app/src/main/java/com/mulberry/ody/data/remote/thirdparty/address/KakaoAddressRepository.kt
  android/app/src/main/java/com/mulberry/ody/data/remote/thirdparty/address/KakaoAddressService.kt
  android/app/src/main/java/com/mulberry/ody/data/remote/thirdparty/address/response/coord/Address.kt
  android/app/src/main/java/com/mulberry/ody/data/remote/thirdparty/address/response/coord/AddressByCoordResponse.kt
  android/app/src/main/java/com/mulberry/ody/data/remote/thirdparty/address/response/coord/Document.kt
  android/app/src/main/java/com/mulberry/ody/data/remote/thirdparty/address/response/coord/Meta.kt
  android/app/src/main/java/com/mulberry/ody/data/remote/thirdparty/address/response/coord/RoadAddress.kt
  android/app/src/main/java/com/mulberry/ody/domain/model/Address.kt
  android/app/src/main/java/com/mulberry/ody/domain/repository/location/AddressRepository.kt
  android/app/src/main/java/com/mulberry/ody/presentation/join/MeetingJoinActivity.kt
  android/app/src/main/java/com/mulberry/ody/presentation/join/MeetingJoinViewModel.kt
  android/app/src/test/java/com/mulberry/ody/fake/FakeAddressRepository.kt
  android/app/src/test/java/com/mulberry/ody/presentation/join/MeetingJoinViewModelTest.kt
Labels: AN, FEATURE

#594 design: 대중교통 멘트 추가
  android/app/src/main/res/layout/item_meeting_catalog.xml
  android/app/src/main/res/values/strings.xml
Labels: AN, DESIGN

#586 refactor: 백그라운드 스케줄링 리팩터링
  android/app/src/main/java/com/mulberry/ody/OdyApplication.kt
  android/app/src/main/java/com/mulberry/ody/data/local/db/OdyDatastore.kt
  android/app/src/main/java/com/mulberry/ody/data/local/repository/DefaultMatesEtaRepository.kt
  android/app/src/main/java/com/mulberry/ody/data/local/service/EtaDashboardWorker.kt
  android/app/src/main/java/com/mulberry/ody/domain/repository/ody/MatesEtaRepository.kt
  android/app/src/main/java/com/mulberry/ody/presentation/join/MeetingJoinViewModel.kt
  android/app/src/test/java/com/mulberry/ody/fake/FakeMatesEtaRepository.kt
Labels: AN, REFACTOR

#596 refactor: 회원 탈퇴 시 예약된 스케줄링 모두 삭제
  android/app/src/main/java/com/mulberry/ody/data/local/repository/DefaultMatesEtaRepository.kt
  android/app/src/main/java/com/mulberry/ody/domain/repository/ody/MatesEtaRepository.kt
  android/app/src/main/java/com/mulberry/ody/presentation/setting/SettingViewModel.kt
  android/app/src/test/java/com/mulberry/ody/fake/FakeMatesEtaRepository.kt
Labels: AN, REFACTOR

#600 fix: gps Location이 null이 나오는 버그 수정
  android/app/src/main/java/com/mulberry/ody/data/local/service/EtaDashboardWorker.kt
Labels: AN, BUG

#605 hotfix: 입장, ETA 공지 알림 오지 않는 문제 해결
  backend/src/main/java/com/ody/meeting/service/MeetingService.java
  backend/src/main/java/com/ody/notification/domain/Notification.java
  backend/src/main/java/com/ody/notification/service/FcmPushSender.java
  backend/src/main/java/com/ody/notification/service/NotificationService.java
Labels: BE, BUG

#603 design: RecyclerView overScrollMode 속성 변경
  android/app/src/main/res/layout/activity_meetings.xml
  android/app/src/main/res/layout/activity_setting.xml
  android/app/src/main/res/layout/fragment_address_search.xml
  android/app/src/main/res/layout/fragment_eta_dashboard.xml
  android/app/src/main/res/layout/fragment_notification_log.xml
Labels: AN, DESIGN

#598 hotfix: 약속 이름에 이모지 입력 시 약속 개설 안 됨
  backend/src/main/java/com/ody/common/config/FlywayConfig.java
  backend/src/main/resources/application-dev.yml
  backend/src/main/resources/application-local.yml
  backend/src/main/resources/application-prod.yml
  backend/src/main/resources/common.yml
  backend/src/main/resources/db/migration/V3__alter_character_set.sql
  backend/src/test/resources/application.yml
Labels: BE, BUG

#611 hotfix: 약속방 로그가 뜨지 않는 문제 해결
  backend/src/main/java/com/ody/notification/repository/NotificationRepository.java
  backend/src/main/java/com/ody/notification/service/NotificationService.java
  backend/src/test/java/com/ody/notification/repository/NotificationRepositoryTest.java
Labels: BE, BUG

#610 fix: ETA 공지 알림 오지 않는 문제 해결
  backend/src/main/java/com/ody/notification/domain/FcmTopic.java
Labels: BE, BUG

#612 hotfix: DB health check 하지 않도록 수정
  backend/src/main/resources/common.yml
Labels: BE, INFRA

#613 hotfix: odsay api key 오류 해결
  backend/src/main/resources/common.yml
Labels: BE, BUG

#616 hotfix: character set 변경 SQL syntax 에러
  backend/src/main/resources/db/migration/V3__alter_character_set.sql
Labels: BE, BUG

#617 hotfix: OSIV false 설정으로 인한 스케줄링 메서드 트랜잭션 선언
  backend/build.gradle
  backend/src/main/java/com/ody/notification/service/NotificationService.java
Labels: BE, BUG

#621 bugfix: READ, WRITE DB 선택 로그
  backend/src/main/java/com/ody/common/config/ReplicationDataSourceRouter.java
Labels: BE, BUG

#619 fix: eta 목록 화면 불안정한 문제 수정
  android/app/build.gradle.kts
  android/app/src/main/java/com/mulberry/ody/data/local/db/MateEtaInfoDao.kt
  android/app/src/main/java/com/mulberry/ody/data/local/db/OdyDatabase.kt
  android/app/src/main/java/com/mulberry/ody/data/local/entity/eta/MateEtaInfoEntity.kt
  android/app/src/main/java/com/mulberry/ody/data/local/entity/eta/MateEtaListTypeConverter.kt
  android/app/src/main/java/com/mulberry/ody/data/local/repository/DefaultMatesEtaRepository.kt
  android/app/src/main/java/com/mulberry/ody/data/local/service/EtaDashboardWorker.kt
  android/app/src/main/java/com/mulberry/ody/di/DBModule.kt
  android/app/src/main/java/com/mulberry/ody/domain/model/MateEtaInfo.kt
  android/app/src/main/java/com/mulberry/ody/domain/repository/ody/MatesEtaRepository.kt
  android/app/src/main/java/com/mulberry/ody/presentation/setting/SettingViewModel.kt
  android/app/src/test/java/com/mulberry/ody/fake/FakeMatesEtaRepository.kt
  android/gradle/libs.versions.toml
Labels: AN, BUG, REFACTOR

#626 chore: 안드로이드 cd 배포 위치 테스트 트랙에서 프로덕션 트랙으로 변경
  .github/workflows/android-cd-dev.yml
Labels: AN, INFRA
