Repository woowacourse-teams/2024-ody, pull requests merged in 2024-07, with the labels that each got.

#3 docs: 모임 개설 API 문서화
  .idea/.gitignore
  .idea/2024-ody.iml
  .idea/misc.xml
  .idea/modules.xml
  .idea/vcs.xml
  backend/.gitignore
  backend/build.gradle
  backend/gradle/wrapper/gradle-wrapper.jar
  backend/gradle/wrapper/gradle-wrapper.properties
  backend/gradlew
  backend/gradlew.bat
  backend/settings.gradle
  backend/src/main/java/com/ody/BackendApplication.java
  backend/src/main/java/com/ody/meeting/controller/MeetingController.java
  backend/src/main/java/com/ody/meeting/controller/MeetingControllerSwagger.java
  backend/src/main/java/com/ody/meeting/dto/MateResponse.java
  backend/src/main/java/com/ody/meeting/dto/MeetingRequest.java
  backend/src/main/java/com/ody/meeting/dto/MeetingResponse.java
  backend/src/main/java/com/ody/swagger/annotation/ErrorCode400.java
  backend/src/main/java/com/ody/swagger/annotation/ErrorCode401.java
  backend/src/main/java/com/ody/swagger/annotation/ErrorCode500.java
  backend/src/main/java/com/ody/swagger/config/SwaggerConfig.java
  backend/src/main/resources/application.yml
Labels: BE, DOCS

#6 docs: 모임 개설 API 문서 가독성 개선
  backend/src/main/java/com/ody/meeting/dto/MeetingRequest.java
  backend/src/main/java/com/ody/meeting/dto/MeetingResponse.java
Labels: DOCS

#8 feat: 엔티티 구현
  backend/src/main/java/com/ody/common/domain/BaseEntity.java
  backend/src/main/java/com/ody/mate/domain/Mate.java
  backend/src/main/java/com/ody/meeting/domain/Location.java
  backend/src/main/java/com/ody/meeting/domain/Meeting.java
  backend/src/main/java/com/ody/member/domain/Member.java
  backend/src/main/java/com/ody/notification/domain/Notification.java
  backend/src/main/java/com/ody/notification/domain/NotificationType.java
Labels: BE, FEATURE

#15 feat: 안드로이드 기초세팅
  android/.gitignore
  android/app/.gitignore
  android/app/build.gradle.kts
  android/app/proguard-rules.pro
  android/app/src/androidTest/java/com/woowacourse/ody/.gitkeep
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/java/com/woowacourse/ody/Application.kt
  android/app/src/main/java/com/woowacourse/ody/data/local/.gitkeep
  android/app/src/main/java/com/woowacourse/ody/data/remote/RetrofitClient.kt
  android/app/src/main/java/com/woowacourse/ody/domain/.gitkeep
  android/app/src/main/java/com/woowacourse/ody/presentation/IntroActivity.kt
  android/app/src/main/res/drawable/ic_launcher_background.xml
  android/app/src/main/res/drawable/ic_launcher_foreground.xml
  android/app/src/main/res/font/font.xml
  android/app/src/main/res/font/pretendard_bold.ttf
  android/app/src/main/res/font/pretendard_medium.ttf
  android/app/src/main/res/font/pretendard_regular.ttf
  android/app/src/main/res/layout/activity_main.xml
  android/app/src/main/res/mipmap-anydpi/ic_launcher.xml
  android/app/src/main/res/mipmap-anydpi/ic_launcher_round.xml
  android/app/src/main/res/mipmap-hdpi/ic_launcher.webp
  android/app/src/main/res/mipmap-hdpi/ic_launcher_round.webp
  android/app/src/main/res/mipmap-mdpi/ic_launcher.webp
  android/app/src/main/res/mipmap-mdpi/ic_launcher_round.webp
  android/app/src/main/res/mipmap-xhdpi/ic_launcher.webp
  android/app/src/main/res/mipmap-xhdpi/ic_launcher_round.webp
  android/app/src/main/res/mipmap-xxhdpi/ic_launcher.webp
  android/app/src/main/res/mipmap-xxhdpi/ic_launcher_round.webp
  android/app/src/main/res/mipmap-xxxhdpi/ic_launcher.webp
  android/app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.webp
  android/app/src/main/res/values-night/themes.xml
  android/app/src/main/res/values/colors.xml
  android/app/src/main/res/values/dimens.xml
  android/app/src/main/res/values/strings.xml
  android/app/src/main/res/values/styles.xml
  android/app/src/main/res/values/themes.xml
  android/app/src/main/res/xml/backup_rules.xml
  android/app/src/main/res/xml/data_extraction_rules.xml
  android/app/src/test/java/com/woowacourse/ody/ExampleUnitTest.kt
  android/build.gradle.kts
  android/gradle.properties
  android/gradle/libs.versions.toml
  android/gradle/wrapper/gradle-wrapper.jar
  android/gradle/wrapper/gradle-wrapper.properties
  android/gradlew
  android/gradlew.bat
  android/settings.gradle.kts
Labels: AN, FEATURE

#17 docs: 참여중인 모임 목록 조회 API 문서화
  backend/src/main/java/com/ody/mate/domain/controller/MateController.java
  backend/src/main/java/com/ody/mate/domain/controller/MateControllerSwagger.java
  backend/src/main/java/com/ody/meeting/controller/MeetingController.java
  backend/src/main/java/com/ody/meeting/controller/MeetingControllerSwagger.java
  backend/src/main/java/com/ody/meeting/dto/request/MeetingSaveRequest.java
  backend/src/main/java/com/ody/meeting/dto/response/MateResponse.java
  backend/src/main/java/com/ody/meeting/dto/response/MeetingSaveResponse.java
  backend/src/main/java/com/ody/meeting/dto/response/MeetingSaveResponses.java
Labels: BE, DOCS

#16 docs: FCM 토큰 저장, 초대 코드 유효성 검사 API 문서화
  backend/src/main/java/com/ody/meeting/controller/MeetingController.java
  backend/src/main/java/com/ody/meeting/controller/MeetingControllerSwagger.java
  backend/src/main/java/com/ody/member/controller/MemberController.java
  backend/src/main/java/com/ody/member/controller/MemberControllerSwagger.java
Labels: BE, DOCS

#14 docs: 로그 목록 API 문서화
  backend/src/main/java/com/ody/notification/controller/NotificationController.java
  backend/src/main/java/com/ody/notification/controller/NotificationControllerSwagger.java
  backend/src/main/java/com/ody/notification/dto/request/NotificationSaveResponse.java
  backend/src/main/java/com/ody/notification/dto/response/NotiLogFindResponse.java
Labels: BE, DOCS

#42 chore: backend ci 스크립트 작성
  .github/workflows/backend-ci-dev.yml
Labels: BE, INFRA

#41 feat: 스플래쉬 화면 구현
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/java/com/woowacourse/ody/presentation/IntroActivity.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/splash/SplashActivity.kt
  android/app/src/main/res/drawable-hdpi/img_ody_logo.png
  android/app/src/main/res/drawable-mdpi/img_ody_logo.png
  android/app/src/main/res/drawable-xhdpi/img_ody_logo.png
  android/app/src/main/res/drawable-xxhdpi/img_ody_logo.png
  android/app/src/main/res/drawable-xxxhdpi/img_ody_logo.png
  android/app/src/main/res/layout/activity_splash.xml
  android/app/src/main/res/values-night/themes.xml
  android/app/src/main/res/values/themes.xml
Labels: AN, FEATURE

#40 feat: 공통 컴포넌트 구현
  android/app/src/main/res/drawable/ic_arrow_back.xml
  android/app/src/main/res/drawable/ic_share.xml
  android/app/src/main/res/drawable/rectangle_edit_text.xml
  android/app/src/main/res/drawable/selector_bottom_button.xml
  android/app/src/main/res/layout/toolbar_back.xml
  android/app/src/main/res/layout/toolbar_intro.xml
  android/app/src/main/res/layout/toolbar_log.xml
  android/app/src/main/res/values/colors.xml
  android/app/src/main/res/values/strings.xml
  android/app/src/main/res/values/styles.xml
Labels: AN, FEATURE

#45 feat: Status바 추가
  android/app/src/main/res/values-night/themes.xml
  android/app/src/main/res/values/themes.xml
Labels: AN, FEATURE

#48 chore: backend ci 스크립트 작성
  .github/workflows/backend-cicd-dev.yml
  backend/Dockerfile
Labels: BE, INFRA

#47 feat: 주소 검색 화면 구현
  android/app/build.gradle.kts
  android/app/src/main/java/com/woowacourse/ody/OdyApplication.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/address/AddressSearchDialog.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/destination/DestinationFragment.kt
  android/app/src/main/res/layout/dialog_address_search.xml
  android/app/src/main/res/layout/fragment_destination.xml
  android/app/src/main/res/values/colors.xml
  android/app/src/main/res/values/dimens.xml
  android/app/src/main/res/values/strings.xml
Labels: AN, FEATURE

#50 feat: Timber에 DebugTree 추가
  android/app/build.gradle.kts
  android/app/src/main/java/com/woowacourse/ody/OdyApplication.kt
Labels: AN, FEATURE

#54 chore: android ci 구축
  .github/workflows/android-ci-dev.yml
Labels: AN, INFRA

#52 feat: FCM 구현
  .idea/misc.xml
  android/app/build.gradle.kts
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/java/com/woowacourse/ody/OdyApplication.kt
  android/app/src/main/java/com/woowacourse/ody/data/local/FCMService.kt
  android/app/src/main/java/com/woowacourse/ody/data/remote/MemberService.kt
  android/app/src/main/java/com/woowacourse/ody/data/remote/RetrofitClient.kt
  android/build.gradle.kts
  android/gradle.properties
  android/gradle/libs.versions.toml
Labels: AN, FEATURE

#55 chore: cicd 파이프라인 구축
  .github/workflows/backend-cicd-dev.yml
  backend/Dockerfile
Labels: BE, INFRA

#62 chore: backend cicd yml 파일 통합
  .github/workflows/backend-ci-dev.yml
  .github/workflows/backend-cicd-dev.yml
Labels: BE, INFRA

#67 feat: 주소 검색 다이얼로그 구현
  android/app/build.gradle.kts
  android/app/src/main/assets/address.html
  android/app/src/main/java/com/woowacourse/ody/presentation/address/AddressReceiveListener.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/address/AddressSearchDialog.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/address/AddressSearchInterface.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/address/LocalContentWebViewClient.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/destination/MeetingDestinationFragment.kt
  android/app/src/main/res/layout/dialog_address_search.xml
  android/app/src/main/res/layout/fragment_meeting_destination.xml
  android/app/src/main/res/values/styles.xml
Labels: AN, FEATURE

#69 feat: 모임 개설 시 프래그먼트들 연결하는 뷰페이저
  android/app/build.gradle.kts
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/java/com/woowacourse/ody/presentation/date/MeetingDateFragment.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/meetinginfo/MeetingInfoActivity.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/meetinginfo/MeetingInfoListener.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/meetinginfo/adapter/InfoViewPagerAdapter.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/name/MeetingNameFragment.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/nickname/JoinNickNameFragment.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/startingpoint/JoinStartingPointFragment.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/time/MeetingTimeFragment.kt
  android/app/src/main/res/layout/activity_meeting_info.xml
  android/app/src/main/res/layout/fragment_join_nickname.xml
  android/app/src/main/res/layout/fragment_join_starting_point.xml
  android/app/src/main/res/layout/fragment_meeting_date.xml
  android/app/src/main/res/layout/fragment_meeting_name.xml
  android/app/src/main/res/layout/fragment_meeting_time.xml
  android/app/src/main/res/layout/toolbar_back.xml
  android/build.gradle.kts
  android/gradle.properties
  android/gradle/libs.versions.toml
Labels: AN, FEATURE

#70 feat: 모임 참여 완료 화면 구현
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/java/com/woowacourse/ody/presentation/completion/MeetingCompletionActivity.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/meetinginfo/MeetingInfoActivity.kt
  android/app/src/main/res/drawable-hdpi/img_clap.png
  android/app/src/main/res/drawable-mdpi/img_clap.png
  android/app/src/main/res/drawable-xhdpi/img_clap.png
  android/app/src/main/res/drawable-xxhdpi/img_clap.png
  android/app/src/main/res/drawable-xxxhdpi/img_clap.png
  android/app/src/main/res/layout/activity_meeting_completion.xml
  android/app/src/main/res/values/strings.xml
Labels: AN, FEATURE

#72 feat: 모임 참여 완료 화면
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/java/com/woowacourse/ody/presentation/completion/JoinCompleteActivity.kt
  android/app/src/main/res/drawable-hdpi/img_calendar.png
  android/app/src/main/res/drawable-mdpi/img_calendar.png
  android/app/src/main/res/drawable-xhdpi/img_calendar.png
  android/app/src/main/res/drawable-xxhdpi/img_calendar.png
  android/app/src/main/res/drawable-xxxhdpi/img_calendar.png
  android/app/src/main/res/layout/activity_join_complete.xml
  android/app/src/main/res/values/strings.xml
Labels: AN, FEATURE

#73 feat: 메인 화면 구현
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/java/com/woowacourse/ody/presentation/IntroActivity.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/intro/IntroActivity.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/intro/IntroListener.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/intro/IntroNavigateAction.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/intro/IntroViewModel.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/meetinginfo/MeetingInfoActivity.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/splash/SplashActivity.kt
  android/app/src/main/java/com/woowacourse/ody/util/Event.kt
  android/app/src/main/res/drawable/rectangle_purple_radius_20.xml
  android/app/src/main/res/layout/activity_intro.xml
  android/app/src/main/res/layout/activity_main.xml
  android/app/src/main/res/values/strings.xml
Labels: AN, FEATURE

#75 feat: 알림 권한 요청
  android/app/src/main/java/com/woowacourse/ody/presentation/intro/IntroActivity.kt
  android/app/src/main/res/values/strings.xml
Labels: AN, FEATURE

#78 chore: android ci 필드 추가
  .github/workflows/android-ci-dev.yml
Labels: AN, INFRA

#79 feat: 약속 날짜 입력 화면
  android/app/src/main/java/com/woowacourse/ody/presentation/date/MeetingDateFragment.kt
  android/app/src/main/res/layout/fragment_meeting_date.xml
  android/app/src/main/res/values/strings.xml
Labels: AN, FEATURE

#68 feat: 모임 정보 입력 검증 로직 추가
  backend/src/main/java/com/ody/common/annotation/FutureOrPresentDateTime.java
  backend/src/main/java/com/ody/common/validator/FutureOrPresentDateTimeValidator.java
  backend/src/main/java/com/ody/mate/domain/Mate.java
  backend/src/main/java/com/ody/mate/domain/NickName.java
  backend/src/main/java/com/ody/meeting/controller/MeetingController.java
  backend/src/main/java/com/ody/meeting/domain/Location.java
  backend/src/main/java/com/ody/meeting/dto/request/MeetingSaveRequest.java
  backend/src/test/java/com/ody/common/validator/FutureOrPresentDateTimeValidatorTest.java
  backend/src/test/java/com/ody/mate/domain/NickNameTest.java
  backend/src/test/java/com/ody/meeting/domain/LocationTest.java
Labels: BE, FEATURE

#86 feat: 닉네임 입력 화면 구현
  android/app/src/main/java/com/woowacourse/ody/presentation/joininfo/JoinInfoActivity.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/joininfo/JoinInfoViewModel.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/nickname/JoinNickNameFragment.kt
  android/app/src/main/java/com/woowacourse/ody/util/CommonBindingAdapter.kt
  android/app/src/main/res/drawable/ic_cancel.xml
  android/app/src/main/res/layout/fragment_join_nickname.xml
  android/app/src/main/res/values/strings.xml
Labels: AN, FEATURE

#84 feat: 초대 코드 복사 bottom dialog
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/java/com/woowacourse/ody/presentation/meetinglog/CodeCopyListener.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/meetinglog/LogsActivity.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/meetinglog/LogsListener.kt
  android/app/src/main/res/drawable/bottom_sheet_radius_25.xml
  android/app/src/main/res/layout/activity_logs.xml
  android/app/src/main/res/layout/bottom_sheet_code_copy.xml
  android/app/src/main/res/values/strings.xml
Labels: AN, FEATURE

#97 feat: 약속 시간 입력 화면 구현
  android/app/src/main/java/com/woowacourse/ody/presentation/meetinginfo/MeetingInfoActivity.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/meetinginfo/MeetingInfoViewModel.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/time/MeetingTimeBindingAdapter.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/time/MeetingTimeFragment.kt
  android/app/src/main/res/layout/fragment_join_nickname.xml
  android/app/src/main/res/layout/fragment_meeting_time.xml
  android/app/src/main/res/values/strings.xml
  android/app/src/main/res/values/styles.xml
Labels: AN, FEATURE

#99 feat: 초대 코드 입력 화면 구현
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/java/com/woowacourse/ody/data/local/FCMService.kt
  android/app/src/main/java/com/woowacourse/ody/data/remote/DefaultMeetingRepository.kt
  android/app/src/main/java/com/woowacourse/ody/data/remote/service/MeetingService.kt
  android/app/src/main/java/com/woowacourse/ody/data/remote/service/MemberService.kt
  android/app/src/main/java/com/woowacourse/ody/domain/repository/MeetingRepository.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/intro/IntroActivity.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/invitecode/InviteCodeActivity.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/invitecode/InviteCodeViewModel.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/invitecode/InviteCodeViewModelFactory.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/joininfo/JoinInfoActivity.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/meetinginfo/MeetingInfoActivity.kt
  android/app/src/main/res/drawable/rectangle_gray_radius_20.xml
  android/app/src/main/res/drawable/selector_confirm_button.xml
  android/app/src/main/res/layout/activity_invite_code.xml
  android/app/src/main/res/layout/activity_join_info.xml
  android/app/src/main/res/layout/activity_meeting_info.xml
  android/app/src/main/res/layout/toolbar_back.xml
  android/app/src/main/res/values/strings.xml
Labels: AN, FEATURE

#98 feat: 다이얼로그 위치 조정
  android/app/src/main/res/layout/dialog_address_search.xml
Labels: AN, FEATURE

#100 feat: 출발지 입력 화면 구현
  android/app/src/main/java/com/woowacourse/ody/presentation/address/AddressSearchDialog.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/address/AddressValidator.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/address/listener/AddressReceiveListener.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/address/listener/AddressSearchListener.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/address/web/AddressSearchInterface.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/address/web/LocalContentWebViewClient.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/destination/MeetingDestinationFragment.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/joininfo/JoinInfoViewModel.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/meetinginfo/MeetingInfoViewModel.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/startingpoint/JoinStartingPointFragment.kt
  android/app/src/main/res/layout/fragment_join_starting_point.xml
  android/app/src/main/res/layout/fragment_meeting_destination.xml
  android/app/src/main/res/values/strings.xml
Labels: AN, FEATURE

#102 feat: 모임 이름 입력 화면 구현
  android/app/src/main/java/com/woowacourse/ody/presentation/meetinginfo/MeetingInfoViewModel.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/name/MeetingNameFragment.kt
  android/app/src/main/res/layout/fragment_meeting_destination.xml
  android/app/src/main/res/layout/fragment_meeting_name.xml
  android/app/src/main/res/values/strings.xml
Labels: AN, FEATURE

#60 feat: 출발 시간 알림 구현
  backend/.DS_Store
  backend/.gitignore
  backend/gradlew.bat
  backend/src/main/java/com/ody/common/annotaion/AuthMember.java
  backend/src/main/java/com/ody/common/argumentresolver/AuthMemberArgumentResolver.java
  backend/src/main/java/com/ody/common/config/JpaAuditingConfig.java
  backend/src/main/java/com/ody/common/config/WebConfig.java
  backend/src/main/java/com/ody/common/exception/OdyException.java
  backend/src/main/java/com/ody/mate/controller/MateController.java
  backend/src/main/java/com/ody/mate/controller/MateControllerSwagger.java
  backend/src/main/java/com/ody/mate/domain/controller/MateController.java
  backend/src/main/java/com/ody/mate/dto/request/MateSaveRequest.java
  backend/src/main/java/com/ody/mate/repository/MateRepository.java
  backend/src/main/java/com/ody/mate/service/MateService.java
  backend/src/main/java/com/ody/meeting/controller/MeetingController.java
  backend/src/main/java/com/ody/meeting/controller/MeetingControllerSwagger.java
  backend/src/main/java/com/ody/meeting/dto/request/MeetingSaveRequest.java
  backend/src/main/java/com/ody/meeting/dto/response/MateResponse.java
  backend/src/main/java/com/ody/meeting/dto/response/MeetingSaveResponse.java
  backend/src/main/java/com/ody/meeting/repository/MeetingRepository.java
  backend/src/main/java/com/ody/meeting/service/MeetingService.java
  backend/src/main/java/com/ody/member/controller/MemberController.java
  backend/src/main/java/com/ody/member/controller/MemberControllerSwagger.java
  backend/src/main/java/com/ody/member/domain/DeviceToken.java
  backend/src/main/java/com/ody/member/domain/Member.java
  backend/src/main/java/com/ody/member/repository/MemberRepository.java
  backend/src/main/java/com/ody/member/service/MemberService.java
  backend/src/main/java/com/ody/notification/config/FcmConfig.java
  backend/src/main/java/com/ody/notification/config/SchedulingConfig.java
  backend/src/main/java/com/ody/notification/controller/NotificationController.java
  backend/src/main/java/com/ody/notification/controller/NotificationControllerSwagger.java
  backend/src/main/java/com/ody/notification/domain/Notification.java
  backend/src/main/java/com/ody/notification/domain/NotificationStatus.java
  backend/src/main/java/com/ody/notification/dto/request/FcmSendRequest.java
  backend/src/main/java/com/ody/notification/dto/response/NotiLogFindResponse.java
  backend/src/main/java/com/ody/notification/dto/response/NotificationSaveResponse.java
  backend/src/main/java/com/ody/notification/repository/NotificationRepository.java
  backend/src/main/java/com/ody/notification/service/FcmEventScheduler.java
  backend/src/main/java/com/ody/notification/service/FcmPushSender.java
  backend/src/main/java/com/ody/notification/service/FcmSubscriber.java
  backend/src/main/java/com/ody/notification/service/NotificationService.java
  backend/src/main/java/com/ody/swagger/annotation/DeviceTokenHeader.java
  backend/src/main/resources/application.yml
  backend/src/test/java/com/ody/common/BaseControllerTest.java
  backend/src/test/java/com/ody/common/Fixture.java
  backend/src/test/java/com/ody/mate/controller/MateControllerTest.java
  backend/src/test/java/com/ody/mate/repository/MateRepositoryTest.java
  backend/src/test/java/com/ody/member/domain/DeviceTokenTest.java
  backend/src/test/java/com/ody/member/repository/MemberRepositoryTest.java
  backend/src/test/java/com/ody/notification/service/FcmEventSchedulerTest.java
Labels: BE, FEATURE

#104 feat: 초대 코드 Preference dataStore 세팅
  android/app/build.gradle.kts
  android/app/src/main/java/com/woowacourse/ody/OdyApplication.kt
  android/app/src/main/java/com/woowacourse/ody/data/local/db/OdyDatastore.kt
  android/gradle/libs.versions.toml
Labels: AN, FEATURE

#105 feat: 모임 참여/개설 시 뷰모델 데이터 관리 #93
  android/app/src/main/java/com/woowacourse/ody/presentation/completion/JoinCompleteActivity.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/completion/MeetingCompletionActivity.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/date/MeetingDateFragment.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/destination/MeetingDestinationFragment.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/intro/IntroActivity.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/invitecode/InviteCodeActivity.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/joininfo/JoinInfoActivity.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/joininfo/JoinInfoViewModel.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/meetinginfo/MeetingInfoActivity.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/meetinginfo/MeetingInfoViewModel.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/meetinglog/LogsActivity.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/name/MeetingNameFragment.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/nickname/JoinNickNameFragment.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/startingpoint/JoinStartingPointFragment.kt
  android/app/src/main/java/com/woowacourse/ody/util/CommonBindingAdapter.kt
  android/app/src/main/java/com/woowacourse/ody/util/NextListener.kt
  android/app/src/main/res/layout/activity_join_info.xml
  android/app/src/main/res/layout/activity_meeting_info.xml
  android/app/src/main/res/layout/fragment_join_nickname.xml
  android/app/src/main/res/layout/fragment_join_starting_point.xml
  android/app/src/main/res/layout/fragment_meeting_destination.xml
  android/app/src/main/res/layout/fragment_meeting_name.xml
  android/app/src/main/res/layout/fragment_meeting_time.xml
Labels: AN, FEATURE

#107 fix: Swagger에서 API 호출 시 Bad Request 응답 오류
  backend/src/main/java/com/ody/common/annotation/AuthMember.java
  backend/src/main/java/com/ody/common/argumentresolver/AuthMemberArgumentResolver.java
  backend/src/main/java/com/ody/mate/controller/MateController.java
  backend/src/main/java/com/ody/mate/controller/MateControllerSwagger.java
  backend/src/main/java/com/ody/mate/dto/request/MateSaveRequest.java
  backend/src/main/java/com/ody/meeting/controller/MeetingController.java
  backend/src/main/java/com/ody/meeting/controller/MeetingControllerSwagger.java
  backend/src/main/java/com/ody/meeting/dto/request/MeetingSaveRequest.java
  backend/src/main/java/com/ody/meeting/dto/response/MateResponse.java
  backend/src/main/java/com/ody/meeting/dto/response/MeetingSaveResponse.java
  backend/src/main/java/com/ody/member/controller/MemberController.java
  backend/src/main/java/com/ody/member/controller/MemberControllerSwagger.java
  backend/src/main/java/com/ody/member/domain/DeviceToken.java
  backend/src/main/java/com/ody/notification/controller/NotificationController.java
  backend/src/main/java/com/ody/notification/controller/NotificationControllerSwagger.java
  backend/src/main/java/com/ody/notification/service/NotificationService.java
  backend/src/main/java/com/ody/swagger/annotation/DeviceTokenHeader.java
  backend/src/main/java/com/ody/swagger/config/SwaggerConfig.java
  backend/src/test/java/com/ody/common/Fixture.java
  backend/src/test/java/com/ody/mate/controller/MateControllerTest.java
  backend/src/test/java/com/ody/member/domain/DeviceTokenTest.java
Labels: BE, BUG

#61 feat: 모임 초대 코드 생성 기능 추가
  backend/src/main/java/com/ody/meeting/service/InviteCodeGenerator.java
  backend/src/test/java/com/ody/meeting/service/InviteCodeGeneratorTest.java
Labels: BE, FEATURE

#116 feat: 스낵바 위치 조정
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/java/com/woowacourse/ody/presentation/date/MeetingDateFragment.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/destination/MeetingDestinationFragment.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/intro/IntroActivity.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/invitecode/InviteCodeActivity.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/meetinglog/LogsActivity.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/notificationlog/NotificationLogActivity.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/startingpoint/JoinStartingPointFragment.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/time/MeetingTimeFragment.kt
Labels: AN, FEATURE

#87 feat: 로그 목록 조회
  backend/.DS_Store
  backend/src/main/java/com/ody/BackendApplication.java
  backend/src/main/java/com/ody/mate/dto/request/MateSaveRequest.java
  backend/src/main/java/com/ody/mate/repository/MateRepository.java
  backend/src/main/java/com/ody/meeting/controller/MeetingController.java
  backend/src/main/java/com/ody/meeting/controller/MeetingControllerSwagger.java
  backend/src/main/java/com/ody/meeting/dto/response/MateResponse.java
  backend/src/main/java/com/ody/meeting/repository/MeetingRepository.java
  backend/src/main/java/com/ody/member/repository/MemberRepository.java
  backend/src/main/java/com/ody/notification/controller/NotificationController.java
  backend/src/main/java/com/ody/notification/controller/NotificationControllerSwagger.java
  backend/src/main/java/com/ody/notification/dto/response/FcmSendRequest.java
  backend/src/main/java/com/ody/notification/dto/response/NotiLogFindResponse.java
  backend/src/main/java/com/ody/notification/dto/response/NotiLogFindResponses.java
  backend/src/main/java/com/ody/notification/dto/response/NotificationSaveResponse.java
  backend/src/main/java/com/ody/notification/repository/NotificationRepository.java
  backend/src/main/java/com/ody/notification/service/NotificationService.java
  backend/src/test/java/com/ody/common/BaseServiceTest.java
  backend/src/test/java/com/ody/common/Fixture.java
  backend/src/test/java/com/ody/mate/controller/MateControllerTest.java
  backend/src/test/java/com/ody/mate/repository/MateRepositoryTest.java
  backend/src/test/java/com/ody/meeting/controller/MeetingControllerTest.java
  backend/src/test/java/com/ody/meeting/notification/repository/NotificationRepositoryTest.java
  backend/src/test/java/com/ody/notification/service/FcmEventSchedulerTest.java
  backend/src/test/java/com/ody/route/service/RouteServiceTest.java
Labels: BE, FEATURE

#127 fix: 회원 생성, 모임 참여 API 오류 수정
  backend/src/main/java/com/ody/mate/domain/Mate.java
  backend/src/main/java/com/ody/mate/repository/MateRepository.java
  backend/src/main/java/com/ody/mate/service/MateService.java
  backend/src/main/java/com/ody/member/domain/DeviceToken.java
  backend/src/main/java/com/ody/member/domain/Member.java
  backend/src/main/java/com/ody/member/repository/MemberRepository.java
  backend/src/main/java/com/ody/member/service/MemberService.java
  backend/src/test/java/com/ody/meeting/controller/MeetingControllerTest.java
  backend/src/test/java/com/ody/member/repository/MemberRepositoryTest.java
Labels: BE, BUG

#126 feat: CI/CD 스크립트 분리
  .github/workflows/backend-cd-dev.yml
  .github/workflows/backend-ci-dev.yml
Labels: BE, INFRA

#119 feat: 모임 내 닉네임 중복 검증
  backend/src/main/java/com/ody/mate/service/MateService.java
  backend/src/test/java/com/ody/mate/service/MateServiceTest.java
Labels: BE, FEATURE

#131 feat: 모임 개설 서버 연결
  android/app/src/main/java/com/woowacourse/ody/data/local/fake/FakeMeetingRepository.kt
  android/app/src/main/java/com/woowacourse/ody/data/model/Mapper.kt
  android/app/src/main/java/com/woowacourse/ody/data/model/meeting/MeetingRequest.kt
  android/app/src/main/java/com/woowacourse/ody/data/model/meeting/MeetingResponse.kt
  android/app/src/main/java/com/woowacourse/ody/data/remote/repository/DefaultMeetingRepository.kt
  android/app/src/main/java/com/woowacourse/ody/data/remote/service/MeetingService.kt
  android/app/src/main/java/com/woowacourse/ody/domain/Meeting.kt
  android/app/src/main/java/com/woowacourse/ody/domain/repository/MeetingRepository.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/completion/JoinCompleteActivity.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/completion/JoinCompleteViewModel.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/completion/JoinCompleteViewModelFactory.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/joininfo/JoinInfoActivity.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/meetinginfo/MeetingInfoActivity.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/meetinglog/LogsActivity.kt
Labels: AN, FEATURE

#129 feat: 특정 회원이 참여한 모임 목록 조회 API 구현
  backend/src/main/java/com/ody/meeting/controller/MeetingController.java
  backend/src/main/java/com/ody/meeting/repository/MeetingRepository.java
  backend/src/main/java/com/ody/meeting/service/MeetingService.java
  backend/src/test/java/com/ody/common/Fixture.java
  backend/src/test/java/com/ody/meeting/controller/MeetingControllerTest.java
  backend/src/test/java/com/ody/meeting/repository/MeetingRepositoryTest.java
  backend/src/test/java/com/ody/notification/repository/NotificationRepositoryTest.java
Labels: BE, FEATURE

#122 feat: 다음 버튼 비활성화 시 뷰페이저 스와이프 막는 기능 구현
  android/app/src/main/java/com/woowacourse/ody/presentation/date/MeetingDateFragment.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/destination/MeetingDestinationFragment.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/meetinginfo/MeetingInfoActivity.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/meetinginfo/MeetingInfoType.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/meetinginfo/MeetingInfoViewModel.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/name/MeetingNameFragment.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/nickname/JoinNickNameFragment.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/startingpoint/JoinStartingPointFragment.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/time/MeetingTimeFragment.kt
  android/app/src/main/res/layout/activity_meeting_info.xml
Labels: AN, FEATURE

#128 feat: Notification 구현
  android/app/build.gradle.kts
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/java/com/woowacourse/ody/data/local/FCMService.kt
  android/app/src/main/java/com/woowacourse/ody/data/remote/FCMService.kt
  android/app/src/main/res/values/strings.xml
  android/gradle/libs.versions.toml
Labels: AN, FEATURE

#130 feat: 알림 로그 화면에 bottom dialog 적용
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/java/com/woowacourse/ody/data/local/fake/FakeMeetingRepository.kt
  android/app/src/main/java/com/woowacourse/ody/data/local/fake/FakeNotificationLogRepository.kt
  android/app/src/main/java/com/woowacourse/ody/data/model/Mapper.kt
  android/app/src/main/java/com/woowacourse/ody/data/remote/repository/DefaultMeetingRepository.kt
  android/app/src/main/java/com/woowacourse/ody/data/remote/repository/DefaultNotificationLogRepository.kt
  android/app/src/main/java/com/woowacourse/ody/domain/model/Mate.kt
  android/app/src/main/java/com/woowacourse/ody/domain/model/Meeting.kt
  android/app/src/main/java/com/woowacourse/ody/domain/model/NotificationLog.kt
  android/app/src/main/java/com/woowacourse/ody/domain/model/NotificationType.kt
  android/app/src/main/java/com/woowacourse/ody/domain/repository/MeetingRepository.kt
  android/app/src/main/java/com/woowacourse/ody/domain/repository/NotificationLogRepository.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/completion/JoinCompleteActivity.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/completion/JoinCompleteViewModel.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/meetinglog/CodeCopyListener.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/meetinglog/LogsActivity.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/meetinglog/LogsListener.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/notificationlog/BindingAdapter.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/notificationlog/CopyInviteCodeButtonListener.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/notificationlog/CopyInviteCodeListener.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/notificationlog/NotificationLogActivity.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/notificationlog/NotificationLogViewModel.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/notificationlog/NotificationLogViewModelFactory.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/notificationlog/ShareListener.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/notificationlog/adapter/InviteCodeViewHolder.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/notificationlog/adapter/NotificationLogListAdapter.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/notificationlog/uimodel/Mapper.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/notificationlog/uimodel/MeetingUiModel.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/notificationlog/uimodel/NotificationLogUiModel.kt
  android/app/src/main/res/layout/activity_logs.xml
  android/app/src/main/res/layout/activity_notification_log.xml
  android/app/src/main/res/layout/bottom_sheet_code_copy.xml
  android/app/src/main/res/layout/item_invite_code_log.xml
  android/app/src/main/res/layout/toolbar_log.xml
Labels: AN, FEATURE

#137 fix: backend merge bug fix
  backend/src/test/java/com/ody/common/BaseServiceTest.java
  backend/src/test/java/com/ody/meeting/controller/MeetingControllerTest.java
  backend/src/test/java/com/ody/util/InviteCodeGeneratorTest.java
Labels: BE, BUG

#133 fix: 초대 코드 입력 성공 시 참여 화면으로 이동하도록 수정
  android/app/src/main/java/com/woowacourse/ody/presentation/invitecode/InviteCodeActivity.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/invitecode/InviteCodeNavigateAction.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/invitecode/InviteCodeViewModel.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/joininfo/JoinInfoActivity.kt
Labels: AN, BUG

#139 feat: 모임 개설 api 연결
  android/app/build.gradle.kts
  android/app/src/main/java/com/woowacourse/ody/data/local/fake/FakeMeetingRepository.kt
  android/app/src/main/java/com/woowacourse/ody/data/model/meeting/MeetingResponse.kt
  android/app/src/main/java/com/woowacourse/ody/data/remote/FCMService.kt
  android/app/src/main/java/com/woowacourse/ody/data/remote/RetrofitClient.kt
  android/app/src/main/java/com/woowacourse/ody/data/remote/service/MeetingService.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/completion/JoinCompleteActivity.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/completion/JoinCompleteViewModel.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/meetinginfo/MeetingInfoActivity.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/notificationlog/NotificationLogActivity.kt
  android/gradle/libs.versions.toml
  backend/.DS_Store
Labels: AN, FEATURE

#140 feat: 커스텀 예외 생성 및 적용
  backend/src/main/java/com/ody/common/exception/GlobalExceptionHandler.java
  backend/src/main/java/com/ody/common/exception/NotFoundException.java
  backend/src/main/java/com/ody/common/exception/OdyBadRequestException.java
  backend/src/main/java/com/ody/common/exception/OdyException.java
  backend/src/main/java/com/ody/common/exception/OdyNotFoundException.java
  backend/src/main/java/com/ody/common/exception/OdyServerErrorException.java
  backend/src/main/java/com/ody/common/exception/OdyUnauthorizedException.java
  backend/src/main/java/com/ody/common/validator/FutureOrPresentDateTimeValidator.java
  backend/src/main/java/com/ody/mate/domain/Nickname.java
  backend/src/main/java/com/ody/mate/service/MateService.java
  backend/src/main/java/com/ody/meeting/controller/MeetingController.java
  backend/src/main/java/com/ody/meeting/domain/Location.java
  backend/src/main/java/com/ody/meeting/dto/request/MeetingSaveRequest.java
  backend/src/main/java/com/ody/meeting/service/MeetingService.java
  backend/src/main/java/com/ody/member/domain/DeviceToken.java
  backend/src/main/java/com/ody/member/domain/Member.java
  backend/src/main/java/com/ody/member/repository/MemberRepository.java
  backend/src/main/java/com/ody/member/service/MemberService.java
  backend/src/main/java/com/ody/notification/controller/NotificationController.java
  backend/src/main/java/com/ody/notification/service/FcmPushSender.java
  backend/src/main/java/com/ody/notification/service/FcmSubscriber.java
  backend/src/main/java/com/ody/notification/service/NotificationService.java
  backend/src/main/java/com/ody/route/mapper/OdsayResponseDeserializer.java
  backend/src/main/java/com/ody/route/service/RouteClient.java
  backend/src/main/java/com/ody/swagger/annotation/ErrorCode400.java
  backend/src/main/java/com/ody/swagger/annotation/ErrorCode401.java
  backend/src/main/java/com/ody/swagger/annotation/ErrorCode500.java
  backend/src/main/java/com/ody/swagger/config/SwaggerConfig.java
  backend/src/main/java/com/ody/util/InviteCodeGenerator.java
  backend/src/test/java/com/ody/common/BaseControllerTest.java
  backend/src/test/java/com/ody/mate/controller/MateControllerTest.java
  backend/src/test/java/com/ody/mate/domain/NicknameTest.java
  backend/src/test/java/com/ody/mate/service/MateServiceTest.java
  backend/src/test/java/com/ody/meeting/controller/MeetingControllerTest.java
  backend/src/test/java/com/ody/meeting/domain/LocationTest.java
  backend/src/test/java/com/ody/member/domain/DeviceTokenTest.java
  backend/src/test/java/com/ody/notification/repository/NotificationRepositoryTest.java
  backend/src/test/java/com/ody/route/service/RouteServiceTest.java
Labels: BE, FEATURE

#143 feat: 모임 참여 서버 연결
  android/app/src/main/java/com/woowacourse/ody/data/model/join/JoinRequest.kt
  android/app/src/main/java/com/woowacourse/ody/data/remote/repository/DefaultJoinRepository.kt
  android/app/src/main/java/com/woowacourse/ody/data/remote/service/JoinService.kt
  android/app/src/main/java/com/woowacourse/ody/domain/repository/JoinRepository.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/completion/JoinCompleteActivity.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/completion/JoinCompleteViewModel.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/completion/JoinCompleteViewModelFactory.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/joininfo/JoinInfoActivity.kt
Labels: AN, FEATURE

#142 feat: 참여중인 모임 목록 조회
  android/app/src/main/java/com/woowacourse/ody/data/local/fake/FakeNotificationLogRepository.kt
  android/app/src/main/java/com/woowacourse/ody/data/remote/repository/DefaultNotificationLogRepository.kt
  android/app/src/main/java/com/woowacourse/ody/data/remote/service/NotificationService.kt
  android/app/src/main/java/com/woowacourse/ody/domain/repository/NotificationLogRepository.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/notificationlog/NotificationLogViewModel.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/splash/SplashActivity.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/splash/SplashViewModel.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/splash/SplashViewModelFactory.kt
Labels: AN, FEATURE

#146 feat: EC2 서버의 H2 콘솔 접근 설정 및 누락된 모임장 알림 로직 추가
  backend/src/main/java/com/ody/meeting/controller/MeetingController.java
  backend/src/main/resources/application.yml
  backend/src/test/java/com/ody/mate/controller/MateControllerTest.java
  backend/src/test/java/com/ody/meeting/controller/MeetingControllerTest.java
Labels: BE, FEATURE

#149 fix: FCM 토픽 Malformed topic name 에러 해결
  backend/src/main/java/com/ody/notification/service/FcmPushSender.java
  backend/src/main/java/com/ody/notification/service/FcmSubscriber.java
Labels: BE, BUG

#151 fix: FCM 토픽 Malformed topic name 에러 해결
  backend/src/main/java/com/ody/notification/service/FcmPushSender.java
  backend/src/main/java/com/ody/notification/service/FcmSubscriber.java
  backend/src/main/java/com/ody/notification/service/NotificationService.java
Labels: BE, BUG

#153 fix: Malformed topic name 에러 해결
  backend/src/main/java/com/ody/notification/service/FcmPushSender.java
  backend/src/main/java/com/ody/notification/service/NotificationService.java
Labels: BE, BUG

#157 fix: 로그 화면 버그 해결
  android/app/src/main/java/com/woowacourse/ody/data/local/db/OdyDatastore.kt
  android/app/src/main/java/com/woowacourse/ody/data/local/fake/FakeMeetingRepository.kt
  android/app/src/main/java/com/woowacourse/ody/data/model/Mapper.kt
  android/app/src/main/java/com/woowacourse/ody/data/model/meeting/MeetingsResponse.kt
  android/app/src/main/java/com/woowacourse/ody/data/remote/FCMService.kt
  android/app/src/main/java/com/woowacourse/ody/data/remote/repository/DefaultMeetingRepository.kt
  android/app/src/main/java/com/woowacourse/ody/data/remote/service/MeetingService.kt
  android/app/src/main/java/com/woowacourse/ody/domain/model/Meeting.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/completion/JoinCompleteActivity.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/joininfo/JoinInfoActivity.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/notificationlog/NotificationLogActivity.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/notificationlog/NotificationLogViewModel.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/notificationlog/uimodel/Mapper.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/splash/SplashActivity.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/splash/SplashViewModel.kt
  android/app/src/main/res/drawable/rectangle_cream_downside_radius_30.xml
  android/app/src/main/res/drawable/rectangle_cream_downside_shadow_radius_30.xml
  android/app/src/main/res/layout/activity_notification_log.xml
  android/app/src/main/res/layout/toolbar_log.xml
Labels: AN, FEATURE

#155 fix: 달력 월말 날짜 선택 안되는 버그 수정
  android/app/src/main/java/com/woowacourse/ody/presentation/date/MeetingDateFragment.kt
  android/app/src/main/res/layout/fragment_meeting_date.xml
Labels: AN, BUG

#144 feat: 로그 목록 조회 시 과거순 정렬
  backend/src/main/java/com/ody/meeting/controller/MeetingController.java
  backend/src/main/java/com/ody/meeting/controller/MeetingControllerSwagger.java
  backend/src/main/java/com/ody/meeting/dto/response/MeetingSaveResponse.java
  backend/src/main/java/com/ody/notification/dto/response/NotiLogFindResponse.java
  backend/src/main/java/com/ody/notification/dto/response/NotificationSaveResponse.java
  backend/src/main/java/com/ody/notification/repository/NotificationRepository.java
  backend/src/test/java/com/ody/notification/repository/NotificationRepositoryTest.java
Labels: BE, FEATURE

#162 fix: 알림 전송 예약 시점이 아닌 전송 시점에 상태 변경
  backend/src/main/java/com/ody/notification/domain/Notification.java
  backend/src/main/java/com/ody/notification/dto/request/FcmSendRequest.java
  backend/src/main/java/com/ody/notification/service/FcmPushSender.java
  backend/src/main/java/com/ody/notification/service/NotificationService.java
  backend/src/test/java/com/ody/notification/service/FcmEventSchedulerTest.java
Labels: BE, BUG

#164 feat: 초대코드 존재유무 검증로직 구현
  backend/src/main/java/com/ody/meeting/controller/MeetingController.java
  backend/src/main/java/com/ody/meeting/repository/MeetingRepository.java
  backend/src/main/java/com/ody/meeting/service/MeetingService.java
  backend/src/test/java/com/ody/meeting/repository/MeetingRepositoryTest.java
Labels: BE, FEATURE

#163 fix: 스플래쉬 딜레이 수정
  android/app/src/main/java/com/woowacourse/ody/data/model/Mapper.kt
Labels: AN, BUG

#184 refactor: manifest tools 속성 제거
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/java/com/woowacourse/ody/presentation/common/Event.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/common/MutableSingleLiveData.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/common/SingleLiveData.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/creation/MeetingCreationActivity.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/creation/MeetingCreationViewModel.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/creation/time/MeetingTimeFragment.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/intro/IntroActivity.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/intro/IntroViewModel.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/invitecode/InviteCodeActivity.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/invitecode/InviteCodeViewModel.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/join/complete/JoinCompleteViewModel.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/join/departure/JoinDepartureFragment.kt
Labels: AN, REFACTOR

#177 test: RouteClient Mock 테스트
  backend/src/main/java/com/ody/route/config/RouteConfig.java
  backend/src/main/java/com/ody/route/service/OdsayRouteClient.java
  backend/src/main/java/com/ody/route/service/RouteClient.java
  backend/src/test/java/com/ody/common/BaseControllerTest.java
  backend/src/test/java/com/ody/common/BaseServiceTest.java
  backend/src/test/java/com/ody/common/FakeRouteClient.java
  backend/src/test/java/com/ody/common/TestRouteConfig.java
  backend/src/test/java/com/ody/mate/controller/MateControllerTest.java
  backend/src/test/java/com/ody/meeting/controller/MeetingControllerTest.java
  backend/src/test/java/com/ody/route/service/OdsayRouteClientTest.java
  backend/src/test/java/com/ody/route/service/RouteServiceTest.java
  backend/src/test/resources/application.yml
  backend/src/test/resources/odsay-api-response/error-98Response.json
  backend/src/test/resources/odsay-api-response/error4Response.json
  backend/src/test/resources/odsay-api-response/error500Response.json
  backend/src/test/resources/odsay-api-response/successResponse.json
Labels: BE, FEATURE

#185 refactor: Event -> SingleLiveData로 개선
  android/app/src/main/java/com/woowacourse/ody/presentation/common/Event.kt
Labels: AN, REFACTOR

#186 refactor: MeetingCreationViewModel UiState 관리 개선
  android/app/src/main/java/com/woowacourse/ody/presentation/creation/MeetingCreationActivity.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/creation/MeetingCreationViewModel.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/creation/date/MeetingDateFragment.kt
Labels: AN, REFACTOR

#166 feat: 알림 생성 시점이 전송 시점보다 늦은 경우 예외 처리
  backend/src/main/java/com/ody/notification/service/NotificationService.java
  backend/src/main/java/com/ody/route/domain/DepartureTime.java
  backend/src/test/java/com/ody/common/BaseServiceTest.java
  backend/src/test/java/com/ody/common/Fixture.java
  backend/src/test/java/com/ody/notification/service/NotificationServiceTest.java
Labels: BE, FEATURE

#183 refactor: application에서 repository, datastore, retrofit service 인스턴스 관리
  android/app/src/main/java/com/woowacourse/ody/OdyApplication.kt
  android/app/src/main/java/com/woowacourse/ody/data/local/db/OdyDatastore.kt
  android/app/src/main/java/com/woowacourse/ody/data/remote/core/RetrofitClient.kt
  android/app/src/main/java/com/woowacourse/ody/data/remote/core/repository/DefaultFCMTokenRepository.kt
  android/app/src/main/java/com/woowacourse/ody/data/remote/core/repository/DefaultInviteCodeRepository.kt
  android/app/src/main/java/com/woowacourse/ody/data/remote/core/repository/DefaultJoinRepository.kt
  android/app/src/main/java/com/woowacourse/ody/data/remote/core/repository/DefaultMeetingRepository.kt
  android/app/src/main/java/com/woowacourse/ody/data/remote/core/repository/DefaultNotificationLogRepository.kt
  android/app/src/main/java/com/woowacourse/ody/data/remote/thirdparty/fcm/service/FCMService.kt
  android/app/src/main/java/com/woowacourse/ody/data/remote/thirdparty/location/KakaoRetrofitClient.kt
  android/app/src/main/java/com/woowacourse/ody/data/remote/thirdparty/location/repository/KakaoGeoLocationRepository.kt
  android/app/src/main/java/com/woowacourse/ody/domain/repository/ody/FCMTokenRepository.kt
  android/app/src/main/java/com/woowacourse/ody/domain/repository/ody/InviteCodeRepository.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/address/AddressSearchDialog.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/invitecode/InviteCodeActivity.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/join/complete/JoinCompleteActivity.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/join/complete/JoinCompleteViewModel.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/join/complete/JoinCompleteViewModelFactory.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/room/MeetingRoomActivity.kt
  android/app/src/main/java/com/woowacourse/ody/presentation/splash/SplashActivity.kt
Labels: AN, REFACTOR
