Repository woowacourse-teams/2024-ody, pull requests merged in 2025-01, with the labels that each got.

#940 chore: 개발 서버 cd 체크아웃 브랜치 복구
  .github/workflows/backend-cd-dev.yml
Labels: BE, INFRA

#943 fix: 운영 서버 배포 시 개발 서버 프로필로 활성화되는 문제 해결
  .github/workflows/backend-cd-prod.yml
  backend/Dockerfile
  backend/src/main/resources/application-prod.yml
Labels: BE, BUG, INFRA

#931 refactor: 카카오 로그인 관련 로직 DataSource 리팩터링
  android/app/src/main/java/com/mulberry/ody/data/auth/repository/KakaoAuthRepository.kt
  android/app/src/main/java/com/mulberry/ody/data/auth/source/local/KakaoLocalAuthDataSource.kt
  android/app/src/main/java/com/mulberry/ody/data/auth/source/local/LocalAuthDataSource.kt
  android/app/src/main/java/com/mulberry/ody/data/auth/source/remote/KakaoRemoteAuthDataSource.kt
  android/app/src/main/java/com/mulberry/ody/data/auth/source/remote/RemoteAuthDataSource.kt
  android/app/src/main/java/com/mulberry/ody/data/local/repository/DefaultAuthTokenRepository.kt
  android/app/src/main/java/com/mulberry/ody/data/remote/core/repository/DefaultFCMTokenRepository.kt
  android/app/src/main/java/com/mulberry/ody/data/remote/core/service/AuthService.kt
  android/app/src/main/java/com/mulberry/ody/data/remote/core/service/LogoutService.kt
  android/app/src/main/java/com/mulberry/ody/data/remote/core/service/MemberService.kt
  android/app/src/main/java/com/mulberry/ody/data/remote/thirdparty/fcm/service/FCMService.kt
  android/app/src/main/java/com/mulberry/ody/data/remote/thirdparty/login/kakao/KakaoLoginRepository.kt
  android/app/src/main/java/com/mulberry/ody/data/remote/thirdparty/login/kakao/KakaoOAuthLoginService.kt
  android/app/src/main/java/com/mulberry/ody/data/retrofit/AccessTokenInterceptor.kt
  android/app/src/main/java/com/mulberry/ody/data/retrofit/RefreshTokenInterceptor.kt
  android/app/src/main/java/com/mulberry/ody/di/DataSourceModule.kt
  android/app/src/main/java/com/mulberry/ody/di/NetworkModule.kt
  android/app/src/main/java/com/mulberry/ody/di/RepositoryModule.kt
  android/app/src/main/java/com/mulberry/ody/di/ServiceModule.kt
  android/app/src/main/java/com/mulberry/ody/domain/apiresult/ApiResultExtensions.kt
  android/app/src/main/java/com/mulberry/ody/domain/repository/ody/AuthRepository.kt
  android/app/src/main/java/com/mulberry/ody/domain/repository/ody/AuthTokenRepository.kt
  android/app/src/main/java/com/mulberry/ody/domain/repository/ody/FCMTokenRepository.kt
  android/app/src/main/java/com/mulberry/ody/presentation/login/LoginActivity.kt
  android/app/src/main/java/com/mulberry/ody/presentation/login/LoginViewModel.kt
  android/app/src/main/java/com/mulberry/ody/presentation/setting/SettingViewModel.kt
Labels: AN, REFACTOR

#945 fix: Header null 값 들어가는 버그 해결
  android/app/src/main/java/com/mulberry/ody/data/auth/source/remote/KakaoRemoteAuthDataSource.kt
  android/app/src/main/java/com/mulberry/ody/data/remote/core/service/AuthService.kt
  android/app/src/main/java/com/mulberry/ody/data/remote/core/service/LoginService.kt
  android/app/src/main/java/com/mulberry/ody/di/ServiceModule.kt
Labels: AN, BUG

#949 refactor: suspendOnXXX() 함수 제거
  android/app/src/main/java/com/mulberry/ody/data/auth/repository/KakaoAuthRepository.kt
  android/app/src/main/java/com/mulberry/ody/data/local/service/EtaDashboardService.kt
  android/app/src/main/java/com/mulberry/ody/data/retrofit/AccessTokenInterceptor.kt
  android/app/src/main/java/com/mulberry/ody/domain/apiresult/ApiResultExtensions.kt
  android/app/src/main/java/com/mulberry/ody/presentation/creation/MeetingCreationViewModel.kt
  android/app/src/main/java/com/mulberry/ody/presentation/invitecode/InviteCodeViewModel.kt
  android/app/src/main/java/com/mulberry/ody/presentation/join/MeetingJoinViewModel.kt
  android/app/src/main/java/com/mulberry/ody/presentation/login/LoginViewModel.kt
  android/app/src/main/java/com/mulberry/ody/presentation/room/MeetingRoomViewModel.kt
  android/app/src/main/java/com/mulberry/ody/presentation/setting/SettingViewModel.kt
Labels: AN, REFACTOR

#955 docs: 애플 로그인 회원 삭제 API 문서화
  backend/src/main/java/com/ody/member/controller/MemberController.java
  backend/src/main/java/com/ody/member/controller/MemberControllerSwagger.java
  backend/src/main/java/com/ody/swagger/annotation/ErrorCode403.java
Labels: BE, DOCS

#960 refactor: 약속 단건 조회 api v2 구현
  backend/src/main/java/com/ody/mate/domain/Mate.java
  backend/src/main/java/com/ody/meeting/controller/MeetingController.java
  backend/src/main/java/com/ody/meeting/controller/MeetingControllerSwagger.java
  backend/src/main/java/com/ody/meeting/dto/response/MeetingWithMatesResponseV1.java
  backend/src/main/java/com/ody/meeting/dto/response/MeetingWithMatesResponseV2.java
  backend/src/main/java/com/ody/meeting/service/MeetingService.java
  backend/src/test/java/com/ody/meeting/service/MeetingServiceTest.java
Labels: BE, REFACTOR

#947 feat: apiCall 동시성 이슈를 분산락에서 비관적 락으로 대체
  backend/src/main/java/com/ody/common/aop/DistributedLock.java
  backend/src/main/java/com/ody/common/aop/DistributedLockAop.java
  backend/src/main/java/com/ody/common/redis/RedissonLockManager.java
  backend/src/main/java/com/ody/eta/service/EtaService.java
  backend/src/main/java/com/ody/meeting/service/MeetingService.java
  backend/src/main/java/com/ody/route/domain/ApiCall.java
  backend/src/main/java/com/ody/route/repository/ApiCallRepository.java
  backend/src/main/java/com/ody/route/service/ApiCallService.java
  backend/src/main/java/com/ody/route/service/RouteClientCircuitBreaker.java
  backend/src/main/java/com/ody/route/service/RouteClientManager.java
  backend/src/main/java/com/ody/route/service/RouteService.java
  backend/src/test/java/com/ody/common/BaseControllerTest.java
  backend/src/test/java/com/ody/common/BaseServiceTest.java
  backend/src/test/java/com/ody/common/redis/RouteClientRedisTemplateTest.java
  backend/src/test/java/com/ody/meeting/service/MeetingServiceTest.java
  backend/src/test/java/com/ody/route/repository/ApiCallRepositoryTest.java
  backend/src/test/java/com/ody/route/repository/RouteClientRedisTemplateTest.java
  backend/src/test/java/com/ody/route/service/ApiCallServiceTest.java
  backend/src/test/java/com/ody/route/service/RouteClientCircuitBreakerTest.java
  backend/src/test/java/com/ody/route/service/RouteClientManagerTest.java
  backend/src/test/java/com/ody/route/service/RouteServiceTest.java
Labels: BE, REFACTOR

#961 feat: 약속 상세 화면 기능 개발
  android/app/src/main/java/com/mulberry/ody/data/remote/core/entity/meeting/mapper/MeetingResponseMapper.kt
  android/app/src/main/java/com/mulberry/ody/data/remote/core/entity/meeting/response/MeetingResponse.kt
  android/app/src/main/java/com/mulberry/ody/data/remote/core/service/MeetingService.kt
  android/app/src/main/java/com/mulberry/ody/domain/model/Meeting.kt
  android/app/src/main/java/com/mulberry/ody/presentation/common/DimensionExtensions.kt
  android/app/src/main/java/com/mulberry/ody/presentation/join/MeetingJoinActivity.kt
  android/app/src/main/java/com/mulberry/ody/presentation/meetings/MeetingsActivity.kt
  android/app/src/main/java/com/mulberry/ody/presentation/notification/FCMNotification.kt
  android/app/src/main/java/com/mulberry/ody/presentation/room/MeetingRoomActivity.kt
  android/app/src/main/java/com/mulberry/ody/presentation/room/MeetingRoomNavigateAction.kt
  android/app/src/main/java/com/mulberry/ody/presentation/room/MeetingRoomViewModel.kt
  android/app/src/main/java/com/mulberry/ody/presentation/room/detail/DetailMeetingBindingAdapter.kt
  android/app/src/main/java/com/mulberry/ody/presentation/room/detail/DetailMeetingFragment.kt
  android/app/src/main/java/com/mulberry/ody/presentation/room/detail/adapter/MatesAdapter.kt
  android/app/src/main/java/com/mulberry/ody/presentation/room/detail/adapter/MatesViewHolder.kt
  android/app/src/main/java/com/mulberry/ody/presentation/room/detail/listener/DepartureTimeGuideListener.kt
  android/app/src/main/java/com/mulberry/ody/presentation/room/detail/listener/InviteCodeCopyListener.kt
  android/app/src/main/java/com/mulberry/ody/presentation/room/detail/model/DetailMeetingUiModel.kt
  android/app/src/main/java/com/mulberry/ody/presentation/room/detail/model/DetailMeetingUiModelMapper.kt
  android/app/src/main/java/com/mulberry/ody/presentation/room/detail/model/InviteCodeCopyInfo.kt
  android/app/src/main/java/com/mulberry/ody/presentation/room/detail/model/MateUiModelMapper.kt
  android/app/src/main/java/com/mulberry/ody/presentation/room/detail/model/MatesUiModel.kt
  android/app/src/main/java/com/mulberry/ody/presentation/room/etadashboard/EtaDashboardBindingAdapter.kt
  android/app/src/main/java/com/mulberry/ody/presentation/room/log/NotificationLogFragment.kt
  android/app/src/main/java/com/mulberry/ody/presentation/room/log/adapter/MateViewHolder.kt
  android/app/src/main/java/com/mulberry/ody/presentation/room/log/adapter/MatesAdapter.kt
  android/app/src/main/java/com/mulberry/ody/presentation/room/log/model/MateUiModel.kt
  android/app/src/main/java/com/mulberry/ody/presentation/room/log/model/MeetingDetailUiModel.kt
  android/app/src/main/java/com/mulberry/ody/presentation/room/log/model/MeetingDetailUiModelMapper.kt
  android/app/src/main/res/drawable/selector_detail_meeting_button.xml
  android/app/src/main/res/layout/fragment_detail_meeting.xml
  android/app/src/main/res/layout/fragment_notification_log.xml
  android/app/src/main/res/layout/item_invite_code_copy.xml
  android/app/src/main/res/layout/item_mate.xml
  android/app/src/main/res/values/strings.xml
  android/app/src/test/java/com/mulberry/ody/TestFixtures.kt
  android/app/src/test/java/com/mulberry/ody/presentation/room/MeetingRoomViewModelTest.kt
Labels: AN, FEATURE
