Repository woowacourse-teams/2024-ody, pull requests merged in 2025-03, with the labels that each got.

#963 feat: 약속 30분 전 최초 스케줄링 책임 백엔드로 이전
  backend/build.gradle
  backend/docker-compose-local.yml
  backend/src/main/java/com/ody/common/config/RedisConfig.java
  backend/src/main/java/com/ody/eta/domain/EtaSchedulingKey.java
  backend/src/main/java/com/ody/eta/service/EtaSchedulingRedisTemplate.java
  backend/src/main/java/com/ody/eta/service/EtaSchedulingService.java
  backend/src/main/java/com/ody/eta/service/EtaService.java
  backend/src/main/java/com/ody/eta/service/RedisKeyExpiredListener.java
  backend/src/main/java/com/ody/mate/repository/MateRepository.java
  backend/src/main/java/com/ody/meeting/repository/MeetingRepository.java
  backend/src/main/java/com/ody/meeting/service/MeetingService.java
  backend/src/main/java/com/ody/notification/domain/NotificationType.java
  backend/src/main/java/com/ody/notification/domain/message/AbstractMessage.java
  backend/src/main/java/com/ody/notification/domain/message/DirectMessage.java
  backend/src/main/java/com/ody/notification/domain/message/GroupMessage.java
  backend/src/main/java/com/ody/notification/domain/notice/EtaNotice.java
  backend/src/main/java/com/ody/notification/domain/notice/EtaSchedulingNotice.java
  backend/src/main/java/com/ody/notification/domain/notice/Notice.java
  backend/src/main/java/com/ody/notification/domain/notice/NoticeType.java
  backend/src/main/java/com/ody/notification/service/FcmEventListener.java
  backend/src/main/java/com/ody/notification/service/FcmPushSender.java
  backend/src/main/java/com/ody/notification/service/NoticeService.java
  backend/src/main/java/com/ody/notification/service/NotificationService.java
  backend/src/main/java/com/ody/notification/service/event/NoticeEvent.java
  backend/src/main/java/com/ody/notification/service/event/PushEvent.java
  backend/src/main/java/com/ody/util/TimeUtil.java
  backend/src/main/resources/common.yml
  backend/src/test/java/com/ody/common/BaseControllerTest.java
  backend/src/test/java/com/ody/common/BaseRedisTest.java
  backend/src/test/java/com/ody/common/BaseServiceTest.java
  backend/src/test/java/com/ody/common/DatabaseCleaner.java
  backend/src/test/java/com/ody/common/Fixture.java
  backend/src/test/java/com/ody/common/RedisCacheCleaner.java
  backend/src/test/java/com/ody/common/RedisTestContainersConfig.java
  backend/src/test/java/com/ody/eta/service/EtaSchedulingKeyTest.java
  backend/src/test/java/com/ody/eta/service/EtaSchedulingRedisTemplateTest.java
  backend/src/test/java/com/ody/eta/service/EtaSchedulingServiceTest.java
  backend/src/test/java/com/ody/eta/service/EtaServiceTest.java
  backend/src/test/java/com/ody/mate/controller/MateControllerTest.java
  backend/src/test/java/com/ody/meeting/repository/MeetingRepositoryTest.java
  backend/src/test/java/com/ody/meeting/service/MeetingServiceTest.java
  backend/src/test/java/com/ody/util/TimeUtilTest.java
  backend/src/test/resources/application.yml
Labels: BE, FEATURE

#986 chore: Apple 인증 정보 교체
  backend/src/main/resources/common.yml
Labels: BE, INFRA

#984 chore: 사용기간 만료에 따른 ODsay API Key 교체
  backend/src/main/resources/common.yml
Labels: BE, INFRA

#987 refactor: MeetingsActivity Compose 마이그레이션
  .github/workflows/android-ci-dev.yml
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/java/com/mulberry/ody/presentation/common/LifecycleExtensions.kt
  android/app/src/main/java/com/mulberry/ody/presentation/common/LocalDateTimeMapper.kt
  android/app/src/main/java/com/mulberry/ody/presentation/common/NoRippleInteractionSource.kt
  android/app/src/main/java/com/mulberry/ody/presentation/common/OnLifecycleEvent.kt
  android/app/src/main/java/com/mulberry/ody/presentation/common/PermissionHelper.kt
  android/app/src/main/java/com/mulberry/ody/presentation/common/modifier/NoRippleClickable.kt
  android/app/src/main/java/com/mulberry/ody/presentation/component/OdyButton.kt
  android/app/src/main/java/com/mulberry/ody/presentation/component/OdyTopAppBar.kt
  android/app/src/main/java/com/mulberry/ody/presentation/feature/meetings/MeetingsActivity.kt
  android/app/src/main/java/com/mulberry/ody/presentation/feature/meetings/MeetingsBindingAdapter.kt
  android/app/src/main/java/com/mulberry/ody/presentation/feature/meetings/MeetingsScreen.kt
  android/app/src/main/java/com/mulberry/ody/presentation/feature/meetings/MeetingsViewModel.kt
  android/app/src/main/java/com/mulberry/ody/presentation/feature/meetings/adapter/MeetingsAdapter.kt
  android/app/src/main/java/com/mulberry/ody/presentation/feature/meetings/adapter/MeetingsViewHolder.kt
  android/app/src/main/java/com/mulberry/ody/presentation/feature/meetings/component/BackPressed.kt
  android/app/src/main/java/com/mulberry/ody/presentation/feature/meetings/component/MeetingsLaunchPermission.kt
  android/app/src/main/java/com/mulberry/ody/presentation/feature/meetings/listener/MeetingsItemListener.kt
  android/app/src/main/java/com/mulberry/ody/presentation/feature/meetings/listener/MeetingsListener.kt
  android/app/src/main/java/com/mulberry/ody/presentation/feature/meetings/model/MeetingUiModel.kt
  android/app/src/main/java/com/mulberry/ody/presentation/feature/meetings/model/MeetingsUiState.kt
  android/app/src/main/java/com/mulberry/ody/presentation/theme/Color.kt
  android/app/src/main/java/com/mulberry/ody/presentation/theme/OdyTypography.kt
  android/app/src/main/res/layout/activity_meetings.xml
  android/app/src/main/res/layout/dialog_exit_meeting_room.xml
  android/app/src/main/res/layout/fragment_address_search.xml
  android/app/src/main/res/layout/item_meeting.xml
  android/app/src/main/res/layout/toolbar_intro.xml
  android/app/src/main/res/values/dimens.xml
  android/app/src/main/res/values/strings.xml
  android/app/src/test/java/com/mulberry/ody/TestFixtures.kt
  android/app/src/test/java/com/mulberry/ody/presentation/feature/meetings/MeetingsViewModelTest.kt
Labels: AN, REFACTOR

#991 refactor: SettingActivity Compose 마이그레이션
  android/app/src/main/java/com/mulberry/ody/data/repository/DefaultSettingRepository.kt
  android/app/src/main/java/com/mulberry/ody/di/AppModule.kt
  android/app/src/main/java/com/mulberry/ody/di/RepositoryModule.kt
  android/app/src/main/java/com/mulberry/ody/domain/repository/ody/SettingRepository.kt
  android/app/src/main/java/com/mulberry/ody/presentation/common/ErrorSnackbarHandler.kt
  android/app/src/main/java/com/mulberry/ody/presentation/common/OnLifecycleEvent.kt
  android/app/src/main/java/com/mulberry/ody/presentation/common/PermissionHelper.kt
  android/app/src/main/java/com/mulberry/ody/presentation/component/OdySadDialog.kt
  android/app/src/main/java/com/mulberry/ody/presentation/feature/join/MeetingJoinActivity.kt
  android/app/src/main/java/com/mulberry/ody/presentation/feature/meetings/MeetingsActivity.kt
  android/app/src/main/java/com/mulberry/ody/presentation/feature/meetings/MeetingsNavigateAction.kt
  android/app/src/main/java/com/mulberry/ody/presentation/feature/meetings/MeetingsScreen.kt
  android/app/src/main/java/com/mulberry/ody/presentation/feature/meetings/MeetingsViewModel.kt
  android/app/src/main/java/com/mulberry/ody/presentation/feature/meetings/component/MeetingsLaunchPermission.kt
  android/app/src/main/java/com/mulberry/ody/presentation/feature/setting/SettingActivity.kt
  android/app/src/main/java/com/mulberry/ody/presentation/feature/setting/SettingScreen.kt
  android/app/src/main/java/com/mulberry/ody/presentation/feature/setting/SettingViewModel.kt
  android/app/src/main/java/com/mulberry/ody/presentation/feature/setting/adapter/SettingViewHolder.kt
  android/app/src/main/java/com/mulberry/ody/presentation/feature/setting/adapter/SettingsAdapter.kt
  android/app/src/main/java/com/mulberry/ody/presentation/feature/setting/listener/SettingListener.kt
  android/app/src/main/java/com/mulberry/ody/presentation/feature/setting/model/SettingAction.kt
  android/app/src/main/java/com/mulberry/ody/presentation/feature/setting/model/SettingItemType.kt
  android/app/src/main/java/com/mulberry/ody/presentation/feature/setting/model/SettingNavigation.kt
  android/app/src/main/java/com/mulberry/ody/presentation/feature/setting/model/SettingState.kt
  android/app/src/main/java/com/mulberry/ody/presentation/feature/setting/model/SettingUiModel.kt
  android/app/src/main/java/com/mulberry/ody/presentation/feature/setting/withdrawal/WithDrawalDialog.kt
  android/app/src/main/java/com/mulberry/ody/presentation/theme/OdyTypography.kt
  android/app/src/main/res/layout/activity_setting.xml
  android/app/src/main/res/layout/dialog_withdrawal.xml
  android/app/src/main/res/layout/item_setting.xml
  android/app/src/main/res/layout/item_setting_divider.xml
  android/app/src/main/res/layout/item_setting_header.xml
  android/app/src/main/res/layout/layout_navigate_to_eta.xml
  android/app/src/main/res/layout/toolbar_setting.xml
Labels: AN, REFACTOR
