Repository woowacourse-teams/2024-ody, pull requests merged in 2025-07, with the labels that each got.

#1016 refactor: 약속 상세 화면 Compose 마이그레이션
  android/app/build.gradle.kts
  android/app/src/main/java/com/mulberry/ody/presentation/common/CommonBindingAdapter.kt
  android/app/src/main/java/com/mulberry/ody/presentation/common/DimensionExtensions.kt
  android/app/src/main/java/com/mulberry/ody/presentation/component/BaseActionHandler.kt
  android/app/src/main/java/com/mulberry/ody/presentation/component/OdyLoading.kt
  android/app/src/main/java/com/mulberry/ody/presentation/component/OdySadDialog.kt
  android/app/src/main/java/com/mulberry/ody/presentation/component/OdyTooltip.kt
  android/app/src/main/java/com/mulberry/ody/presentation/feature/address/AddressSearchScreen.kt
  android/app/src/main/java/com/mulberry/ody/presentation/feature/room/MeetingRoomViewModel.kt
  android/app/src/main/java/com/mulberry/ody/presentation/feature/room/detail/DetailMeetingBindingAdapter.kt
  android/app/src/main/java/com/mulberry/ody/presentation/feature/room/detail/DetailMeetingFragment.kt
  android/app/src/main/java/com/mulberry/ody/presentation/feature/room/detail/DetailMeetingScreen.kt
  android/app/src/main/java/com/mulberry/ody/presentation/feature/room/detail/adapter/MatesAdapter.kt
  android/app/src/main/java/com/mulberry/ody/presentation/feature/room/detail/adapter/MatesViewHolder.kt
  android/app/src/main/java/com/mulberry/ody/presentation/feature/room/detail/listener/DepartureTimeGuideListener.kt
  android/app/src/main/java/com/mulberry/ody/presentation/feature/room/detail/listener/InviteCodeCopyListener.kt
  android/app/src/main/java/com/mulberry/ody/presentation/feature/room/detail/model/DetailMeetingUiModel.kt
  android/app/src/main/java/com/mulberry/ody/presentation/feature/room/detail/model/DetailMeetingUiModelMapper.kt
  android/app/src/main/java/com/mulberry/ody/presentation/feature/room/detail/model/MateUiModel.kt
  android/app/src/main/java/com/mulberry/ody/presentation/feature/room/detail/model/MatesUiModel.kt
  android/app/src/main/java/com/mulberry/ody/presentation/feature/room/etadashboard/EtaDashboardScreen.kt
  android/app/src/main/res/anim/bounce_duration_500.xml
  android/app/src/main/res/drawable/rectangle_cream_downside_shadow_radius_30.xml
  android/app/src/main/res/drawable/rectangle_radius_15_stroke_1_gray_350.xml
  android/app/src/main/res/drawable/rectangle_radius_15_stroke_1_purple_800.xml
  android/app/src/main/res/drawable/rectangle_radius_20_without_bottom_left.xml
  android/app/src/main/res/drawable/selector_detail_meeting_button.xml
  android/app/src/main/res/layout/fragment_detail_meeting.xml
  android/app/src/main/res/layout/item_invite_code_copy.xml
  android/app/src/main/res/layout/item_mate.xml
  android/app/src/main/res/layout/item_notification_log.xml
  android/app/src/main/res/layout/layout_departure_time_tooltip.xml
  android/app/src/test/java/com/mulberry/ody/presentation/feature/room/MeetingRoomViewModelTest.kt
  android/gradle/libs.versions.toml
Labels: AN, REFACTOR

#1014 refactor: 위치 현황 화면 가이드 Compose 마이그레이션
  android/app/src/main/java/com/mulberry/ody/data/local/db/OdyDataStore.kt
  android/app/src/main/java/com/mulberry/ody/data/repository/DefaultMatesEtaRepository.kt
  android/app/src/main/java/com/mulberry/ody/domain/repository/ody/MatesEtaRepository.kt
  android/app/src/main/java/com/mulberry/ody/presentation/feature/room/MeetingRoomViewModel.kt
  android/app/src/main/java/com/mulberry/ody/presentation/feature/room/etadashboard/EtaDashboardFragment.kt
  android/app/src/main/java/com/mulberry/ody/presentation/feature/room/etadashboard/EtaDashboardScreen.kt
  android/app/src/main/java/com/mulberry/ody/presentation/feature/room/etadashboard/component/EtaDashboardItem.kt
  android/app/src/main/java/com/mulberry/ody/presentation/feature/room/etadashboard/guide/EtaDashboardFirstGuideScreen.kt
  android/app/src/main/java/com/mulberry/ody/presentation/feature/room/etadashboard/guide/EtaDashboardGuideLayout.kt
  android/app/src/main/java/com/mulberry/ody/presentation/feature/room/etadashboard/guide/EtaDashboardGuideScreen.kt
  android/app/src/main/java/com/mulberry/ody/presentation/feature/room/etadashboard/guide/EtaDashboardSecondGuideScreen.kt
  android/app/src/main/java/com/mulberry/ody/presentation/feature/room/etadashboard/guide/model/EtaDashboardGuideUiModel.kt
  android/app/src/main/java/com/mulberry/ody/presentation/feature/room/etadashboard/model/EtaStatusUiModel.kt
  android/app/src/main/java/com/mulberry/ody/presentation/theme/Color.kt
  android/app/src/test/java/com/mulberry/ody/fake/FakeMatesEtaRepository.kt
Labels: AN, DESIGN

#1005 [FEAT] trigger 도메인 분리
  backend/src/main/java/com/ody/auth/service/AuthService.java
  backend/src/main/java/com/ody/auth/service/MemberAppleTokenService.java
  backend/src/main/java/com/ody/common/aop/DeletedFilterAspect.java
  backend/src/main/java/com/ody/common/aop/EnableDeletedFilter.java
  backend/src/main/java/com/ody/eta/domain/EtaTriggerTime.java
  backend/src/main/java/com/ody/eta/service/EtaSchedulingRedisTemplate.java
  backend/src/main/java/com/ody/eta/service/EtaSchedulingService.java
  backend/src/main/java/com/ody/eta/service/EtaService.java
  backend/src/main/java/com/ody/mate/service/MateService.java
  backend/src/main/java/com/ody/meeting/service/MeetingService.java
  backend/src/main/java/com/ody/meetinglog/service/MeetingLogService.java
  backend/src/main/java/com/ody/member/service/MemberService.java
  backend/src/main/java/com/ody/notification/domain/NotificationType.java
  backend/src/main/java/com/ody/notification/domain/message/DirectMessage.java
  backend/src/main/java/com/ody/notification/domain/message/GroupMessage.java
  backend/src/main/java/com/ody/notification/domain/notice/EtaSchedulingNotice.java
  backend/src/main/java/com/ody/notification/domain/notice/NoticeType.java
  backend/src/main/java/com/ody/notification/domain/trigger/EtaTrigger.java
  backend/src/main/java/com/ody/notification/domain/trigger/MateEtaTrigger.java
  backend/src/main/java/com/ody/notification/domain/trigger/MeetingEtaTrigger.java
  backend/src/main/java/com/ody/notification/domain/trigger/TriggerType.java
  backend/src/main/java/com/ody/notification/domain/types/MateLeave.java
  backend/src/main/java/com/ody/notification/domain/types/MemberDeletion.java
  backend/src/main/java/com/ody/notification/service/FcmEventListener.java
  backend/src/main/java/com/ody/notification/service/NoticeSender.java
  backend/src/main/java/com/ody/notification/service/NotificationService.java
  backend/src/main/java/com/ody/notification/service/TriggerSender.java
  backend/src/main/java/com/ody/notification/service/event/TriggerEvent.java
  backend/src/main/java/com/ody/route/service/ApiCallService.java
  backend/src/main/java/com/ody/route/service/RouteService.java
  backend/src/test/java/com/ody/eta/service/EtaSchedulingServiceTest.java
  backend/src/test/java/com/ody/meeting/service/MeetingServiceTest.java
Labels: BE, REFACTOR

#1022 refactor: InviteCode 화면 Compose 마이그레이션
  android/app/src/main/java/com/mulberry/ody/presentation/feature/invitecode/InviteCodeActivity.kt
  android/app/src/main/java/com/mulberry/ody/presentation/feature/invitecode/InviteCodeScreen.kt
  android/app/src/main/java/com/mulberry/ody/presentation/feature/invitecode/InviteCodeViewModel.kt
  android/app/src/main/java/com/mulberry/ody/presentation/feature/invitecode/model/InviteCodeNavigateAction.kt
  android/app/src/main/res/layout/activity_invite_code.xml
  android/app/src/main/res/values/strings.xml
  android/app/src/test/java/com/mulberry/ody/presentation/feature/invitecode/InviteCodeViewModelTest.kt
Labels: AN, REFACTOR

#1018 refactor: 직렬화 라이브러리 Kotlinx Serialization으로 변경
  android/app/build.gradle.kts
  android/app/src/main/java/com/mulberry/ody/data/local/entity/eta/MateEtaInfoEntity.kt
  android/app/src/main/java/com/mulberry/ody/data/local/entity/eta/MateEtaListTypeConverter.kt
  android/app/src/main/java/com/mulberry/ody/data/remote/core/entity/ErrorResponse.kt
  android/app/src/main/java/com/mulberry/ody/data/remote/core/entity/join/request/JoinRequest.kt
  android/app/src/main/java/com/mulberry/ody/data/remote/core/entity/join/response/JoinResponse.kt
  android/app/src/main/java/com/mulberry/ody/data/remote/core/entity/login/request/LoginRequest.kt
  android/app/src/main/java/com/mulberry/ody/data/remote/core/entity/login/response/LoginResponse.kt
  android/app/src/main/java/com/mulberry/ody/data/remote/core/entity/meeting/request/MatesEtaRequest.kt
  android/app/src/main/java/com/mulberry/ody/data/remote/core/entity/meeting/request/MeetingRequest.kt
  android/app/src/main/java/com/mulberry/ody/data/remote/core/entity/meeting/request/NudgeRequest.kt
  android/app/src/main/java/com/mulberry/ody/data/remote/core/entity/meeting/response/DetailMeetingResponse.kt
  android/app/src/main/java/com/mulberry/ody/data/remote/core/entity/meeting/response/MateEtaResponse.kt
  android/app/src/main/java/com/mulberry/ody/data/remote/core/entity/meeting/response/MateResponse.kt
  android/app/src/main/java/com/mulberry/ody/data/remote/core/entity/meeting/response/MatesEtaResponse.kt
  android/app/src/main/java/com/mulberry/ody/data/remote/core/entity/meeting/response/MeetingCreationResponse.kt
  android/app/src/main/java/com/mulberry/ody/data/remote/core/entity/meeting/response/MeetingResponse.kt
  android/app/src/main/java/com/mulberry/ody/data/remote/core/entity/meeting/response/MeetingsResponse.kt
  android/app/src/main/java/com/mulberry/ody/data/remote/core/entity/notification/response/NotificationLogResponse.kt
  android/app/src/main/java/com/mulberry/ody/data/remote/core/entity/notification/response/NotificationLogsResponse.kt
  android/app/src/main/java/com/mulberry/ody/data/remote/retrofit/ApiResultCall.kt
  android/app/src/main/java/com/mulberry/ody/data/remote/thirdparty/address/response/AddressResponse.kt
  android/app/src/main/java/com/mulberry/ody/data/remote/thirdparty/address/response/Document.kt
  android/app/src/main/java/com/mulberry/ody/data/remote/thirdparty/address/response/Meta.kt
  android/app/src/main/java/com/mulberry/ody/data/remote/thirdparty/address/response/SameName.kt
  android/app/src/main/java/com/mulberry/ody/data/remote/thirdparty/address/response/coord/Address.kt
  android/app/src/main/java/com/mulberry/ody/data/remote/thirdparty/address/response/coord/AddressByCoordinateResponse.kt
  android/app/src/main/java/com/mulberry/ody/data/remote/thirdparty/address/response/coord/Document.kt
  android/app/src/main/java/com/mulberry/ody/data/remote/thirdparty/address/response/coord/Meta.kt
  android/app/src/main/java/com/mulberry/ody/data/remote/thirdparty/address/response/coord/RoadAddress.kt
  android/app/src/main/java/com/mulberry/ody/di/NetworkModule.kt
  android/app/src/main/java/com/mulberry/ody/domain/model/EtaStatus.kt
  android/app/src/main/java/com/mulberry/ody/domain/model/MateEta.kt
  android/gradle/libs.versions.toml
Labels: AN, REFACTOR

#1024 feat: FCM 알림 발송 우선순위 조정
  backend/src/main/java/com/ody/notification/domain/message/DirectMessage.java
  backend/src/main/java/com/ody/notification/domain/message/FcmPriorityResolver.java
  backend/src/main/java/com/ody/notification/domain/message/GroupMessage.java
  backend/src/main/java/com/ody/notification/domain/message/MessagePriority.java
  backend/src/main/java/com/ody/notification/domain/trigger/EtaTrigger.java
  backend/src/main/java/com/ody/notification/domain/trigger/MateEtaTrigger.java
  backend/src/main/java/com/ody/notification/domain/trigger/MeetingEtaTrigger.java
  backend/src/main/java/com/ody/notification/dto/response/MessagePriorityConfigs.java
  backend/src/main/java/com/ody/notification/service/TriggerSender.java
  backend/src/test/java/com/ody/notification/domain/message/FcmPriorityResolverTest.java
Labels: BE
