Repository woowacourse-teams/2024-ody, pull requests merged in 2025-08, with the labels that each got.

#1033 refactor: sdk 버전 변경 및 포그라운드 서비스 type 수정
  android/app/build.gradle.kts
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/java/com/mulberry/ody/data/local/service/EtaDashboardService.kt
Labels: AN, REFACTOR

#1045 fix: 정상배포를 위한 테스트 타임존 설정
  backend/src/test/java/com/ody/common/BaseRepositoryTest.java
Labels: BE, BUG

#1048 release: 백엔드 v2.3.6 배포
  backend/src/test/java/com/ody/common/BaseRepositoryTest.java
Labels: BE, RELEASE

#1036 chore: 인프라 이전
  .github/workflows/backend-cd-prod.yml
  backend/src/main/java/com/ody/eta/service/RedisKeyExpiredListener.java
  backend/src/main/java/com/ody/meeting/service/MeetingService.java
  backend/src/main/resources/application-prod.yml
  backend/src/test/java/com/ody/meetinglog/repository/MeetingLogRepositoryTest.java
Labels: BE, INFRA
