Repository woowacourse-teams/2024-ody, pull requests merged in 2025-04, with the labels that each got.

#982 refactor: meetingLog 도메인 추가
  backend/src/main/java/com/ody/mate/service/MateService.java
  backend/src/main/java/com/ody/meeting/controller/MeetingController.java
  backend/src/main/java/com/ody/meetinglog/domain/MeetingLog.java
  backend/src/main/java/com/ody/meetinglog/domain/MeetingLogType.java
  backend/src/main/java/com/ody/meetinglog/repository/MeetingLogRepository.java
  backend/src/main/java/com/ody/meetinglog/service/MeetingLogService.java
  backend/src/main/java/com/ody/notification/dto/response/NotiLogFindResponse.java
  backend/src/main/java/com/ody/notification/dto/response/NotiLogFindResponses.java
  backend/src/main/java/com/ody/notification/service/FcmPushSender.java
  backend/src/main/java/com/ody/notification/service/NotificationService.java
  backend/src/main/java/com/ody/util/ScheduleRunner.java
  backend/src/main/resources/db/migration/V13__add_meeting_log_table.sql
  backend/src/test/java/com/ody/common/BaseRepositoryTest.java
  backend/src/test/java/com/ody/common/FixtureGenerator.java
  backend/src/test/java/com/ody/common/FixtureGeneratorConfig.java
  backend/src/test/java/com/ody/eta/service/EtaSchedulingServiceTest.java
  backend/src/test/java/com/ody/mate/service/MateServiceTest.java
  backend/src/test/java/com/ody/meetinglog/repository/MeetingLogRepositoryTest.java
  backend/src/test/java/com/ody/notification/service/FcmPushSenderTest.java
  backend/src/test/java/com/ody/notification/service/NotificationServiceTest.java
Labels: BE, REFACTOR

#995 fix: 애플 로그인 AppleRefreshToken 널 값 에러 해결
  backend/src/main/java/com/ody/auth/dto/response/AppleAuthValidationResponse.java
  backend/src/test/java/com/ody/auth/dto/response/AppleAuthValidationResponseTest.java
Labels: BE, BUG

#935 refactor: 스케줄링 로직 서버로 이전
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/java/com/mulberry/ody/data/local/db/OdyDatastore.kt
  android/app/src/main/java/com/mulberry/ody/data/local/service/EtaDashboard.kt
  android/app/src/main/java/com/mulberry/ody/data/local/service/EtaDashboardAlarm.kt
  android/app/src/main/java/com/mulberry/ody/data/local/service/EtaDashboardCloseBroadcastReceiver.kt
  android/app/src/main/java/com/mulberry/ody/data/local/service/EtaDashboardOpenBroadcastReceiver.kt
  android/app/src/main/java/com/mulberry/ody/data/local/service/EtaDashboardService.kt
  android/app/src/main/java/com/mulberry/ody/data/local/service/ReinstallBroadcastReceiver.kt
  android/app/src/main/java/com/mulberry/ody/data/remote/thirdparty/fcm/service/FCMService.kt
  android/app/src/main/java/com/mulberry/ody/data/repository/DefaultMatesEtaRepository.kt
  android/app/src/main/java/com/mulberry/ody/di/AppModule.kt
  android/app/src/main/java/com/mulberry/ody/domain/model/FCMType.kt
  android/app/src/main/java/com/mulberry/ody/domain/model/NotificationType.kt
  android/app/src/main/java/com/mulberry/ody/domain/repository/ody/MatesEtaRepository.kt
  android/app/src/main/java/com/mulberry/ody/presentation/feature/join/MeetingJoinViewModel.kt
  android/app/src/main/java/com/mulberry/ody/presentation/feature/login/LoginViewModel.kt
  android/app/src/main/java/com/mulberry/ody/presentation/feature/room/MeetingRoomViewModel.kt
  android/app/src/main/java/com/mulberry/ody/presentation/feature/setting/SettingViewModel.kt
  android/app/src/main/java/com/mulberry/ody/presentation/notification/FCMNotification.kt
  android/app/src/test/java/com/mulberry/ody/fake/FakeMatesEtaRepository.kt
  android/app/src/test/java/com/mulberry/ody/presentation/feature/join/MeetingJoinViewModelTest.kt
Labels: AN, REFACTOR

#993 refactor: AddressSearchFragment Compose 마이그레이션
  android/app/build.gradle.kts
  android/app/src/main/java/com/mulberry/ody/domain/apiresult/ApiResult.kt
  android/app/src/main/java/com/mulberry/ody/domain/apiresult/ApiResultExtensions.kt
  android/app/src/main/java/com/mulberry/ody/presentation/component/BaseActionHandler.kt
  android/app/src/main/java/com/mulberry/ody/presentation/component/OdyLoading.kt
  android/app/src/main/java/com/mulberry/ody/presentation/component/OdyTextField.kt
  android/app/src/main/java/com/mulberry/ody/presentation/feature/address/AddressSearchFragment.kt
  android/app/src/main/java/com/mulberry/ody/presentation/feature/address/AddressSearchScreen.kt
  android/app/src/main/java/com/mulberry/ody/presentation/feature/address/AddressSearchViewModel.kt
  android/app/src/main/java/com/mulberry/ody/presentation/feature/address/adapter/AddressesAdapter.kt
  android/app/src/main/java/com/mulberry/ody/presentation/feature/address/listener/AddressListener.kt
  android/app/src/main/java/com/mulberry/ody/presentation/feature/address/listener/AddressViewHolder.kt
  android/app/src/main/java/com/mulberry/ody/presentation/feature/creation/MeetingCreationActivity.kt
  android/app/src/main/java/com/mulberry/ody/presentation/feature/meetings/MeetingsScreen.kt
  android/app/src/main/java/com/mulberry/ody/presentation/feature/meetings/MeetingsViewModel.kt
  android/app/src/main/java/com/mulberry/ody/presentation/feature/meetings/component/MeetingsBackPressed.kt
  android/app/src/main/java/com/mulberry/ody/presentation/feature/meetings/model/MeetingsUiState.kt
  android/app/src/main/java/com/mulberry/ody/presentation/feature/setting/SettingScreen.kt
  android/app/src/main/res/layout/fragment_address_search.xml
  android/app/src/main/res/layout/item_address_search.xml
  android/app/src/main/res/layout/toolbar_address_search.xml
  android/app/src/test/java/com/mulberry/ody/presentation/feature/address/AddressSearchViewModelTest.kt
  android/gradle/libs.versions.toml
Labels: AN, REFACTOR
